#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/linux-3.2.0-PAE/output/TestLinMemDump /home/scudette/projects/rekall-test/linux-3.2.0-PAE/TestLinMemDump
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/linux-3.2.0-PAE/output/TestLinMemDump /home/scudette/projects/rekall-test/linux-3.2.0-PAE/TestLinMemDump
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/linux-3.2.0-PAE/output/TestLinMemDump /home/scudette/projects/rekall-test/linux-3.2.0-PAE/TestLinMemDump
elif [ "$1" == "run" ]; then
   rekall  -v --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/linux-3.2.0-PAE/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/linux-3.2.0-PAE/Linux-3.2.0-4-686-pae.E01' - memdump --proc_regex bash --dump_dir /tmp/tmpyQ2iUI/TestLinMemDumpThread-4
else
   less /home/scudette/projects/rekall-test/linux-3.2.0-PAE/output/TestLinMemDump
fi
exit 0
{
    "failours": {
        "testCase (rekall.plugins.linux.pslist.TestLinMemDump)": {
            "testCase (rekall.plugins.linux.pslist.TestLinMemDump)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 252, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 360, in testCase\n    self.assertEqual(self.baseline['hashes'], self.current['hashes'])\nAssertionError: {u'bash_2362.dmp': u'017e4870bd5c2e89cd1aee96881b10e5', u'bash_2362.dmp.idx': u' [truncated]... != {'bash_2362.dmp': '017e4870bd5c2e89cd1aee96881b10e5', 'bash_2362.dmp.idx': '272c [truncated]...\n- {u'bash_2362.dmp': u'017e4870bd5c2e89cd1aee96881b10e5',\n?  -                 -\n\n+ {'bash_2362.dmp': '017e4870bd5c2e89cd1aee96881b10e5',\n-  u'bash_2362.dmp.idx': u'6a12df05feab4bc8ea6379fd6a2f1af5'}\n+  'bash_2362.dmp.idx': '272c41a6367d3e3e095ab1522fd07ec0'}\n"
        }
    }, 
    "errors": {
        "testCase (rekall.plugins.linux.pslist.TestLinMemDump)": {}
    }, 
    "logging": [
        "2016-03-28 09:56:42,898:DEBUG:rekall.1:Logging level set to 10", 
        "2016-03-28 09:56:42,899:DEBUG:rekall.1:Voting round with base: None", 
        "2016-03-28 09:56:42,899:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-03-28 09:56:42,899:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided", 
        "2016-03-28 09:56:42,899:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-03-28 09:56:42,899:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space", 
        "2016-03-28 09:56:42,899:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-03-28 09:56:42,899:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided", 
        "2016-03-28 09:56:42,900:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-03-28 09:56:42,900:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided", 
        "2016-03-28 09:56:42,900:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-03-28 09:56:42,900:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space", 
        "2016-03-28 09:56:42,900:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-03-28 09:56:42,900:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space", 
        "2016-03-28 09:56:42,900:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-03-28 09:56:42,901:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided", 
        "2016-03-28 09:56:42,901:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-03-28 09:56:42,901:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided", 
        "2016-03-28 09:56:42,901:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-03-28 09:56:42,901:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space", 
        "2016-03-28 09:56:42,901:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-03-28 09:56:42,901:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.", 
        "2016-03-28 09:56:42,901:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-03-28 09:56:42,902:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume", 
        "2016-03-28 09:56:42,902:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-03-28 09:56:42,903:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at /home/scudette/projects/rekall-test/linux-3.2.0-PAE/Linux-3.2.0-4-686-pae.E01_info", 
        "2016-03-28 09:56:42,903:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-03-28 09:56:42,903:DEBUG:rekall.1:Succeeded instantiating FileAddressSpace", 
        "2016-03-28 09:56:42,903:DEBUG:rekall.1:Voting round with base: FileAddressSpace", 
        "2016-03-28 09:56:42,903:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-03-28 09:56:42,904:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x9465645", 
        "2016-03-28 09:56:42,904:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-03-28 09:56:42,905:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-03-28 09:56:42,905:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-03-28 09:56:42,905:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-03-28 09:56:42,905:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-03-28 09:56:42,911:DEBUG:rekall.1:Succeeded instantiating EWFAddressSpace", 
        "2016-03-28 09:56:42,911:DEBUG:rekall.1:Voting round with base: EWFAddressSpace", 
        "2016-03-28 09:56:42,911:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-03-28 09:56:42,912:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0", 
        "2016-03-28 09:56:42,912:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-03-28 09:56:42,913:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-03-28 09:56:42,913:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-03-28 09:56:42,913:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-03-28 09:56:42,913:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-03-28 09:56:42,913:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "2016-03-28 09:56:42,913:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-03-28 09:56:42,914:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "2016-03-28 09:56:42,914:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-03-28 09:56:42,914:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "2016-03-28 09:56:42,914:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-03-28 09:56:42,914:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "2016-03-28 09:56:42,914:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-03-28 09:56:42,914:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "2016-03-28 09:56:42,914:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-03-28 09:56:42,914:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "2016-03-28 09:56:42,915:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-03-28 09:56:42,915:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature", 
        "2016-03-28 09:56:42,915:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-03-28 09:56:42,915:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space", 
        "2016-03-28 09:56:42,915:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-03-28 09:56:42,916:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.", 
        "2016-03-28 09:56:42,916:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-03-28 09:56:42,916:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space", 
        "2016-03-28 09:56:42,916:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> ", 
        "2016-03-28 09:56:42,916:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space", 
        "2016-03-28 09:56:42,916:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> ", 
        "2016-03-28 09:56:42,917:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified", 
        "2016-03-28 09:56:42,917:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> ", 
        "2016-03-28 09:56:42,918:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.", 
        "2016-03-28 09:56:42,918:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> ", 
        "2016-03-28 09:56:42,918:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified", 
        "2016-03-28 09:56:42,919:INFO:rekall.1:Autodetected physical address space EWFAddressSpace", 
        "2016-03-28 09:56:42,919:DEBUG:rekall.1:Will detect profile using these Detectors: linux_index,nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux", 
        "2016-03-28 09:56:43,444:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master//v1.0/inventory.gz", 
        "2016-03-28 09:56:43,515:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/inventory.gz", 
        "2016-03-28 09:56:43,516:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/Linux/index.gz", 
        "2016-03-28 09:56:43,586:INFO:rekall.1:Loaded profile Linux/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0706398487091 sec)", 
        "2016-03-28 09:56:43,587:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/eprocess_index.gz", 
        "2016-03-28 09:56:43,633:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0463500022888 sec)", 
        "2016-03-28 09:56:43,634:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/index.gz", 
        "2016-03-28 09:56:43,696:INFO:rekall.1:Loaded profile nt/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0623919963837 sec)", 
        "2016-03-28 09:56:43,697:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/OSX/index.gz", 
        "2016-03-28 09:56:43,698:INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.00110721588135 sec)", 
        "2016-03-28 09:56:43,698:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/pe.gz", 
        "2016-03-28 09:56:43,715:INFO:rekall.1:Loaded profile pe from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0173559188843 sec)", 
        "2016-03-28 09:56:43,716:DEBUG:rekall.1:Trying method pe, offset 0", 
        "2016-03-28 09:56:43,719:DEBUG:rekall.1:Trying method windows_kernel_file, offset 0", 
        "2016-03-28 09:56:43,719:DEBUG:rekall.1:Trying method rsds, offset 0", 
        "2016-03-28 09:56:43,719:DEBUG:rekall.1:Trying method linux_index, offset 0", 
        "2016-03-28 09:56:43,720:DEBUG:rekall.1:LinuxIndexDetector:DetectFromHit(0) = None", 
        "2016-03-28 09:56:43,720:DEBUG:rekall.1:Trying method nt_index, offset 0", 
        "2016-03-28 09:56:43,720:DEBUG:rekall.1:Trying method ntfs, offset 0", 
        "2016-03-28 09:56:43,720:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/ntfs.gz", 
        "2016-03-28 09:56:43,722:INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.00198912620544 sec)", 
        "2016-03-28 09:56:44,099:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/Debian/3.2.0-4-686-pae.gz", 
        "2016-03-28 09:56:44,748:INFO:rekall.1:Loaded profile Debian/3.2.0-4-686-pae from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.649235010147 sec)", 
        "2016-03-28 09:56:44,748:INFO:rekall.1:Detected Debian/3.2.0-4-686-pae: Linux version 3.2.0-4-686-pae", 
        "2016-03-28 09:56:44,752:DEBUG:rekall.1:Calculating page offset...", 
        "2016-03-28 09:56:44,753:INFO:rekall.1:Found slide 0x0", 
        "2016-03-28 09:56:44,756:DEBUG:rekall.1:Detection method linux worked at offset 0x12cb06c", 
        "2016-03-28 09:56:44,757:DEBUG:rekall.1:Running plugin (memdump) with args (()) kwargs ({'profile': None, 'all': False, 'task': None, 'task_head': None, 'pid': None, 'proc_regex': 'bash', 'coalesce': False, 'phys_task': None, 'dump_dir': '/tmp/tmpyQ2iUI/TestLinMemDumpThread-4', 'method': ['InitTask']})", 
        "2016-03-28 09:56:44,791:DEBUG:rekall.1:Listed 62 processes using InitTask"
    ], 
    "time_used": 4.749531984329224, 
    "return_code": 0, 
    "output": [
        "**************************************************", 
        "Writing 0xf5836640||bash||  2362 to bash_2362.dmp"
    ], 
    "hashes": {
        "bash_2362.dmp": "017e4870bd5c2e89cd1aee96881b10e5", 
        "bash_2362.dmp.idx": "272c41a6367d3e3e095ab1522fd07ec0"
    }, 
    "options": {
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/linux-3.2.0-PAE/Linux-3.2.0-4-686-pae.E01", 
        "--format": "test", 
        "commandline": "memdump --proc_regex %(proc_name)s --dump_dir %(tempdir)s", 
        "proc_name": "bash", 
        "pid": 2362, 
        "test_class": "TestLinMemDump", 
        "--cache_dir": "/home/scudette/projects/rekall-test/linux-3.2.0-PAE/../profile_cache/", 
        "--cache": "memory", 
        "tempdir": "/tmp/tmpyQ2iUI/TestLinMemDumpThread-4", 
        "executed_command": "rekall  -v --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/linux-3.2.0-PAE/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/linux-3.2.0-PAE/Linux-3.2.0-4-686-pae.E01' - memdump --proc_regex bash --dump_dir /tmp/tmpyQ2iUI/TestLinMemDumpThread-4", 
        "testdir": "/home/scudette/projects/rekall-test/linux-3.2.0-PAE"
    }
}