#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /usr/local/google/home/jordisanchez/projects/rekall/rekall-test/linux-3.2.0-PAE/output/TestCheckAFInfo /usr/local/google/home/jordisanchez/projects/rekall/rekall-test/linux-3.2.0-PAE/TestCheckAFInfo
elif [ "$1" == "meld" ]; then
   meld /usr/local/google/home/jordisanchez/projects/rekall/rekall-test/linux-3.2.0-PAE/output/TestCheckAFInfo /usr/local/google/home/jordisanchez/projects/rekall/rekall-test/linux-3.2.0-PAE/TestCheckAFInfo
elif [ "$1" == "diff" ]; then
   diff /usr/local/google/home/jordisanchez/projects/rekall/rekall-test/linux-3.2.0-PAE/output/TestCheckAFInfo /usr/local/google/home/jordisanchez/projects/rekall/rekall-test/linux-3.2.0-PAE/TestCheckAFInfo
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/usr/local/google/home/jordisanchez/projects/rekall/rekall-test/linux-3.2.0-PAE/Linux-3.2.0-4-686-pae.E01' - check_afinfo
else
   less /usr/local/google/home/jordisanchez/projects/rekall/rekall-test/linux-3.2.0-PAE/output/TestCheckAFInfo
fi
exit 0
{
    "errors": {}, 
    "time_used": 16.88157296180725, 
    "return_code": 0, 
    "failures": {}, 
    "output": [
        "        Constant Name         ||            Member            || Address  ||       Module       ", 
        "------------------------------||------------------------------||----------||--------------------", 
        "tcp6_seq_afinfo               ||seq_ops.start                 ||0xc12575d8||linux               ", 
        "tcp6_seq_afinfo               ||seq_ops.next                  ||0xc1257565||linux               ", 
        "tcp6_seq_afinfo               ||seq_ops.stop                  ||0xc1256d28||linux               ", 
        "tcp6_seq_afinfo               ||seq_ops.show                  ||0xc129a9a3||linux               ", 
        "tcp6_seq_afinfo               ||seq_fops.llseek               ||0xc10e192b||linux               ", 
        "tcp6_seq_afinfo               ||seq_fops.open                 ||0xc1256f26||linux               ", 
        "tcp6_seq_afinfo               ||seq_fops.read                 ||0xc10e1a56||linux               ", 
        "tcp6_seq_afinfo               ||seq_fops.release              ||0xc110a126||linux               ", 
        "tcp4_seq_afinfo               ||seq_ops.start                 ||0xc12575d8||linux               ", 
        "tcp4_seq_afinfo               ||seq_ops.next                  ||0xc1257565||linux               ", 
        "tcp4_seq_afinfo               ||seq_ops.stop                  ||0xc1256d28||linux               ", 
        "tcp4_seq_afinfo               ||seq_ops.show                  ||0xc12569af||linux               ", 
        "tcp4_seq_afinfo               ||seq_fops.llseek               ||0xc10e192b||linux               ", 
        "tcp4_seq_afinfo               ||seq_fops.open                 ||0xc1256f26||linux               ", 
        "tcp4_seq_afinfo               ||seq_fops.read                 ||0xc10e1a56||linux               ", 
        "tcp4_seq_afinfo               ||seq_fops.release              ||0xc110a126||linux               ", 
        "udplite6_seq_afinfo           ||seq_ops.start                 ||0xc125d3ce||linux               ", 
        "udplite6_seq_afinfo           ||seq_ops.next                  ||0xc125c25e||linux               ", 
        "udplite6_seq_afinfo           ||seq_ops.stop                  ||0xc125c15e||linux               ", 
        "udplite6_seq_afinfo           ||seq_ops.show                  ||0xc12904cd||linux               ", 
        "udplite6_seq_afinfo           ||seq_fops.llseek               ||0xc10e192b||linux               ", 
        "udplite6_seq_afinfo           ||seq_fops.open                 ||0xc125c27f||linux               ", 
        "udplite6_seq_afinfo           ||seq_fops.read                 ||0xc10e1a56||linux               ", 
        "udplite6_seq_afinfo           ||seq_fops.release              ||0xc110a126||linux               ", 
        "udp6_seq_afinfo               ||seq_ops.start                 ||0xc125d3ce||linux               ", 
        "udp6_seq_afinfo               ||seq_ops.next                  ||0xc125c25e||linux               ", 
        "udp6_seq_afinfo               ||seq_ops.stop                  ||0xc125c15e||linux               ", 
        "udp6_seq_afinfo               ||seq_ops.show                  ||0xc12904cd||linux               ", 
        "udp6_seq_afinfo               ||seq_fops.llseek               ||0xc10e192b||linux               ", 
        "udp6_seq_afinfo               ||seq_fops.open                 ||0xc125c27f||linux               ", 
        "udp6_seq_afinfo               ||seq_fops.read                 ||0xc10e1a56||linux               ", 
        "udp6_seq_afinfo               ||seq_fops.release              ||0xc110a126||linux               ", 
        "udplite4_seq_afinfo           ||seq_ops.start                 ||0xc125d3ce||linux               ", 
        "udplite4_seq_afinfo           ||seq_ops.next                  ||0xc125c25e||linux               ", 
        "udplite4_seq_afinfo           ||seq_ops.stop                  ||0xc125c15e||linux               ", 
        "udplite4_seq_afinfo           ||seq_ops.show                  ||0xc125d2cc||linux               ", 
        "udplite4_seq_afinfo           ||seq_fops.llseek               ||0xc10e192b||linux               ", 
        "udplite4_seq_afinfo           ||seq_fops.open                 ||0xc125c27f||linux               ", 
        "udplite4_seq_afinfo           ||seq_fops.read                 ||0xc10e1a56||linux               ", 
        "udplite4_seq_afinfo           ||seq_fops.release              ||0xc110a126||linux               ", 
        "udp4_seq_afinfo               ||seq_ops.start                 ||0xc125d3ce||linux               ", 
        "udp4_seq_afinfo               ||seq_ops.next                  ||0xc125c25e||linux               ", 
        "udp4_seq_afinfo               ||seq_ops.stop                  ||0xc125c15e||linux               ", 
        "udp4_seq_afinfo               ||seq_ops.show                  ||0xc125d2cc||linux               ", 
        "udp4_seq_afinfo               ||seq_fops.llseek               ||0xc10e192b||linux               ", 
        "udp4_seq_afinfo               ||seq_fops.open                 ||0xc125c27f||linux               ", 
        "udp4_seq_afinfo               ||seq_fops.read                 ||0xc10e1a56||linux               ", 
        "udp4_seq_afinfo               ||seq_fops.release              ||0xc110a126||linux               "
    ], 
    "options": {
        "executable": "rekall ", 
        "--filename": "/usr/local/google/home/jordisanchez/projects/rekall/rekall-test/linux-3.2.0-PAE/Linux-3.2.0-4-686-pae.E01", 
        "tempdir": "/tmp/tmpbSzysp/TestCheckAFInfoThread-3", 
        "executed_command": "rekall  --renderer 'test' --filename '/usr/local/google/home/jordisanchez/projects/rekall/rekall-test/linux-3.2.0-PAE/Linux-3.2.0-4-686-pae.E01' - check_afinfo", 
        "commandline": "check_afinfo", 
        "--renderer": "test", 
        "testdir": "/usr/local/google/home/jordisanchez/projects/rekall/rekall-test/linux-3.2.0-PAE", 
        "test_class": "TestCheckAFInfo"
    }
}