#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/linux-3.2.0-PAE/output/TestCollect /home/scudette/projects/rekall-test/linux-3.2.0-PAE/TestCollect
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/linux-3.2.0-PAE/output/TestCollect /home/scudette/projects/rekall-test/linux-3.2.0-PAE/TestCollect
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/linux-3.2.0-PAE/output/TestCollect /home/scudette/projects/rekall-test/linux-3.2.0-PAE/TestCollect
elif [ "$1" == "run" ]; then
   rekall  -v --cache_dir '/home/scudette/projects/rekall-test/linux-3.2.0-PAE/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/linux-3.2.0-PAE/Linux-3.2.0-4-686-pae.E01' - collect proc
else
   less /home/scudette/projects/rekall-test/linux-3.2.0-PAE/output/TestCollect
fi
exit 0
{
    "failours": {
        "testCase (rekall.plugins.common.search.TestCollect)": {
            "testCase (rekall.plugins.common.search.TestCollect)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 234, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 284, in testCase\n    self.assertListEqual(previous, current)\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 209, in assertListEqual\n    self.assertEqual(x, y)\nAssertionError: u' Process  ||        Name        || PID ||Producers' != u'   proc   ||        Name        || PID ||Producers'\n-  Process  ||        Name        || PID ||Producers\n?  ^   ^^^\n+    proc   ||        Name        || PID ||Producers\n?  ^^^   ^\n\n"
        }
    }, 
    "errors": {
        "testCase (rekall.plugins.common.search.TestCollect)": {}
    }, 
    "logging": [
        "DEBUG:rekall.1:Logging level set to 10", 
        "DEBUG:rekall.1:Voting round with base: None", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at /home/scudette/projects/rekall-test/linux-3.2.0-PAE/Linux-3.2.0-4-686-pae.E01_info", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "DEBUG:rekall.1:Succeeded instantiating FileAddressSpace", 
        "DEBUG:rekall.1:Voting round with base: FileAddressSpace", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x9465645", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "DEBUG:rekall.1:Succeeded instantiating EWFAddressSpace", 
        "DEBUG:rekall.1:Voting round with base: EWFAddressSpace", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> ", 
        "DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified", 
        "INFO:rekall.1:Autodetected physical address space EWFAddressSpace", 
        "DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/sessions/v1.0/sessions/index.gz", 
        "DEBUG:rekall.1:Decoded in 0.0263671875 sec.", 
        "DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/sessions/v1.0/sessions/30efaa5505e006094da27a98ebf9f6126e98d23a/profile.gz", 
        "DEBUG:rekall.1:Decoded in 0.000113010406494 sec.", 
        "DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/sessions/v1.0/sessions/30efaa5505e006094da27a98ebf9f6126e98d23a/image_fingerprint.gz", 
        "DEBUG:rekall.1:Decoded in 0.00421404838562 sec.", 
        "DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/sessions/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Decoded in 0.000236988067627 sec.", 
        "INFO:rekall.1:Detected fingerprinted image 30efaa5505e006094da27a98ebf9f6126e98d23a", 
        "DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/sessions/v1.0/sessions/30efaa5505e006094da27a98ebf9f6126e98d23a/profile.gz", 
        "DEBUG:rekall.1:Decoded in 6.60419464111e-05 sec.", 
        "DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-profiles/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/Debian/3.2.0-4-686-pae.gz", 
        "INFO:rekall.1:Loaded profile Debian/3.2.0-4-686-pae from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.792922019958 sec)", 
        "DEBUG:rekall.1:Running plugin (collect) with args (()) kwargs ({'profile': None, 'type_name': 'proc'})", 
        "DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/sessions/v1.0/sessions/30efaa5505e006094da27a98ebf9f6126e98d23a/image_fingerprint.gz", 
        "DEBUG:rekall.1:Decoded in 0.000271081924438 sec.", 
        "DEBUG:rekall.1:Flushed profile_obj in 0.00112009048462"
    ], 
    "time_used": 2.639857053756714, 
    "return_code": 0, 
    "output": [
        "   proc   ||        Name        || PID ||Producers", 
        "----------||--------------------||-----||---------"
    ], 
    "options": {
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/linux-3.2.0-PAE/Linux-3.2.0-4-686-pae.E01", 
        "struct": "proc", 
        "--format": "test", 
        "commandline": "collect %(struct)s", 
        "pid": 2362, 
        "test_class": "TestCollect", 
        "--cache_dir": "/home/scudette/projects/rekall-test/linux-3.2.0-PAE/../profile_cache/", 
        "tempdir": "/tmp/tmpK5yllh/TestCollectThread-4", 
        "executed_command": "rekall  -v --cache_dir '/home/scudette/projects/rekall-test/linux-3.2.0-PAE/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/linux-3.2.0-PAE/Linux-3.2.0-4-686-pae.E01' - collect proc", 
        "testdir": "/home/scudette/projects/rekall-test/linux-3.2.0-PAE"
    }
}