#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/osx10.9.5/output/TestListInterfaces /home/scudette/projects/rekall-test/osx10.9.5/TestListInterfaces
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/osx10.9.5/output/TestListInterfaces /home/scudette/projects/rekall-test/osx10.9.5/TestListInterfaces
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/osx10.9.5/output/TestListInterfaces /home/scudette/projects/rekall-test/osx10.9.5/TestListInterfaces
elif [ "$1" == "run" ]; then
   rekall  --cache_dir '/home/scudette/projects/rekall-test/osx10.9.5/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/osx10.9.5/vmem.e01' --name_resolution_strategies 'Module' 'Symbol' - ifconfig
else
   less /home/scudette/projects/rekall-test/osx10.9.5/output/TestListInterfaces
fi
exit 0
{
    "errors": {}, 
    "logging": "", 
    "time_used": 3.039252996444702, 
    "return_code": 0, 
    "failures": {
        "testCase (rekall.plugins.common.searches.TestListInterfaces)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 235, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 297, in testCase\n    self.assertListEqual(previous, current)\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 210, in assertListEqual\n    self.assertEqual(x, y)\nAssertionError: u'      ||                    ||, 10.0.2.15                                      [truncated]... != u'      ||                    ||, ::1                                            [truncated]...\n-       ||                    ||, 10.0.2.15                                     \n?                                  ^^^^^^^^\n+       ||                    ||, ::1                                           \n?                                 ++ ^^^^^^\n\n"
    }, 
    "output": [
        " name ||      address       ||                    address                     ", 
        "------||--------------------||------------------------------------------------", 
        "gif0  ||-                   ||-                                               ", 
        "stf0  ||-                   ||-                                               ", 
        "en0   ||08:00:27:D8:38:B4   ||(2 values): 10.0.2.15                           ", 
        "      ||                    ||, fe80:4::a00:27ff:fed8:38b4                    ", 
        "lo0   ||                    ||(3 values): 127.0.0.1                           ", 
        "      ||                    ||, ::1                                           ", 
        "      ||                    ||, fe80:1::1                                     "
    ], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/osx10.9.5/vmem.e01", 
        "--format": "test", 
        "commandline": "ifconfig", 
        "pid": 232, 
        "test_class": "TestListInterfaces", 
        "--cache_dir": "/home/scudette/projects/rekall-test/osx10.9.5/../profile_cache/", 
        "tempdir": "/tmp/tmpkHVQqz/TestListInterfacesThread-1", 
        "executed_command": "rekall  --cache_dir '/home/scudette/projects/rekall-test/osx10.9.5/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/osx10.9.5/vmem.e01' --name_resolution_strategies 'Module' 'Symbol' - ifconfig", 
        "testdir": "/home/scudette/projects/rekall-test/osx10.9.5"
    }
}