#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /Users/adamsh/Projects/test/osx10.9.5/output/TestDarwinDeadProcessCollector /Users/adamsh/Projects/test/osx10.9.5/TestDarwinDeadProcessCollector
elif [ "$1" == "meld" ]; then
   meld /Users/adamsh/Projects/test/osx10.9.5/output/TestDarwinDeadProcessCollector /Users/adamsh/Projects/test/osx10.9.5/TestDarwinDeadProcessCollector
elif [ "$1" == "diff" ]; then
   diff /Users/adamsh/Projects/test/osx10.9.5/output/TestDarwinDeadProcessCollector /Users/adamsh/Projects/test/osx10.9.5/TestDarwinDeadProcessCollector
elif [ "$1" == "run" ]; then
   rekall  -v --cache_dir '/Users/adamsh/Projects/test/osx10.9.5/../profile_cache/' --format 'test' --filename '/Users/adamsh/Projects/test/osx10.9.5/vmem.e01' --name_resolution_strategies 'Module' 'Symbol' - dead_procs
else
   less /Users/adamsh/Projects/test/osx10.9.5/output/TestDarwinDeadProcessCollector
fi
exit 0
{
    "failours": {
        "testCase (__main__.TestDarwinDeadProcessCollector)": {
            "testCase (__main__.TestDarwinDeadProcessCollector)": "Traceback (most recent call last):\n  File \"/Users/adamsh/Projects/rekall/rekall-core/rekall/testlib.py\", line 234, in run\n    testMethod()\n  File \"/Users/adamsh/Projects/rekall/rekall-core/rekall/testlib.py\", line 284, in testCase\n    self.assertEqual(previous, current)\nAssertionError: 2 != 6\n"
        }
    }, 
    "errors": {
        "testCase (__main__.TestDarwinDeadProcessCollector)": {}
    }, 
    "logging": [
        "DEBUG:rekall.1:Logging level set to 10", 
        "DEBUG:rekall.1:Voting round with base: None", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at /Users/adamsh/Projects/test/osx10.9.5/vmem.e01_info", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "DEBUG:rekall.1:Succeeded instantiating FileAddressSpace", 
        "DEBUG:rekall.1:Voting round with base: FileAddressSpace", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x9465645", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "DEBUG:rekall.1:Succeeded instantiating EWFAddressSpace", 
        "DEBUG:rekall.1:Voting round with base: EWFAddressSpace", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> ", 
        "DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified", 
        "INFO:rekall.1:Autodetected physical address space EWFAddressSpace", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/sessions/v1.0/sessions/index.gz", 
        "DEBUG:rekall.1:Decoded in 0.0297429561615 sec.", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/sessions/v1.0/sessions/2774ac25ccb23220963f9ba7da8d631dafacba02/profile.gz", 
        "DEBUG:rekall.1:Decoded in 0.000120878219604 sec.", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/sessions/v1.0/sessions/2774ac25ccb23220963f9ba7da8d631dafacba02/image_fingerprint.gz", 
        "DEBUG:rekall.1:Decoded in 0.0205821990967 sec.", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/sessions/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Decoded in 0.000306844711304 sec.", 
        "INFO:rekall.1:Detected fingerprinted image 2774ac25ccb23220963f9ba7da8d631dafacba02", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/sessions/v1.0/sessions/2774ac25ccb23220963f9ba7da8d631dafacba02/profile.gz", 
        "DEBUG:rekall.1:Decoded in 8.79764556885e-05 sec.", 
        "DEBUG:rekall.1:Opened url https://raw.githubusercontent.com/google/rekall-profiles/master/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/v1.0/OSX/10.9.5_13F34.64bit.gz", 
        "INFO:rekall.1:Loaded profile OSX/10.9.5_13F34.64bit from Local Cache Directory:/Users/adamsh/Projects/test/profile_cache (in 1.21921801567 sec)", 
        "DEBUG:rekall.1:Running plugin (dead_procs) with args (()) kwargs ({'profile': None})", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/sessions/v1.0/sessions/2774ac25ccb23220963f9ba7da8d631dafacba02/dtb.gz", 
        "DEBUG:rekall.1:Decoded in 0.00012993812561 sec.", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/sessions/v1.0/sessions/2774ac25ccb23220963f9ba7da8d631dafacba02/default_address_space.gz", 
        "DEBUG:rekall.1:Decoded in 0.000468015670776 sec.", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/sessions/v1.0/sessions/2774ac25ccb23220963f9ba7da8d631dafacba02/dead_procs.gz", 
        "DEBUG:rekall.1:Decoded in 0.0001380443573 sec.", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/sessions/v1.0/sessions/2774ac25ccb23220963f9ba7da8d631dafacba02/image_fingerprint.gz", 
        "DEBUG:rekall.1:Decoded in 0.000381946563721 sec.", 
        "DEBUG:rekall.1:Flushed profile_obj in 0.00124716758728"
    ], 
    "time_used": 3.4116790294647217, 
    "return_code": 0, 
    "output": [
        "   Process    ||        Name        || PID ", 
        "--------------||--------------------||-----", 
        "0xff800cba4a80||      talagent      ||  231", 
        "0xff800ca67098||   SubmitDiagInfo   ||  162", 
        "0xff800ca67e90||    path_helper     ||  234", 
        "0xff800d793e90||      soagent       ||  189"
    ], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/Users/adamsh/Projects/test/osx10.9.5/vmem.e01", 
        "--format": "test", 
        "commandline": "dead_procs", 
        "cache": "memory", 
        "pid": 232, 
        "test_class": "TestDarwinDeadProcessCollector", 
        "--cache_dir": "/Users/adamsh/Projects/test/osx10.9.5/../profile_cache/", 
        "tempdir": "/var/folders/00/1pjr0000h01000cxqpysvccm006t70/T/tmpNNpOYa/TestDarwinDeadProcessCollectorThread-4", 
        "executed_command": "rekall  -v --cache_dir '/Users/adamsh/Projects/test/osx10.9.5/../profile_cache/' --format 'test' --filename '/Users/adamsh/Projects/test/osx10.9.5/vmem.e01' --name_resolution_strategies 'Module' 'Symbol' - dead_procs", 
        "testdir": "/Users/adamsh/Projects/test/osx10.9.5"
    }
}