#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /Users/adamsh/Projects/rekall-test/osx10.9.5/output/TestDarwinArp /Users/adamsh/Projects/rekall-test/osx10.9.5/TestDarwinArp
elif [ "$1" == "meld" ]; then
   meld /Users/adamsh/Projects/rekall-test/osx10.9.5/output/TestDarwinArp /Users/adamsh/Projects/rekall-test/osx10.9.5/TestDarwinArp
elif [ "$1" == "diff" ]; then
   diff /Users/adamsh/Projects/rekall-test/osx10.9.5/output/TestDarwinArp /Users/adamsh/Projects/rekall-test/osx10.9.5/TestDarwinArp
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/osx10.9.5/vmem.e01' --name_resolution_strategies 'Module,Symbol' - arp
else
   less /Users/adamsh/Projects/rekall-test/osx10.9.5/output/TestDarwinArp
fi
exit 0
{
    "errors": {}, 
    "time_used": 8.285307884216309, 
    "return_code": 0, 
    "failures": {
        "testCase (__main__.TestDarwinArp)": "Traceback (most recent call last):\n  File \"/Users/adamsh/Projects/rekall/rekall/testlib.py\", line 221, in run\n    testMethod()\n  File \"/Users/adamsh/Projects/rekall/rekall/testlib.py\", line 271, in testCase\n    self.assertEqual(previous, current)\nAssertionError: u'[sockaddr sockaddr] ||[sockaddr         ||en0      ||0       ||1794    ||2014- [truncated]... != u'[sockaddr sockaddr] ||[sockaddr         ||en0      ||0       ||1430    ||2014- [truncated]...\n- [sockaddr sockaddr] ||[sockaddr         ||en0      ||0       ||1794    ||2014-12-03 15:55:42+0000||1794    ||1734    \n?                                                                 --                ^^  ------        --         ^^\n+ [sockaddr sockaddr] ||[sockaddr         ||en0      ||0       ||1430    ||2014-12-05 18:54:15+0000||1430    ||1376    \n?                                                                  ++               ^^^^^^^^           ++       + ^\n\n"
    }, 
    "output": [
        "      IP Addr       ||     MAC Addr     ||Interface||  Sent  ||  Recv  ||          Time          ||Expires || Delta  ", 
        "--------------------||------------------||---------||--------||--------||------------------------||--------||--------", 
        "[sockaddr sockaddr] ||[sockaddr         ||en0      ||0       ||1430    ||2014-12-05 18:54:15+0000||1430    ||1376    ", 
        "@ 0xFF800D4C4208    ||rt_gateway] @     ||         ||        ||        ||                        ||        ||        ", 
        "                    ||0xFF800D4C4228    ||         ||        ||        ||                        ||        ||        "
    ], 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/Users/adamsh/Projects/rekall-test/osx10.9.5/vmem.e01", 
        "commandline": "arp", 
        "--renderer": "test", 
        "test_class": "TestDarwinArp", 
        "tempdir": "/var/folders/yc/4zng19655k37kyxgskb3vvf0006t70/T/tmpB0dT24/TestDarwinArpThread-6", 
        "executed_command": "rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/osx10.9.5/vmem.e01' --name_resolution_strategies 'Module,Symbol' - arp", 
        "testdir": "/Users/adamsh/Projects/rekall-test/osx10.9.5"
    }
}