#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/osx10.9.5/output/TestWinMemDump /home/scudette/projects/rekall-test/osx10.9.5/TestWinMemDump
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/osx10.9.5/output/TestWinMemDump /home/scudette/projects/rekall-test/osx10.9.5/TestWinMemDump
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/osx10.9.5/output/TestWinMemDump /home/scudette/projects/rekall-test/osx10.9.5/TestWinMemDump
elif [ "$1" == "run" ]; then
   rekall  -v --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/osx10.9.5/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/osx10.9.5/vmem.e01' --name_resolution_strategies 'Module' 'Symbol' - memdump --pid=232 --dump_dir /tmp/tmpFAvBXH/TestWinMemDumpThread-4
else
   less /home/scudette/projects/rekall-test/osx10.9.5/output/TestWinMemDump
fi
exit 0
{
    "failours": {
        "testCase (rekall.plugins.windows.taskmods.TestWinMemDump)": {
            "testCase (rekall.plugins.windows.taskmods.TestWinMemDump)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 252, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 360, in testCase\n    self.assertEqual(self.baseline['hashes'], self.current['hashes'])\nAssertionError: {u'bash_232.dmp.idx': u'd1a891d8feb99d851f133aa7b61acc34', u'bash_232.dmp': u'20 [truncated]... != {'bash_232.dmp.idx': 'fb3f88523b8ad31a9f38c8fb7e60abb1', 'bash_232.dmp': '202452 [truncated]...\n- {u'bash_232.dmp': u'20245209dee614533ed9474ece4cba71',\n?  -                -\n\n+ {'bash_232.dmp': '20245209dee614533ed9474ece4cba71',\n-  u'bash_232.dmp.idx': u'd1a891d8feb99d851f133aa7b61acc34'}\n+  'bash_232.dmp.idx': 'fb3f88523b8ad31a9f38c8fb7e60abb1'}\n"
        }
    }, 
    "errors": {
        "testCase (rekall.plugins.windows.taskmods.TestWinMemDump)": {}
    }, 
    "logging": [
        "2016-03-28 11:00:25,772:DEBUG:rekall.1:Logging level set to 10", 
        "2016-03-28 11:00:25,773:DEBUG:rekall.1:Voting round with base: None", 
        "2016-03-28 11:00:25,773:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-03-28 11:00:25,773:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided", 
        "2016-03-28 11:00:25,773:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-03-28 11:00:25,773:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space", 
        "2016-03-28 11:00:25,773:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-03-28 11:00:25,774:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided", 
        "2016-03-28 11:00:25,774:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-03-28 11:00:25,774:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided", 
        "2016-03-28 11:00:25,775:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-03-28 11:00:25,775:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space", 
        "2016-03-28 11:00:25,775:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-03-28 11:00:25,775:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space", 
        "2016-03-28 11:00:25,775:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-03-28 11:00:25,775:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided", 
        "2016-03-28 11:00:25,775:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-03-28 11:00:25,776:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided", 
        "2016-03-28 11:00:25,776:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-03-28 11:00:25,776:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space", 
        "2016-03-28 11:00:25,776:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-03-28 11:00:25,776:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.", 
        "2016-03-28 11:00:25,776:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-03-28 11:00:25,778:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume", 
        "2016-03-28 11:00:25,778:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-03-28 11:00:25,778:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at /home/scudette/projects/rekall-test/osx10.9.5/vmem.e01_info", 
        "2016-03-28 11:00:25,779:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-03-28 11:00:25,779:DEBUG:rekall.1:Succeeded instantiating FileAddressSpace", 
        "2016-03-28 11:00:25,779:DEBUG:rekall.1:Voting round with base: FileAddressSpace", 
        "2016-03-28 11:00:25,779:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-03-28 11:00:25,782:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x9465645", 
        "2016-03-28 11:00:25,782:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-03-28 11:00:25,783:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-03-28 11:00:25,783:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-03-28 11:00:25,783:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-03-28 11:00:25,783:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-03-28 11:00:25,788:DEBUG:rekall.1:Succeeded instantiating EWFAddressSpace", 
        "2016-03-28 11:00:25,789:DEBUG:rekall.1:Voting round with base: EWFAddressSpace", 
        "2016-03-28 11:00:25,789:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-03-28 11:00:25,792:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0", 
        "2016-03-28 11:00:25,793:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-03-28 11:00:25,793:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-03-28 11:00:25,793:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-03-28 11:00:25,793:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-03-28 11:00:25,793:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-03-28 11:00:25,794:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "2016-03-28 11:00:25,794:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-03-28 11:00:25,794:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "2016-03-28 11:00:25,794:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-03-28 11:00:25,794:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "2016-03-28 11:00:25,794:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-03-28 11:00:25,795:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "2016-03-28 11:00:25,795:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-03-28 11:00:25,795:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "2016-03-28 11:00:25,795:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-03-28 11:00:25,795:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "2016-03-28 11:00:25,795:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-03-28 11:00:25,796:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature", 
        "2016-03-28 11:00:25,796:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-03-28 11:00:25,796:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space", 
        "2016-03-28 11:00:25,797:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-03-28 11:00:25,797:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.", 
        "2016-03-28 11:00:25,797:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-03-28 11:00:25,797:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space", 
        "2016-03-28 11:00:25,797:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> ", 
        "2016-03-28 11:00:25,797:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space", 
        "2016-03-28 11:00:25,797:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> ", 
        "2016-03-28 11:00:25,799:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified", 
        "2016-03-28 11:00:25,800:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> ", 
        "2016-03-28 11:00:25,800:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.", 
        "2016-03-28 11:00:25,800:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> ", 
        "2016-03-28 11:00:25,801:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified", 
        "2016-03-28 11:00:25,801:INFO:rekall.1:Autodetected physical address space EWFAddressSpace", 
        "2016-03-28 11:00:25,801:DEBUG:rekall.1:Will detect profile using these Detectors: linux_index,nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux", 
        "2016-03-28 11:00:33,378:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master//v1.0/inventory.gz", 
        "2016-03-28 11:00:33,473:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/inventory.gz", 
        "2016-03-28 11:00:33,474:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/Linux/index.gz", 
        "2016-03-28 11:00:33,550:INFO:rekall.1:Loaded profile Linux/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0766561031342 sec)", 
        "2016-03-28 11:00:33,551:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/eprocess_index.gz", 
        "2016-03-28 11:00:33,607:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0566799640656 sec)", 
        "2016-03-28 11:00:33,608:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/index.gz", 
        "2016-03-28 11:00:33,667:INFO:rekall.1:Loaded profile nt/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0595738887787 sec)", 
        "2016-03-28 11:00:33,668:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/OSX/index.gz", 
        "2016-03-28 11:00:33,669:INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.000765085220337 sec)", 
        "2016-03-28 11:00:33,669:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/pe.gz", 
        "2016-03-28 11:00:33,686:INFO:rekall.1:Loaded profile pe from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0172970294952 sec)", 
        "2016-03-28 11:00:33,687:DEBUG:rekall.1:Trying method pe, offset 0", 
        "2016-03-28 11:00:33,689:DEBUG:rekall.1:Trying method windows_kernel_file, offset 0", 
        "2016-03-28 11:00:33,690:DEBUG:rekall.1:Trying method rsds, offset 0", 
        "2016-03-28 11:00:33,690:DEBUG:rekall.1:Trying method linux_index, offset 0", 
        "2016-03-28 11:00:33,690:DEBUG:rekall.1:LinuxIndexDetector:DetectFromHit(0) = None", 
        "2016-03-28 11:00:33,691:DEBUG:rekall.1:Trying method nt_index, offset 0", 
        "2016-03-28 11:00:33,691:DEBUG:rekall.1:Trying method ntfs, offset 0", 
        "2016-03-28 11:00:33,691:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/ntfs.gz", 
        "2016-03-28 11:00:33,693:INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.00168395042419 sec)", 
        "2016-03-28 11:00:37,620:DEBUG:rekall.1:OSX/10.9.5_13F34.64bit matched offset -0x7bfb0+0x9424000=0x93a8050 ('Darwin Kernel Version ')", 
        "2016-03-28 11:00:37,621:DEBUG:rekall.1:OSX/10.9.5_13F34.64bit matched offset -0x7bf36+0x9424000=0x93a80ca ('root\\x00')", 
        "2016-03-28 11:00:37,621:DEBUG:rekall.1:OSX/10.9.5_13F34.64bit matches 2/2 comparison points", 
        "2016-03-28 11:00:37,621:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/OSX/10.9.5_13F34.64bit.gz", 
        "2016-03-28 11:00:46,186:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master//v1.0/OSX/dynamic.gz", 
        "2016-03-28 11:00:46,187:INFO:rekall.1:Loaded profile OSX/dynamic from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 7.80779480934 sec)", 
        "2016-03-28 11:00:46,187:INFO:rekall.1:Loaded profile OSX/10.9.5_13F34.64bit from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 8.56600403786 sec)", 
        "2016-03-28 11:00:46,189:DEBUG:rekall.1:Searching for KASLR hits.", 
        "2016-03-28 11:00:49,761:INFO:rekall.1:New best match: OSX/10.9.5_13F34.64bit (100% match)", 
        "2016-03-28 11:00:49,761:DEBUG:rekall.1:Detection method osx worked at offset 0x9424000", 
        "2016-03-28 11:00:49,763:DEBUG:rekall.1:Running plugin (memdump) with args (()) kwargs ({'profile': None, 'all': False, 'pid': [232], 'proc_regex': None, 'coalesce': False, 'dump_dir': '/tmp/tmpFAvBXH/TestWinMemDumpThread-4', 'phys_proc': None, 'proc': None})"
    ], 
    "time_used": 38.56314206123352, 
    "return_code": 0, 
    "output": [
        "**************************************************", 
        "Writing 0xff800cba3c88||bash||  232 to bash_232.dmp"
    ], 
    "hashes": {
        "bash_232.dmp.idx": "fb3f88523b8ad31a9f38c8fb7e60abb1", 
        "bash_232.dmp": "20245209dee614533ed9474ece4cba71"
    }, 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/osx10.9.5/vmem.e01", 
        "--format": "test", 
        "commandline": "memdump --pid=%(pid)s --dump_dir %(tempdir)s", 
        "script": "search('(SELECT proc.p_fd.fd_ofiles[4].vnode.full_path AS path FROM pslist WHERE proc.command == \"Finder\" LIMIT 1) == (SELECT proc.p_fd.fd_ofiles[4].human_name AS path FROM pslist WHERE proc.command == \"Finder\" LIMIT 1)')", 
        "pid": 232, 
        "test_class": "TestWinMemDump", 
        "--cache_dir": "/home/scudette/projects/rekall-test/osx10.9.5/../profile_cache/", 
        "--cache": "memory", 
        "tempdir": "/tmp/tmpFAvBXH/TestWinMemDumpThread-4", 
        "executed_command": "rekall  -v --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/osx10.9.5/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/osx10.9.5/vmem.e01' --name_resolution_strategies 'Module' 'Symbol' - memdump --pid=232 --dump_dir /tmp/tmpFAvBXH/TestWinMemDumpThread-4", 
        "testdir": "/home/scudette/projects/rekall-test/osx10.9.5"
    }
}