#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /Users/adamsh/Projects/test/osx10.9.5/output/TestListInterfaces /Users/adamsh/Projects/test/osx10.9.5/TestListInterfaces
elif [ "$1" == "meld" ]; then
   meld /Users/adamsh/Projects/test/osx10.9.5/output/TestListInterfaces /Users/adamsh/Projects/test/osx10.9.5/TestListInterfaces
elif [ "$1" == "diff" ]; then
   diff /Users/adamsh/Projects/test/osx10.9.5/output/TestListInterfaces /Users/adamsh/Projects/test/osx10.9.5/TestListInterfaces
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --cache_dir '/Users/adamsh/Projects/test/osx10.9.5/../profile_cache/' --filename '/Users/adamsh/Projects/test/osx10.9.5/vmem.e01' --name_resolution_strategies 'Module' 'Symbol' - ifconfig
else
   less /Users/adamsh/Projects/test/osx10.9.5/output/TestListInterfaces
fi
exit 0
{
    "errors": {}, 
    "time_used": 7.290137052536011, 
    "return_code": 0, 
    "failures": {
        "testCase (__main__.TestListInterfaces)": "Traceback (most recent call last):\n  File \"/Users/adamsh/Projects/rekall/rekall/testlib.py\", line 233, in run\n    testMethod()\n  File \"/Users/adamsh/Projects/rekall/rekall/testlib.py\", line 283, in testCase\n    self.assertEqual(previous, current)\nAssertionError: 6 != 9\n"
    }, 
    "output": [
        " name ||      address       ||                    address                     ", 
        "------||--------------------||------------------------------------------------", 
        "en0   ||08:00:27:D8:38:B4   ||(2 values): fe80:4::a00:27ff:fed8:38b4          ", 
        "      ||                    ||, 10.0.2.15                                     ", 
        "stf0  ||-                   ||-                                               ", 
        "gif0  ||-                   ||-                                               ", 
        "lo0   ||                    ||(3 values): fe80:1::1                           ", 
        "      ||                    ||, 127.0.0.1                                     ", 
        "      ||                    ||, ::1                                           "
    ], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/Users/adamsh/Projects/test/osx10.9.5/vmem.e01", 
        "--cache_dir": "/Users/adamsh/Projects/test/osx10.9.5/../profile_cache/", 
        "commandline": "ifconfig", 
        "--renderer": "test", 
        "test_class": "TestListInterfaces", 
        "tempdir": "/var/folders/00/1pjr0000h01000cxqpysvccm006t70/T/tmpwpVWxF/TestListInterfacesThread-4", 
        "executed_command": "rekall  --renderer 'test' --cache_dir '/Users/adamsh/Projects/test/osx10.9.5/../profile_cache/' --filename '/Users/adamsh/Projects/test/osx10.9.5/vmem.e01' --name_resolution_strategies 'Module' 'Symbol' - ifconfig", 
        "testdir": "/Users/adamsh/Projects/test/osx10.9.5"
    }
}