#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/osx10.9.5/output/TestDarwinBootParameters /home/scudette/projects/rekall-test/osx10.9.5/TestDarwinBootParameters
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/osx10.9.5/output/TestDarwinBootParameters /home/scudette/projects/rekall-test/osx10.9.5/TestDarwinBootParameters
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/osx10.9.5/output/TestDarwinBootParameters /home/scudette/projects/rekall-test/osx10.9.5/TestDarwinBootParameters
elif [ "$1" == "run" ]; then
   rekall  -v --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/osx10.9.5/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/osx10.9.5/vmem.e01' --name_resolution_strategies 'Module' 'Symbol' - boot_cmdline
else
   less /home/scudette/projects/rekall-test/osx10.9.5/output/TestDarwinBootParameters
fi
exit 0
{
    "failours": {
        "testCase (__main__.TestDarwinBootParameters)": {
            "testCase (__main__.TestDarwinBootParameters)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 252, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 302, in testCase\n    self.assertListEqual(previous, current)\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 224, in assertListEqual\n    self.assertEqual(len(a), len(b))\nAssertionError: 3 != 1\n"
        }
    }, 
    "errors": {
        "testCase (__main__.TestDarwinBootParameters)": {}
    }, 
    "logging": [
        "2016-05-17 14:44:43,058:DEBUG:rekall.1:Logging level set to 10", 
        "2016-05-17 14:44:43,059:DEBUG:rekall.1:Voting round with base: None", 
        "2016-05-17 14:44:43,059:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-05-17 14:44:43,059:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided", 
        "2016-05-17 14:44:43,059:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-05-17 14:44:43,059:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space", 
        "2016-05-17 14:44:43,060:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-05-17 14:44:43,060:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided", 
        "2016-05-17 14:44:43,060:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-05-17 14:44:43,060:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided", 
        "2016-05-17 14:44:43,060:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-05-17 14:44:43,060:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space", 
        "2016-05-17 14:44:43,060:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-05-17 14:44:43,060:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space", 
        "2016-05-17 14:44:43,060:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-05-17 14:44:43,061:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided", 
        "2016-05-17 14:44:43,061:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-05-17 14:44:43,061:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided", 
        "2016-05-17 14:44:43,061:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-05-17 14:44:43,061:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space", 
        "2016-05-17 14:44:43,061:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-05-17 14:44:43,061:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.", 
        "2016-05-17 14:44:43,061:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-05-17 14:44:43,064:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume", 
        "2016-05-17 14:44:43,064:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-05-17 14:44:43,064:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at /home/scudette/projects/rekall-test/osx10.9.5/vmem.e01_info", 
        "2016-05-17 14:44:43,065:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-05-17 14:44:43,065:DEBUG:rekall.1:Succeeded instantiating FileAddressSpace", 
        "2016-05-17 14:44:43,065:DEBUG:rekall.1:Voting round with base: FileAddressSpace", 
        "2016-05-17 14:44:43,065:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-05-17 14:44:43,066:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x9465645", 
        "2016-05-17 14:44:43,066:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-05-17 14:44:43,066:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-05-17 14:44:43,066:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-05-17 14:44:43,066:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-05-17 14:44:43,067:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-05-17 14:44:43,070:DEBUG:rekall.1:Succeeded instantiating EWFAddressSpace", 
        "2016-05-17 14:44:43,070:DEBUG:rekall.1:Voting round with base: EWFAddressSpace", 
        "2016-05-17 14:44:43,070:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-05-17 14:44:43,072:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0", 
        "2016-05-17 14:44:43,072:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-05-17 14:44:43,072:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-05-17 14:44:43,072:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-05-17 14:44:43,072:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-05-17 14:44:43,072:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-05-17 14:44:43,072:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "2016-05-17 14:44:43,072:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-05-17 14:44:43,072:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "2016-05-17 14:44:43,073:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-05-17 14:44:43,073:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "2016-05-17 14:44:43,073:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-05-17 14:44:43,073:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "2016-05-17 14:44:43,073:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-05-17 14:44:43,073:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "2016-05-17 14:44:43,073:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-05-17 14:44:43,073:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "2016-05-17 14:44:43,073:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-05-17 14:44:43,073:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature", 
        "2016-05-17 14:44:43,073:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-05-17 14:44:43,074:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space", 
        "2016-05-17 14:44:43,074:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-05-17 14:44:43,074:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.", 
        "2016-05-17 14:44:43,074:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-05-17 14:44:43,074:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space", 
        "2016-05-17 14:44:43,074:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> ", 
        "2016-05-17 14:44:43,074:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space", 
        "2016-05-17 14:44:43,074:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> ", 
        "2016-05-17 14:44:43,075:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified", 
        "2016-05-17 14:44:43,075:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> ", 
        "2016-05-17 14:44:43,075:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.", 
        "2016-05-17 14:44:43,075:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> ", 
        "2016-05-17 14:44:43,075:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified", 
        "2016-05-17 14:44:43,075:INFO:rekall.1:Autodetected physical address space EWFAddressSpace", 
        "2016-05-17 14:44:43,076:DEBUG:rekall.1:Will detect profile using these Detectors: linux_index,nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux", 
        "2016-05-17 14:44:43,076:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-profiles/v1.0/inventory.gz", 
        "2016-05-17 14:44:43,086:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/inventory.gz", 
        "2016-05-17 14:44:43,087:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/Linux/index.gz", 
        "2016-05-17 14:44:43,095:INFO:rekall.1:Loaded profile Linux/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.008131980896 sec)", 
        "2016-05-17 14:44:43,095:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/eprocess_index.gz", 
        "2016-05-17 14:44:43,147:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0522079467773 sec)", 
        "2016-05-17 14:44:43,148:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/index.gz", 
        "2016-05-17 14:44:43,283:INFO:rekall.1:Loaded profile nt/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.135127067566 sec)", 
        "2016-05-17 14:44:43,283:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/OSX/index.gz", 
        "2016-05-17 14:44:43,284:INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.000818014144897 sec)", 
        "2016-05-17 14:44:43,284:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/pe.gz", 
        "2016-05-17 14:44:43,308:INFO:rekall.1:Loaded profile pe from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0232548713684 sec)", 
        "2016-05-17 14:44:43,308:DEBUG:rekall.1:Trying method pe, offset 0", 
        "2016-05-17 14:44:43,311:DEBUG:rekall.1:Trying method windows_kernel_file, offset 0", 
        "2016-05-17 14:44:43,311:DEBUG:rekall.1:Trying method rsds, offset 0", 
        "2016-05-17 14:44:43,312:DEBUG:rekall.1:Trying method linux_index, offset 0", 
        "2016-05-17 14:44:43,312:DEBUG:rekall.1:LinuxIndexDetector:DetectFromHit(0) = None", 
        "2016-05-17 14:44:43,312:DEBUG:rekall.1:Trying method nt_index, offset 0", 
        "2016-05-17 14:44:43,312:DEBUG:rekall.1:Trying method ntfs, offset 0", 
        "2016-05-17 14:44:43,313:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/ntfs.gz", 
        "2016-05-17 14:44:43,315:INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.00206899642944 sec)", 
        "2016-05-17 14:44:47,590:DEBUG:rekall.1:OSX/10.9.5_13F34.64bit matched offset -0x7bfb0+0x9424000=0x93a8050 ('Darwin Kernel Version ')", 
        "2016-05-17 14:44:47,591:DEBUG:rekall.1:OSX/10.9.5_13F34.64bit matched offset -0x7bf36+0x9424000=0x93a80ca ('root\\x00')", 
        "2016-05-17 14:44:47,591:DEBUG:rekall.1:OSX/10.9.5_13F34.64bit matches 2/2 comparison points", 
        "2016-05-17 14:44:47,591:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/OSX/10.9.5_13F34.64bit.gz", 
        "2016-05-17 14:44:48,553:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-profiles/v1.0/OSX/dynamic.gz", 
        "2016-05-17 14:44:48,553:INFO:rekall.1:Loaded profile OSX/dynamic from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.00075101852417 sec)", 
        "2016-05-17 14:44:48,554:INFO:rekall.1:Loaded profile OSX/10.9.5_13F34.64bit from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.962950944901 sec)", 
        "2016-05-17 14:44:48,557:DEBUG:rekall.1:Searching for KASLR hits.", 
        "2016-05-17 14:44:51,805:INFO:rekall.1:New best match: OSX/10.9.5_13F34.64bit (100% match)", 
        "2016-05-17 14:44:51,805:DEBUG:rekall.1:Detection method osx worked at offset 0x9424000", 
        "2016-05-17 14:44:51,806:DEBUG:rekall.1:Running plugin (boot_cmdline) with args (()) kwargs ({'profile': None})"
    ], 
    "time_used": 11.251031160354614, 
    "return_code": 0, 
    "output": [
        "keepsyms=1 -v -serial=0x1"
    ], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/osx10.9.5/vmem.e01", 
        "--format": "test", 
        "commandline": "boot_cmdline", 
        "script": "search('lookup(\"_PE_state\", \"PE_state\").result.bootArgs.CommandLine')", 
        "test_class": "TestDarwinBootParameters", 
        "--cache_dir": "/home/scudette/projects/rekall-test/osx10.9.5/../profile_cache/", 
        "--cache": "memory", 
        "tempdir": "/tmp/tmpHyu_6o/TestDarwinBootParametersThread-2", 
        "executed_command": "rekall  -v --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/osx10.9.5/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/osx10.9.5/vmem.e01' --name_resolution_strategies 'Module' 'Symbol' - boot_cmdline", 
        "pids": 232, 
        "testdir": "/home/scudette/projects/rekall-test/osx10.9.5"
    }
}