#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /Users/adamsh/Projects/rekall-test/osx10.9.5/output/TestDarwinListFiles /Users/adamsh/Projects/rekall-test/osx10.9.5/TestDarwinListFiles
elif [ "$1" == "meld" ]; then
   meld /Users/adamsh/Projects/rekall-test/osx10.9.5/output/TestDarwinListFiles /Users/adamsh/Projects/rekall-test/osx10.9.5/TestDarwinListFiles
elif [ "$1" == "diff" ]; then
   diff /Users/adamsh/Projects/rekall-test/osx10.9.5/output/TestDarwinListFiles /Users/adamsh/Projects/rekall-test/osx10.9.5/TestDarwinListFiles
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/osx10.9.5/vmem.e01' --name_resolution_strategies 'Module' 'Symbol' - list_files
else
   less /Users/adamsh/Projects/rekall-test/osx10.9.5/output/TestDarwinListFiles
fi
exit 0
{
    "errors": {}, 
    "time_used": 6.94140887260437, 
    "return_code": 0, 
    "failures": {
        "testCase (__main__.TestDarwinListFiles)": "Traceback (most recent call last):\n  File \"/Users/adamsh/Projects/rekall/rekall/testlib.py\", line 227, in run\n    testMethod()\n  File \"/Users/adamsh/Projects/rekall/rekall/testlib.py\", line 277, in testCase\n    self.assertEqual(previous, current)\nAssertionError: 492 != 2\n"
    }, 
    "output": [
        "   type   ||           Sources            ||    Created    ||   Modified    ||                  path                  ", 
        "----------||------------------------------||---------------||---------------||----------------------------------------"
    ], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/Users/adamsh/Projects/rekall-test/osx10.9.5/vmem.e01", 
        "commandline": "list_files", 
        "--renderer": "test", 
        "test_class": "TestDarwinListFiles", 
        "tempdir": "/var/folders/yc/4zng19655k37kyxgskb3vvf0006t70/T/tmpao6WjV/TestDarwinListFilesThread-2", 
        "executed_command": "rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/osx10.9.5/vmem.e01' --name_resolution_strategies 'Module' 'Symbol' - list_files", 
        "testdir": "/Users/adamsh/Projects/rekall-test/osx10.9.5"
    }
}