#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /Users/adamsh/Projects/test/osx10.9.5/output/TestListTerminals /Users/adamsh/Projects/test/osx10.9.5/TestListTerminals
elif [ "$1" == "meld" ]; then
   meld /Users/adamsh/Projects/test/osx10.9.5/output/TestListTerminals /Users/adamsh/Projects/test/osx10.9.5/TestListTerminals
elif [ "$1" == "diff" ]; then
   diff /Users/adamsh/Projects/test/osx10.9.5/output/TestListTerminals /Users/adamsh/Projects/test/osx10.9.5/TestListTerminals
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --cache_dir '/Users/adamsh/Projects/test/osx10.9.5/../profile_cache/' --filename '/Users/adamsh/Projects/test/osx10.9.5/vmem.e01' --name_resolution_strategies 'Module' 'Symbol' - list_terminals
else
   less /Users/adamsh/Projects/test/osx10.9.5/output/TestListTerminals
fi
exit 0
{
    "errors": {}, 
    "time_used": 8.948025941848755, 
    "return_code": 0, 
    "failures": {
        "testCase (__main__.TestListTerminals)": "Traceback (most recent call last):\n  File \"/Users/adamsh/Projects/rekall/rekall/testlib.py\", line 233, in run\n    testMethod()\n  File \"/Users/adamsh/Projects/rekall/rekall/testlib.py\", line 283, in testCase\n    self.assertEqual(previous, current)\nAssertionError: u\"testdude       ||230            ||/dev/ttys000                  ||'\\\\rna<white [truncated]... != u\"testdude       ||230            ||/dev/ttys000                  ||u'\\\\rna<whit [truncated]...\nDiff is 885 characters long. Set self.maxDiff to None to see it.\n"
    }, 
    "output": [
        "     User      ||    Session    ||        Terminal vnode        ||                              Recovered input                              ||                             Recovered output                              ", 
        "---------------||---------------||------------------------------||---------------------------------------------------------------------------||---------------------------------------------------------------------------", 
        "testdude       ||230            ||/dev/ttys000                  ||u'\\rna<whitespace>'                                                        ||u'Tests-MacBook-Pro:~ testdude$ ocal/Users/testdude\\x07l Version 13.4.0:   ", 
        "               ||               ||                              ||                                                                           ||Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64         ", 
        "               ||               ||                              ||                                                                           ||x86_64<whitespace>'                                                        "
    ], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/Users/adamsh/Projects/test/osx10.9.5/vmem.e01", 
        "--cache_dir": "/Users/adamsh/Projects/test/osx10.9.5/../profile_cache/", 
        "commandline": "list_terminals", 
        "--renderer": "test", 
        "test_class": "TestListTerminals", 
        "tempdir": "/var/folders/00/1pjr0000h01000cxqpysvccm006t70/T/tmpisxrhV/TestListTerminalsThread-4", 
        "executed_command": "rekall  --renderer 'test' --cache_dir '/Users/adamsh/Projects/test/osx10.9.5/../profile_cache/' --filename '/Users/adamsh/Projects/test/osx10.9.5/vmem.e01' --name_resolution_strategies 'Module' 'Symbol' - list_terminals", 
        "testdir": "/Users/adamsh/Projects/test/osx10.9.5"
    }
}