#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /Users/adamsh/Projects/test/osx10.9.5/output/TestDarwinArp /Users/adamsh/Projects/test/osx10.9.5/TestDarwinArp
elif [ "$1" == "meld" ]; then
   meld /Users/adamsh/Projects/test/osx10.9.5/output/TestDarwinArp /Users/adamsh/Projects/test/osx10.9.5/TestDarwinArp
elif [ "$1" == "diff" ]; then
   diff /Users/adamsh/Projects/test/osx10.9.5/output/TestDarwinArp /Users/adamsh/Projects/test/osx10.9.5/TestDarwinArp
elif [ "$1" == "run" ]; then
   rekall  -v --cache_dir '/Users/adamsh/Projects/test/osx10.9.5/../profile_cache/' --format 'test' --filename '/Users/adamsh/Projects/test/osx10.9.5/vmem.e01' --name_resolution_strategies 'Module' 'Symbol' - arp
else
   less /Users/adamsh/Projects/test/osx10.9.5/output/TestDarwinArp
fi
exit 0
{
    "failours": {
        "testCase (__main__.TestDarwinArp)": {
            "testCase (__main__.TestDarwinArp)": "Traceback (most recent call last):\n  File \"/Users/adamsh/Projects/rekall/rekall-core/rekall/testlib.py\", line 234, in run\n    testMethod()\n  File \"/Users/adamsh/Projects/rekall/rekall-core/rekall/testlib.py\", line 284, in testCase\n    self.assertEqual(previous, current)\nAssertionError: 5 != 3\n"
        }
    }, 
    "errors": {
        "testCase (__main__.TestDarwinArp)": {}
    }, 
    "logging": [
        "DEBUG:rekall.1:Logging level set to 10", 
        "DEBUG:rekall.1:Voting round with base: None", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at /Users/adamsh/Projects/test/osx10.9.5/vmem.e01_info", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "DEBUG:rekall.1:Succeeded instantiating FileAddressSpace", 
        "DEBUG:rekall.1:Voting round with base: FileAddressSpace", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x9465645", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "DEBUG:rekall.1:Succeeded instantiating EWFAddressSpace", 
        "DEBUG:rekall.1:Voting round with base: EWFAddressSpace", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> ", 
        "DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified", 
        "INFO:rekall.1:Autodetected physical address space EWFAddressSpace", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/sessions/v1.0/sessions/index.gz", 
        "DEBUG:rekall.1:Decoded in 0.024402141571 sec.", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/sessions/v1.0/sessions/2774ac25ccb23220963f9ba7da8d631dafacba02/profile.gz", 
        "DEBUG:rekall.1:Decoded in 7.08103179932e-05 sec.", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/sessions/v1.0/sessions/2774ac25ccb23220963f9ba7da8d631dafacba02/image_fingerprint.gz", 
        "DEBUG:rekall.1:Decoded in 0.00945401191711 sec.", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/sessions/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Decoded in 0.000159025192261 sec.", 
        "INFO:rekall.1:Detected fingerprinted image 2774ac25ccb23220963f9ba7da8d631dafacba02", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/sessions/v1.0/sessions/2774ac25ccb23220963f9ba7da8d631dafacba02/profile.gz", 
        "DEBUG:rekall.1:Decoded in 5.79357147217e-05 sec.", 
        "DEBUG:rekall.1:Opened url https://raw.githubusercontent.com/google/rekall-profiles/master/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/v1.0/OSX/10.9.5_13F34.64bit.gz", 
        "INFO:rekall.1:Loaded profile OSX/10.9.5_13F34.64bit from Local Cache Directory:/Users/adamsh/Projects/test/profile_cache (in 0.859507083893 sec)", 
        "DEBUG:rekall.1:Running plugin (arp) with args (()) kwargs ({'profile': None})", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/sessions/v1.0/sessions/2774ac25ccb23220963f9ba7da8d631dafacba02/dtb.gz", 
        "DEBUG:rekall.1:Decoded in 0.000115156173706 sec.", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/sessions/v1.0/sessions/2774ac25ccb23220963f9ba7da8d631dafacba02/default_address_space.gz", 
        "DEBUG:rekall.1:Decoded in 0.000380039215088 sec.", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/sessions/v1.0/sessions/2774ac25ccb23220963f9ba7da8d631dafacba02/process_context.gz", 
        "DEBUG:rekall.1:Decoded in 0.000247001647949 sec.", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/sessions/v1.0/sessions/2774ac25ccb23220963f9ba7da8d631dafacba02/vm_kernel_slide.gz", 
        "DEBUG:rekall.1:Decoded in 8.79764556885e-05 sec.", 
        "DEBUG:rekall.1:Opened local file /Users/adamsh/Projects/test/profile_cache/sessions/v1.0/sessions/2774ac25ccb23220963f9ba7da8d631dafacba02/image_fingerprint.gz", 
        "DEBUG:rekall.1:Decoded in 0.000223159790039 sec.", 
        "DEBUG:rekall.1:Flushed profile_obj in 0.000978946685791"
    ], 
    "time_used": 2.814769983291626, 
    "return_code": 0, 
    "output": [
        "    IP Address    ||   Mac Address    ||Interface||  Sent  ||Received||             Time             ||Expires||Delta", 
        "------------------||------------------||---------||--------||--------||------------------------------||-------||-----", 
        "10.0.2.2          ||52:54:00:12:35:02 ||   en0   ||       0||    1430||     2014-12-05 18:54:15Z     ||   1430|| 1376"
    ], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/Users/adamsh/Projects/test/osx10.9.5/vmem.e01", 
        "--format": "test", 
        "commandline": "arp", 
        "cache": "memory", 
        "pid": 232, 
        "test_class": "TestDarwinArp", 
        "--cache_dir": "/Users/adamsh/Projects/test/osx10.9.5/../profile_cache/", 
        "tempdir": "/var/folders/00/1pjr0000h01000cxqpysvccm006t70/T/tmpE8HmHy/TestDarwinArpThread-1", 
        "executed_command": "rekall  -v --cache_dir '/Users/adamsh/Projects/test/osx10.9.5/../profile_cache/' --format 'test' --filename '/Users/adamsh/Projects/test/osx10.9.5/vmem.e01' --name_resolution_strategies 'Module' 'Symbol' - arp", 
        "testdir": "/Users/adamsh/Projects/test/osx10.9.5"
    }
}