#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/pe/output/TestDisassemble /home/scudette/projects/rekall-test/pe/TestDisassemble
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/pe/output/TestDisassemble /home/scudette/projects/rekall-test/pe/TestDisassemble
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/pe/output/TestDisassemble /home/scudette/projects/rekall-test/pe/TestDisassemble
elif [ "$1" == "run" ]; then
   rekall  -v --cache_dir '/home/scudette/projects/rekall-test/pe/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/pe/ntoskrnl.exe' - dis --length 20 pe!MmGetPhysicalMemoryRanges --name_resolution_strategies Export
else
   less /home/scudette/projects/rekall-test/pe/output/TestDisassemble
fi
exit 0
{
    "failours": {
        "testCase (rekall.plugins.tools.disassembler.TestDisassemble)": {
            "testCase (rekall.plugins.tools.disassembler.TestDisassemble)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 252, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 302, in testCase\n    self.assertListEqual(previous, current)\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 224, in assertListEqual\n    self.assertEqual(len(a), len(b))\nAssertionError: 24 != 25\n"
        }
    }, 
    "errors": {
        "testCase (rekall.plugins.tools.disassembler.TestDisassemble)": {}
    }, 
    "logging": [
        "2016-05-17 11:10:06,820:DEBUG:rekall.1:Logging level set to 10", 
        "2016-05-17 11:10:06,823:DEBUG:rekall.1:Running plugin (dis) with args (()) kwargs ({'end': None, 'address_space': None, 'length': 20, 'mode': None, 'branch': False, 'offset': 'pe!MmGetPhysicalMemoryRanges', 'canonical': False})", 
        "2016-05-17 11:10:06,824:DEBUG:rekall.1:Voting round with base: None", 
        "2016-05-17 11:10:06,824:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-05-17 11:10:06,824:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided", 
        "2016-05-17 11:10:06,824:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-05-17 11:10:06,825:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space", 
        "2016-05-17 11:10:06,825:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-05-17 11:10:06,825:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided", 
        "2016-05-17 11:10:06,825:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-05-17 11:10:06,826:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided", 
        "2016-05-17 11:10:06,826:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-05-17 11:10:06,826:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space", 
        "2016-05-17 11:10:06,826:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-05-17 11:10:06,826:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space", 
        "2016-05-17 11:10:06,826:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-05-17 11:10:06,826:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided", 
        "2016-05-17 11:10:06,826:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-05-17 11:10:06,826:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided", 
        "2016-05-17 11:10:06,827:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-05-17 11:10:06,827:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space", 
        "2016-05-17 11:10:06,827:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-05-17 11:10:06,827:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.", 
        "2016-05-17 11:10:06,827:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-05-17 11:10:06,828:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume", 
        "2016-05-17 11:10:06,828:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-05-17 11:10:06,829:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at /home/scudette/projects/rekall-test/pe/ntoskrnl.exe_info", 
        "2016-05-17 11:10:06,829:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-05-17 11:10:06,829:DEBUG:rekall.1:Succeeded instantiating FileAddressSpace", 
        "2016-05-17 11:10:06,829:DEBUG:rekall.1:Voting round with base: FileAddressSpace", 
        "2016-05-17 11:10:06,829:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-05-17 11:10:06,831:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x905a4d", 
        "2016-05-17 11:10:06,831:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-05-17 11:10:06,831:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-05-17 11:10:06,831:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-05-17 11:10:06,831:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-05-17 11:10:06,831:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-05-17 11:10:06,832:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "2016-05-17 11:10:06,832:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-05-17 11:10:06,835:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "2016-05-17 11:10:06,835:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-05-17 11:10:06,835:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "2016-05-17 11:10:06,835:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-05-17 11:10:06,836:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "2016-05-17 11:10:06,836:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-05-17 11:10:06,836:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "2016-05-17 11:10:06,836:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-05-17 11:10:06,836:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "2016-05-17 11:10:06,836:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-05-17 11:10:06,836:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature", 
        "2016-05-17 11:10:06,836:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-05-17 11:10:06,837:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space", 
        "2016-05-17 11:10:06,837:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-05-17 11:10:06,837:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.", 
        "2016-05-17 11:10:06,837:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-05-17 11:10:06,837:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space", 
        "2016-05-17 11:10:06,837:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> ", 
        "2016-05-17 11:10:06,838:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space", 
        "2016-05-17 11:10:06,838:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> ", 
        "2016-05-17 11:10:06,839:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified", 
        "2016-05-17 11:10:06,839:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> ", 
        "2016-05-17 11:10:06,839:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.", 
        "2016-05-17 11:10:06,839:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> ", 
        "2016-05-17 11:10:06,839:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified", 
        "2016-05-17 11:10:06,840:INFO:rekall.1:Autodetected physical address space FileAddressSpace", 
        "2016-05-17 11:10:06,841:DEBUG:rekall.1:Will detect profile using these Detectors: linux_index,nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux", 
        "2016-05-17 11:10:06,841:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-profiles/v1.0/inventory.gz", 
        "2016-05-17 11:10:06,858:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/inventory.gz", 
        "2016-05-17 11:10:06,859:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/Linux/index.gz", 
        "2016-05-17 11:10:06,870:INFO:rekall.1:Loaded profile Linux/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0111508369446 sec)", 
        "2016-05-17 11:10:06,870:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/eprocess_index.gz", 
        "2016-05-17 11:10:06,915:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0450417995453 sec)", 
        "2016-05-17 11:10:06,916:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/index.gz", 
        "2016-05-17 11:10:07,028:INFO:rekall.1:Loaded profile nt/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.112254858017 sec)", 
        "2016-05-17 11:10:07,028:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/OSX/index.gz", 
        "2016-05-17 11:10:07,028:INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.000494956970215 sec)", 
        "2016-05-17 11:10:07,029:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/pe.gz", 
        "2016-05-17 11:10:07,038:INFO:rekall.1:Loaded profile pe from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.00912809371948 sec)", 
        "2016-05-17 11:10:07,038:DEBUG:rekall.1:Trying method pe, offset 0", 
        "2016-05-17 11:10:07,045:INFO:rekall.1:Detection method pe yielded profile <AMD64 profile pe (PEProfile)>"
    ], 
    "time_used": 3.155700922012329, 
    "return_code": 0, 
    "output": [
        "Address             ||     Rel      ||      Op Codes      ||              Instruction               ||Comment", 
        "--------------------||--------------||--------------------||----------------------------------------||-------", 
        "------ PAGE!MmGetPhysicalMemoryRanges ------", 
        " ||   0x14047a660    ||           0x0||488bc4              ||mov rax, rsp                            ||       ", 
        " ||   0x14047a663    ||           0x3||48895808            ||mov qword ptr [rax + 8], rbx            ||       ", 
        " ||   0x14047a667    ||           0x7||48896810            ||mov qword ptr [rax + 0x10], rbp         ||       ", 
        " ||   0x14047a66b    ||           0xb||48897018            ||mov qword ptr [rax + 0x18], rsi         ||       ", 
        " ||   0x14047a66f    ||           0xf||48897820            ||mov qword ptr [rax + 0x20], rdi         ||       ", 
        " ||   0x14047a673    ||          0x13||4154                ||push r12                                ||       ", 
        " ||   0x14047a675    ||          0x15||4155                ||push r13                                ||       ", 
        " ||   0x14047a677    ||          0x17||4157                ||push r15                                ||       ", 
        " ||   0x14047a679    ||          0x19||4883ec20            ||sub rsp, 0x20                           ||       ", 
        " ||   0x14047a67d    ||          0x1d||65488b1c2588010000  ||mov rbx, qword ptr gs:[0x188]           ||0x0    ", 
        " ||   0x14047a686    ||          0x26||41bf11000000        ||mov r15d, 0x11                          ||       ", 
        " ||   0x14047a68c    ||          0x2c||4533e4              ||xor r12d, r12d                          ||       ", 
        " ||   0x14047a68f    ||          0x2f||f6835104000020      ||test byte ptr [rbx + 0x451], 0x20       ||       ", 
        " ||   0x14047a696    ||          0x36||458d6ff0            ||lea r13d, dword ptr [r15 - 0x10]        ||       ", 
        " ||   0x14047a69a    ||          0x3a||7405                ||je 0x14047a6a1                          ||PAGE!MmGetPhysicalMemoryRanges+0x41", 
        " ||   0x14047a69c    ||          0x3c||418bfc              ||mov edi, r12d                           ||       ", 
        " ||   0x14047a69f    ||          0x3f||eb2a                ||jmp 0x14047a6cb                         ||PAGE!MmGetPhysicalMemoryRanges+0x6b", 
        " ||   0x14047a6a1    ||          0x41||66ff8bc6010000      ||dec word ptr [rbx + 0x1c6]              ||       ", 
        " ||   0x14047a6a8    ||          0x48||33c0                ||xor eax, eax                            ||       ", 
        " ||   0x14047a6aa    ||          0x4a||f04c0fb13d15bddcff  ||lock cmpxchg qword ptr [rip - 0x2342eb],||0x0    ", 
        " ||                  ||              ||                    ||r15                                     ||       ", 
        " ||   0x14047a6b3    ||          0x53||740c                ||je 0x14047a6c1                          ||PAGE!MmGetPhysicalMemoryRanges+0x61"
    ], 
    "options": {
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/pe/ntoskrnl.exe", 
        "func": "pe!MmGetPhysicalMemoryRanges", 
        "--format": "test", 
        "commandline": "dis --length %(length)s %(func)s --name_resolution_strategies Export", 
        "enabled": [
            "TestPEInfo", 
            "TestPEAddressResolver", 
            "TestDisassemble"
        ], 
        "length": 20, 
        "test_class": "TestDisassemble", 
        "--cache_dir": "/home/scudette/projects/rekall-test/pe/../profile_cache/", 
        "tempdir": "/tmp/tmp0E_vwI/TestDisassembleThread-1", 
        "executed_command": "rekall  -v --cache_dir '/home/scudette/projects/rekall-test/pe/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/pe/ntoskrnl.exe' - dis --length 20 pe!MmGetPhysicalMemoryRanges --name_resolution_strategies Export", 
        "testdir": "/home/scudette/projects/rekall-test/pe"
    }
}