#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/android/output/TestSimpleYaraScan /home/scudette/projects/rekall-test/android/TestSimpleYaraScan
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/android/output/TestSimpleYaraScan /home/scudette/projects/rekall-test/android/TestSimpleYaraScan
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/android/output/TestSimpleYaraScan /home/scudette/projects/rekall-test/android/TestSimpleYaraScan
elif [ "$1" == "run" ]; then
   rekall  -v --profile '/home/scudette/projects/rekall-test/android/Evo4G.json' --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/android/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/android/Evo4GRodeo.aff4' --name_resolution_strategies 'Module' 'Symbol' - simple_yarascan
else
   less /home/scudette/projects/rekall-test/android/output/TestSimpleYaraScan
fi
exit 0
{
    "failours": {
        "testCase (__main__.TestSimpleYaraScan)": {}
    }, 
    "errors": {
        "testCase (__main__.TestSimpleYaraScan)": {}
    }, 
    "logging": [
        "2016-05-02 16:36:52,622:DEBUG:rekall.1:Logging level set to 10", 
        "2016-05-02 16:36:52,622:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/android/Evo4G.json", 
        "2016-05-02 16:36:52,817:DEBUG:rekall.1:Running plugin (simple_yarascan) with args (()) kwargs ({'profile': '/home/scudette/projects/rekall-test/android/Evo4G.json', 'hits': 10, 'pre_context': 0, 'string': None, 'binary_string': None, 'yara_expression': None, 'yara_file': None, 'start': 0, 'limit': 18446744073709551616L, 'context': 64})", 
        "2016-05-02 16:36:52,818:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/android/Evo4G.json", 
        "2016-05-02 16:36:52,978:DEBUG:rekall.1:Voting round with base: None", 
        "2016-05-02 16:36:52,979:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-05-02 16:36:52,979:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided", 
        "2016-05-02 16:36:52,979:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-05-02 16:36:52,979:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space", 
        "2016-05-02 16:36:52,979:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-05-02 16:36:52,979:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided", 
        "2016-05-02 16:36:52,979:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-05-02 16:36:52,979:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided", 
        "2016-05-02 16:36:52,979:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-05-02 16:36:52,980:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space", 
        "2016-05-02 16:36:52,980:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-05-02 16:36:52,980:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space", 
        "2016-05-02 16:36:52,980:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-05-02 16:36:52,980:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided", 
        "2016-05-02 16:36:52,980:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-05-02 16:36:52,980:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided", 
        "2016-05-02 16:36:52,980:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-05-02 16:36:52,980:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space", 
        "2016-05-02 16:36:52,980:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-05-02 16:36:52,980:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.", 
        "2016-05-02 16:36:52,980:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-05-02 16:36:52,987:INFO:rekall.1:Added aff4://ad86fa73-d406-4014-9d30-257814b88af3/home/scudette/images/android/Evo4GRodeo.lime as physical memory", 
        "2016-05-02 16:36:52,987:DEBUG:rekall.1:Succeeded instantiating AFF4AddressSpace", 
        "2016-05-02 16:36:52,987:DEBUG:rekall.1:Voting round with base: AFF4AddressSpace", 
        "2016-05-02 16:36:52,988:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-05-02 16:36:52,990:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x4c694d45", 
        "2016-05-02 16:36:52,990:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-05-02 16:36:52,990:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-05-02 16:36:52,990:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-05-02 16:36:52,990:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-05-02 16:36:52,990:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-05-02 16:36:52,990:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "2016-05-02 16:36:52,990:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-05-02 16:36:52,990:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "2016-05-02 16:36:52,990:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-05-02 16:36:52,990:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "2016-05-02 16:36:52,990:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-05-02 16:36:52,991:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "2016-05-02 16:36:52,991:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-05-02 16:36:52,991:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "2016-05-02 16:36:52,991:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-05-02 16:36:52,991:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "2016-05-02 16:36:52,991:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-05-02 16:36:52,995:DEBUG:rekall.1:Succeeded instantiating LimeAddressSpace", 
        "2016-05-02 16:36:52,995:DEBUG:rekall.1:Voting round with base: LimeAddressSpace", 
        "2016-05-02 16:36:52,995:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-05-02 16:36:52,996:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0", 
        "2016-05-02 16:36:52,996:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-05-02 16:36:52,996:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-05-02 16:36:52,996:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-05-02 16:36:52,996:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-05-02 16:36:52,996:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-05-02 16:36:52,996:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "2016-05-02 16:36:52,996:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-05-02 16:36:52,996:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "2016-05-02 16:36:52,996:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-05-02 16:36:52,996:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "2016-05-02 16:36:52,996:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-05-02 16:36:52,997:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "2016-05-02 16:36:52,997:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-05-02 16:36:52,997:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "2016-05-02 16:36:52,997:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-05-02 16:36:52,997:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "2016-05-02 16:36:52,997:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-05-02 16:36:52,997:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature", 
        "2016-05-02 16:36:52,997:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-05-02 16:36:52,997:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space", 
        "2016-05-02 16:36:52,997:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-05-02 16:36:52,997:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.", 
        "2016-05-02 16:36:52,998:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-05-02 16:36:52,998:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space", 
        "2016-05-02 16:36:52,998:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> ", 
        "2016-05-02 16:36:52,998:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space", 
        "2016-05-02 16:36:52,998:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> ", 
        "2016-05-02 16:36:52,998:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified", 
        "2016-05-02 16:36:52,998:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> ", 
        "2016-05-02 16:36:52,998:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.", 
        "2016-05-02 16:36:52,999:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> ", 
        "2016-05-02 16:36:52,999:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified", 
        "2016-05-02 16:36:52,999:INFO:rekall.1:Autodetected physical address space LimeAddressSpace", 
        "2016-05-02 16:36:52,999:CRITICAL:rekall.1:You must specify a yara rule file or string to match."
    ], 
    "time_used": 1.330155849456787, 
    "return_code": 0, 
    "output": [], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/android/Evo4GRodeo.aff4", 
        "--format": "test", 
        "commandline": "simple_yarascan", 
        "proc_name": "sh", 
        "pid": 1872, 
        "tempdir": "/tmp/tmp0s7tvh/TestSimpleYaraScanThread-1", 
        "test_class": "TestSimpleYaraScan", 
        "--cache_dir": "/home/scudette/projects/rekall-test/android/../profile_cache/", 
        "--cache": "memory", 
        "--profile": "/home/scudette/projects/rekall-test/android/Evo4G.json", 
        "executed_command": "rekall  -v --profile '/home/scudette/projects/rekall-test/android/Evo4G.json' --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/android/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/android/Evo4GRodeo.aff4' --name_resolution_strategies 'Module' 'Symbol' - simple_yarascan", 
        "testdir": "/home/scudette/projects/rekall-test/android"
    }
}