#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/android/output/TestCheckModules /home/scudette/projects/rekall-test/android/TestCheckModules
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/android/output/TestCheckModules /home/scudette/projects/rekall-test/android/TestCheckModules
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/android/output/TestCheckModules /home/scudette/projects/rekall-test/android/TestCheckModules
elif [ "$1" == "run" ]; then
   rekall  -v --profile '/home/scudette/projects/rekall-test/android/Evo4G.json' --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/android/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/android/Evo4GRodeo.aff4' --name_resolution_strategies 'Module' 'Symbol' - check_modules
else
   less /home/scudette/projects/rekall-test/android/output/TestCheckModules
fi
exit 0
{
    "failours": {
        "testCase (__main__.TestCheckModules)": {
            "testCase (__main__.TestCheckModules)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 300, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 350, in testCase\n    self.assertListEqual(previous, current)\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 275, in assertListEqual\n    self.assertEqual(x, y)\nAssertionError: u'    Module    ||         Module Name          ||Ref Count ||Known' != u'    0xbf02d4c4||bcm4329                       ||    3     ||True '\n-     Module    ||         Module Name          ||Ref Count ||Known\n+     0xbf02d4c4||bcm4329                       ||    3     ||True \n\n"
        }
    }, 
    "errors": {
        "testCase (__main__.TestCheckModules)": {}
    }, 
    "logging": [
        "2016-06-21 18:07:35,592:DEBUG:rekall.1:Logging level set to 10", 
        "2016-06-21 18:07:35,592:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/android/Evo4G.json", 
        "2016-06-21 18:07:36,224:DEBUG:rekall.1:Voting round with base: None", 
        "2016-06-21 18:07:36,224:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-06-21 18:07:36,224:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided", 
        "2016-06-21 18:07:36,225:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-06-21 18:07:36,225:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space", 
        "2016-06-21 18:07:36,225:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-06-21 18:07:36,225:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided", 
        "2016-06-21 18:07:36,225:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-06-21 18:07:36,227:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided", 
        "2016-06-21 18:07:36,227:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-06-21 18:07:36,228:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space", 
        "2016-06-21 18:07:36,228:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-06-21 18:07:36,228:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space", 
        "2016-06-21 18:07:36,228:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-06-21 18:07:36,228:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided", 
        "2016-06-21 18:07:36,228:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-06-21 18:07:36,231:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided", 
        "2016-06-21 18:07:36,231:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-06-21 18:07:36,231:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space", 
        "2016-06-21 18:07:36,231:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-06-21 18:07:36,232:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.", 
        "2016-06-21 18:07:36,232:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-06-21 18:07:36,259:INFO:rekall.1:Added aff4://ad86fa73-d406-4014-9d30-257814b88af3/home/scudette/images/android/Evo4GRodeo.lime as physical memory", 
        "2016-06-21 18:07:36,260:DEBUG:rekall.1:Succeeded instantiating AFF4AddressSpace", 
        "2016-06-21 18:07:36,261:DEBUG:rekall.1:Voting round with base: AFF4AddressSpace", 
        "2016-06-21 18:07:36,261:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-06-21 18:07:36,270:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x4c694d45", 
        "2016-06-21 18:07:36,270:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-06-21 18:07:36,270:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-06-21 18:07:36,270:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-06-21 18:07:36,275:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-06-21 18:07:36,275:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-06-21 18:07:36,276:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "2016-06-21 18:07:36,276:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-06-21 18:07:36,276:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "2016-06-21 18:07:36,276:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-06-21 18:07:36,276:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "2016-06-21 18:07:36,277:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-06-21 18:07:36,277:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "2016-06-21 18:07:36,277:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-06-21 18:07:36,277:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "2016-06-21 18:07:36,277:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-06-21 18:07:36,277:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "2016-06-21 18:07:36,278:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-06-21 18:07:36,291:DEBUG:rekall.1:Succeeded instantiating LimeAddressSpace", 
        "2016-06-21 18:07:36,298:DEBUG:rekall.1:Voting round with base: LimeAddressSpace", 
        "2016-06-21 18:07:36,298:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-06-21 18:07:36,300:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0", 
        "2016-06-21 18:07:36,301:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-06-21 18:07:36,301:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-06-21 18:07:36,301:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-06-21 18:07:36,301:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-06-21 18:07:36,301:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-06-21 18:07:36,302:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "2016-06-21 18:07:36,302:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-06-21 18:07:36,302:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "2016-06-21 18:07:36,302:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-06-21 18:07:36,303:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "2016-06-21 18:07:36,303:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-06-21 18:07:36,303:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "2016-06-21 18:07:36,303:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-06-21 18:07:36,303:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "2016-06-21 18:07:36,303:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-06-21 18:07:36,304:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "2016-06-21 18:07:36,304:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-06-21 18:07:36,304:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature", 
        "2016-06-21 18:07:36,304:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-06-21 18:07:36,305:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space", 
        "2016-06-21 18:07:36,305:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-06-21 18:07:36,305:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.", 
        "2016-06-21 18:07:36,305:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-06-21 18:07:36,305:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space", 
        "2016-06-21 18:07:36,305:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> ", 
        "2016-06-21 18:07:36,305:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space", 
        "2016-06-21 18:07:36,306:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> ", 
        "2016-06-21 18:07:36,309:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified", 
        "2016-06-21 18:07:36,309:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> ", 
        "2016-06-21 18:07:36,310:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.", 
        "2016-06-21 18:07:36,310:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> ", 
        "2016-06-21 18:07:36,310:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified", 
        "2016-06-21 18:07:36,310:INFO:rekall.1:Autodetected physical address space LimeAddressSpace", 
        "2016-06-21 18:07:36,310:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/android/Evo4G.json", 
        "2016-06-21 18:07:36,738:DEBUG:rekall.1:Running plugin (check_modules) with args (()) kwargs ({'profile': '/home/scudette/projects/rekall-test/android/Evo4G.json'})", 
        "2016-06-21 18:07:36,739:DEBUG:rekall.1:DTB not specified. Delegating to find_dtb.", 
        "2016-06-21 18:07:36,739:DEBUG:rekall.1:Calculating page offset...", 
        "2016-06-21 18:07:36,739:DEBUG:rekall.1:Detected ARM Linux."
    ], 
    "time_used": 4.380204916000366, 
    "return_code": 0, 
    "output": [
        "    Module    ||         Module Name          ||Ref Count ||Known", 
        "--------------||------------------------------||----------||-----", 
        "    0xbf02d4c4||bcm4329                       ||    3     ||True ", 
        "    0xbf03a910||lime                          ||    3     ||True "
    ], 
    "executed_command": "rekall  -v --profile '/home/scudette/projects/rekall-test/android/Evo4G.json' --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/android/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/android/Evo4GRodeo.aff4' --name_resolution_strategies 'Module' 'Symbol' - check_modules", 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/android/Evo4GRodeo.aff4", 
        "--format": "test", 
        "commandline": "check_modules", 
        "proc_name": "sh", 
        "--profile": "/home/scudette/projects/rekall-test/android/Evo4G.json", 
        "test_class": "TestCheckModules", 
        "tempdir": "/tmp/tmp1kmu4S/TestCheckModulesThread-2", 
        "--cache_dir": "/home/scudette/projects/rekall-test/android/../profile_cache/", 
        "--cache": "memory", 
        "debug": false, 
        "pids": 1872, 
        "testdir": "/home/scudette/projects/rekall-test/android"
    }
}