#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/android/output/TestDescribe /home/scudette/projects/rekall-test/android/TestDescribe
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/android/output/TestDescribe /home/scudette/projects/rekall-test/android/TestDescribe
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/android/output/TestDescribe /home/scudette/projects/rekall-test/android/TestDescribe
elif [ "$1" == "run" ]; then
   rekall  -v --profile '/home/scudette/projects/rekall-test/android/Evo4G.json' --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/android/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/android/Evo4GRodeo.aff4' --name_resolution_strategies 'Module' 'Symbol' - describe pslist
else
   less /home/scudette/projects/rekall-test/android/output/TestDescribe
fi
exit 0
{
    "failours": {
        "testCase (rekall.plugins.common.efilter_plugins.info.TestDescribe)": {
            "testCase (rekall.plugins.common.efilter_plugins.info.TestDescribe)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 300, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 354, in testCase\n    self.assertListEqual(previous, current)\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 275, in assertListEqual\n    self.assertEqual(x, y)\nAssertionError: u' ||binary                                          ||NoneType' != u' ||binary                                          ||str '\n-  ||binary                                          ||NoneType\n?                                                      ^^^^^^^^\n+  ||binary                                          ||str \n?                                                      ^^^^\n\n"
        }
    }, 
    "errors": {
        "testCase (rekall.plugins.common.efilter_plugins.info.TestDescribe)": {}
    }, 
    "logging": [
        "2016-10-20 11:20:54,170:DEBUG:rekall.1:Logging level set to 10", 
        "2016-10-20 11:20:54,171:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/android/Evo4G.json", 
        "2016-10-20 11:20:54,623:DEBUG:rekall.1:Running plugin (describe) with args (()) kwargs ({'profile': '/home/scudette/projects/rekall-test/android/Evo4G.json', 'verbosity': 1, 'max_depth': 0, 'plugin_name': 'pslist'})", 
        "2016-10-20 11:20:54,623:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/android/Evo4G.json", 
        "2016-10-20 11:20:55,210:DEBUG:rekall.1:Voting round with base: None", 
        "2016-10-20 11:20:55,210:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> ", 
        "2016-10-20 11:20:55,210:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason", 
        "2016-10-20 11:20:55,210:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-10-20 11:20:55,210:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided", 
        "2016-10-20 11:20:55,211:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-10-20 11:20:55,211:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space", 
        "2016-10-20 11:20:55,211:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-10-20 11:20:55,211:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided", 
        "2016-10-20 11:20:55,211:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-10-20 11:20:55,213:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided", 
        "2016-10-20 11:20:55,213:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-10-20 11:20:55,213:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space", 
        "2016-10-20 11:20:55,213:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-10-20 11:20:55,213:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space", 
        "2016-10-20 11:20:55,213:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-10-20 11:20:55,214:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided", 
        "2016-10-20 11:20:55,214:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-10-20 11:20:55,214:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided", 
        "2016-10-20 11:20:55,214:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-10-20 11:20:55,214:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space", 
        "2016-10-20 11:20:55,214:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-10-20 11:20:55,215:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.", 
        "2016-10-20 11:20:55,215:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-10-20 11:20:55,224:INFO:rekall.1:Added aff4://ad86fa73-d406-4014-9d30-257814b88af3/home/scudette/images/android/Evo4GRodeo.lime as physical memory", 
        "2016-10-20 11:20:55,225:DEBUG:rekall.1:Succeeded instantiating AFF4AddressSpace", 
        "2016-10-20 11:20:55,226:DEBUG:rekall.1:Voting round with base: AFF4AddressSpace", 
        "2016-10-20 11:20:55,226:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> ", 
        "2016-10-20 11:20:55,226:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason", 
        "2016-10-20 11:20:55,226:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-10-20 11:20:55,229:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x4c694d45", 
        "2016-10-20 11:20:55,229:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-10-20 11:20:55,229:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-10-20 11:20:55,230:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-10-20 11:20:55,230:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-10-20 11:20:55,230:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-10-20 11:20:55,230:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "2016-10-20 11:20:55,230:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-10-20 11:20:55,230:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "2016-10-20 11:20:55,231:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-10-20 11:20:55,231:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "2016-10-20 11:20:55,231:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-10-20 11:20:55,231:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "2016-10-20 11:20:55,231:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-10-20 11:20:55,231:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "2016-10-20 11:20:55,231:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-10-20 11:20:55,231:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "2016-10-20 11:20:55,232:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-10-20 11:20:55,237:DEBUG:rekall.1:Succeeded instantiating LimeAddressSpace", 
        "2016-10-20 11:20:55,237:DEBUG:rekall.1:Voting round with base: LimeAddressSpace", 
        "2016-10-20 11:20:55,238:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> ", 
        "2016-10-20 11:20:55,238:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason", 
        "2016-10-20 11:20:55,238:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-10-20 11:20:55,239:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0", 
        "2016-10-20 11:20:55,239:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-10-20 11:20:55,241:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-10-20 11:20:55,241:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-10-20 11:20:55,241:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-10-20 11:20:55,241:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-10-20 11:20:55,242:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "2016-10-20 11:20:55,242:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-10-20 11:20:55,242:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "2016-10-20 11:20:55,242:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-10-20 11:20:55,242:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "2016-10-20 11:20:55,242:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-10-20 11:20:55,242:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "2016-10-20 11:20:55,243:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-10-20 11:20:55,243:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "2016-10-20 11:20:55,243:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-10-20 11:20:55,243:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "2016-10-20 11:20:55,243:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-10-20 11:20:55,243:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature", 
        "2016-10-20 11:20:55,245:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-10-20 11:20:55,246:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space", 
        "2016-10-20 11:20:55,246:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-10-20 11:20:55,246:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.", 
        "2016-10-20 11:20:55,246:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-10-20 11:20:55,246:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space", 
        "2016-10-20 11:20:55,247:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> ", 
        "2016-10-20 11:20:55,247:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space", 
        "2016-10-20 11:20:55,247:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> ", 
        "2016-10-20 11:20:55,248:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified", 
        "2016-10-20 11:20:55,248:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> ", 
        "2016-10-20 11:20:55,248:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.", 
        "2016-10-20 11:20:55,249:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> ", 
        "2016-10-20 11:20:55,249:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified", 
        "2016-10-20 11:20:55,249:INFO:rekall.1:Autodetected physical address space LimeAddressSpace", 
        "2016-10-20 11:20:55,249:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/android/Evo4G.json", 
        "2016-10-20 11:20:55,741:DEBUG:rekall.1:DTB not specified. Delegating to find_dtb.", 
        "2016-10-20 11:20:55,741:DEBUG:rekall.1:Calculating page offset...", 
        "2016-10-20 11:20:55,741:DEBUG:rekall.1:Detected ARM Linux."
    ], 
    "time_used": 5.319968938827515, 
    "return_code": 0, 
    "output": [
        "                      Field                       ||Type", 
        "--------------------------------------------------||----", 
        " ||proc                                            ||task_struct", 
        " ||ppid                                            ||int ", 
        " ||uid                                             ||HexInteger", 
        " ||gid                                             ||HexInteger", 
        " ||dtb                                             ||HexInteger", 
        " ||start_time                                      ||UnixTimeStamp", 
        " ||binary                                          ||str "
    ], 
    "executed_command": "rekall  -v --profile '/home/scudette/projects/rekall-test/android/Evo4G.json' --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/android/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/android/Evo4GRodeo.aff4' --name_resolution_strategies 'Module' 'Symbol' - describe pslist", 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/android/Evo4GRodeo.aff4", 
        "--format": "test", 
        "commandline": "describe pslist", 
        "proc_name": "sh", 
        "--profile": "/home/scudette/projects/rekall-test/android/Evo4G.json", 
        "test_class": "TestDescribe", 
        "tempdir": "/tmp/tmpSutmp0/TestDescribeThread-4", 
        "--cache_dir": "/home/scudette/projects/rekall-test/android/../profile_cache/", 
        "--cache": "memory", 
        "debug": false, 
        "pids": 1872, 
        "testdir": "/home/scudette/projects/rekall-test/android"
    }
}