#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/android/output/TestArp /home/scudette/projects/rekall-test/android/TestArp
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/android/output/TestArp /home/scudette/projects/rekall-test/android/TestArp
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/android/output/TestArp /home/scudette/projects/rekall-test/android/TestArp
elif [ "$1" == "run" ]; then
   rekall  -v --profile '/home/scudette/projects/rekall-test/android/Evo4G.json' --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/android/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/android/Evo4GRodeo.aff4' --name_resolution_strategies 'Module' 'Symbol' - arp
else
   less /home/scudette/projects/rekall-test/android/output/TestArp
fi
exit 0
{
    "failours": {
        "testCase (__main__.TestArp)": {
            "testCase (__main__.TestArp)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 300, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 354, in testCase\n    self.assertListEqual(previous, current)\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 275, in assertListEqual\n    self.assertEqual(x, y)\nAssertionError: u'                                           ::||   00:00:00:00:00:00||          [truncated]... != u'                                           ip||                 mac||          [truncated]...\n-                                            ::||   00:00:00:00:00:00||             lo\n+                                            ip||                 mac||            dev\n\n"
        }
    }, 
    "errors": {
        "testCase (__main__.TestArp)": {}
    }, 
    "logging": [
        "2016-10-20 11:21:18,768:DEBUG:rekall.1:Logging level set to 10", 
        "2016-10-20 11:21:18,769:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/android/Evo4G.json", 
        "2016-10-20 11:21:19,302:DEBUG:rekall.1:Voting round with base: None", 
        "2016-10-20 11:21:19,303:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> ", 
        "2016-10-20 11:21:19,303:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason", 
        "2016-10-20 11:21:19,303:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-10-20 11:21:19,303:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided", 
        "2016-10-20 11:21:19,304:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-10-20 11:21:19,304:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space", 
        "2016-10-20 11:21:19,304:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-10-20 11:21:19,304:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided", 
        "2016-10-20 11:21:19,304:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-10-20 11:21:19,305:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided", 
        "2016-10-20 11:21:19,306:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-10-20 11:21:19,306:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space", 
        "2016-10-20 11:21:19,306:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-10-20 11:21:19,306:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space", 
        "2016-10-20 11:21:19,306:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-10-20 11:21:19,306:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided", 
        "2016-10-20 11:21:19,307:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-10-20 11:21:19,307:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided", 
        "2016-10-20 11:21:19,307:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-10-20 11:21:19,307:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space", 
        "2016-10-20 11:21:19,307:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-10-20 11:21:19,307:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.", 
        "2016-10-20 11:21:19,308:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-10-20 11:21:19,338:INFO:rekall.1:Added aff4://ad86fa73-d406-4014-9d30-257814b88af3/home/scudette/images/android/Evo4GRodeo.lime as physical memory", 
        "2016-10-20 11:21:19,339:DEBUG:rekall.1:Succeeded instantiating AFF4AddressSpace", 
        "2016-10-20 11:21:19,339:DEBUG:rekall.1:Voting round with base: AFF4AddressSpace", 
        "2016-10-20 11:21:19,339:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> ", 
        "2016-10-20 11:21:19,339:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason", 
        "2016-10-20 11:21:19,340:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-10-20 11:21:19,346:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x4c694d45", 
        "2016-10-20 11:21:19,347:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-10-20 11:21:19,348:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-10-20 11:21:19,348:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-10-20 11:21:19,348:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-10-20 11:21:19,348:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-10-20 11:21:19,348:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "2016-10-20 11:21:19,348:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-10-20 11:21:19,352:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "2016-10-20 11:21:19,352:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-10-20 11:21:19,352:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "2016-10-20 11:21:19,352:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-10-20 11:21:19,352:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "2016-10-20 11:21:19,352:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-10-20 11:21:19,353:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "2016-10-20 11:21:19,353:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-10-20 11:21:19,353:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "2016-10-20 11:21:19,353:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-10-20 11:21:19,374:DEBUG:rekall.1:Succeeded instantiating LimeAddressSpace", 
        "2016-10-20 11:21:19,375:DEBUG:rekall.1:Voting round with base: LimeAddressSpace", 
        "2016-10-20 11:21:19,375:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> ", 
        "2016-10-20 11:21:19,375:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason", 
        "2016-10-20 11:21:19,375:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-10-20 11:21:19,377:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0", 
        "2016-10-20 11:21:19,377:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-10-20 11:21:19,377:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-10-20 11:21:19,377:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-10-20 11:21:19,377:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-10-20 11:21:19,378:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-10-20 11:21:19,382:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "2016-10-20 11:21:19,382:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-10-20 11:21:19,383:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "2016-10-20 11:21:19,383:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-10-20 11:21:19,383:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "2016-10-20 11:21:19,383:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-10-20 11:21:19,384:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "2016-10-20 11:21:19,384:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-10-20 11:21:19,385:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "2016-10-20 11:21:19,385:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-10-20 11:21:19,385:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "2016-10-20 11:21:19,386:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-10-20 11:21:19,390:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature", 
        "2016-10-20 11:21:19,391:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-10-20 11:21:19,391:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space", 
        "2016-10-20 11:21:19,391:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-10-20 11:21:19,391:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.", 
        "2016-10-20 11:21:19,391:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-10-20 11:21:19,391:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space", 
        "2016-10-20 11:21:19,392:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> ", 
        "2016-10-20 11:21:19,392:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space", 
        "2016-10-20 11:21:19,392:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> ", 
        "2016-10-20 11:21:19,393:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified", 
        "2016-10-20 11:21:19,393:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> ", 
        "2016-10-20 11:21:19,393:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.", 
        "2016-10-20 11:21:19,393:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> ", 
        "2016-10-20 11:21:19,393:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified", 
        "2016-10-20 11:21:19,394:INFO:rekall.1:Autodetected physical address space LimeAddressSpace", 
        "2016-10-20 11:21:19,397:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/android/Evo4G.json", 
        "2016-10-20 11:21:20,192:DEBUG:rekall.1:Running plugin (arp) with args (()) kwargs ({'profile': '/home/scudette/projects/rekall-test/android/Evo4G.json', 'verbosity': 1})", 
        "2016-10-20 11:21:20,193:DEBUG:rekall.1:DTB not specified. Delegating to find_dtb.", 
        "2016-10-20 11:21:20,194:DEBUG:rekall.1:Calculating page offset...", 
        "2016-10-20 11:21:20,194:DEBUG:rekall.1:Detected ARM Linux."
    ], 
    "time_used": 4.676005840301514, 
    "return_code": 0, 
    "output": [
        "                     ip                      ||        mac         ||      dev      ", 
        "---------------------------------------------||--------------------||---------------", 
        "                                           ip||                 mac||            dev", 
        "                                           ip||                 mac||            dev"
    ], 
    "executed_command": "rekall  -v --profile '/home/scudette/projects/rekall-test/android/Evo4G.json' --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/android/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/android/Evo4GRodeo.aff4' --name_resolution_strategies 'Module' 'Symbol' - arp", 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/android/Evo4GRodeo.aff4", 
        "--format": "test", 
        "commandline": "arp", 
        "proc_name": "sh", 
        "--profile": "/home/scudette/projects/rekall-test/android/Evo4G.json", 
        "test_class": "TestArp", 
        "tempdir": "/tmp/tmpSutmp0/TestArpThread-1", 
        "--cache_dir": "/home/scudette/projects/rekall-test/android/../profile_cache/", 
        "--cache": "memory", 
        "debug": false, 
        "pids": 1872, 
        "testdir": "/home/scudette/projects/rekall-test/android"
    }
}