#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/android/output/TestLinMemDump /home/scudette/projects/rekall-test/android/TestLinMemDump
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/android/output/TestLinMemDump /home/scudette/projects/rekall-test/android/TestLinMemDump
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/android/output/TestLinMemDump /home/scudette/projects/rekall-test/android/TestLinMemDump
elif [ "$1" == "run" ]; then
   rekall  -v --profile '/home/scudette/projects/rekall-test/android/Evo4G.json' --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/android/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/android/Evo4GRodeo.aff4' --name_resolution_strategies 'Module' 'Symbol' - memdump --proc_regex sh --dump_dir /tmp/tmpLBwFS0/TestLinMemDumpThread-3
else
   less /home/scudette/projects/rekall-test/android/output/TestLinMemDump
fi
exit 0
{
    "failours": {
        "testCase (rekall.plugins.linux.pslist.TestLinMemDump)": {
            "testCase (rekall.plugins.linux.pslist.TestLinMemDump)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 252, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 360, in testCase\n    self.assertEqual(self.baseline['hashes'], self.current['hashes'])\nAssertionError: {u'sh_1872.dmp': u'f217b91a807ce0c82e628bd878395e1b', u'sh_1872.dmp.idx': u'ed8b [truncated]... != {'sh_1872.dmp': 'f217b91a807ce0c82e628bd878395e1b', 'sh_1872.dmp.idx': 'dcdec5ac [truncated]...\n- {u'sh_1872.dmp': u'f217b91a807ce0c82e628bd878395e1b',\n?  -               -\n\n+ {'sh_1872.dmp': 'f217b91a807ce0c82e628bd878395e1b',\n-  u'sh_1872.dmp.idx': u'ed8b615e40b029ecb50c1b0c44484e2c'}\n+  'sh_1872.dmp.idx': 'dcdec5accac385985fa427609f3a91f9'}\n"
        }
    }, 
    "errors": {
        "testCase (rekall.plugins.linux.pslist.TestLinMemDump)": {}
    }, 
    "logging": [
        "2016-03-28 09:53:39,763:DEBUG:rekall.1:Logging level set to 10", 
        "2016-03-28 09:53:39,763:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/android/Evo4G.json", 
        "2016-03-28 09:53:40,202:DEBUG:rekall.1:Voting round with base: None", 
        "2016-03-28 09:53:40,203:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-03-28 09:53:40,203:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided", 
        "2016-03-28 09:53:40,203:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-03-28 09:53:40,203:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space", 
        "2016-03-28 09:53:40,203:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-03-28 09:53:40,203:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided", 
        "2016-03-28 09:53:40,204:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-03-28 09:53:40,204:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided", 
        "2016-03-28 09:53:40,204:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-03-28 09:53:40,204:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space", 
        "2016-03-28 09:53:40,205:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-03-28 09:53:40,205:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space", 
        "2016-03-28 09:53:40,205:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-03-28 09:53:40,205:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided", 
        "2016-03-28 09:53:40,205:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-03-28 09:53:40,205:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided", 
        "2016-03-28 09:53:40,205:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-03-28 09:53:40,206:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space", 
        "2016-03-28 09:53:40,206:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-03-28 09:53:40,206:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.", 
        "2016-03-28 09:53:40,206:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-03-28 09:53:40,220:INFO:rekall.1:Added aff4://ad86fa73-d406-4014-9d30-257814b88af3/home/scudette/images/android/Evo4GRodeo.lime as physical memory", 
        "2016-03-28 09:53:40,222:DEBUG:rekall.1:Succeeded instantiating AFF4AddressSpace", 
        "2016-03-28 09:53:40,222:DEBUG:rekall.1:Voting round with base: AFF4AddressSpace", 
        "2016-03-28 09:53:40,222:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-03-28 09:53:40,225:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x4c694d45", 
        "2016-03-28 09:53:40,226:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-03-28 09:53:40,226:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-03-28 09:53:40,226:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-03-28 09:53:40,226:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-03-28 09:53:40,226:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-03-28 09:53:40,226:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "2016-03-28 09:53:40,227:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-03-28 09:53:40,227:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "2016-03-28 09:53:40,227:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-03-28 09:53:40,227:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "2016-03-28 09:53:40,227:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-03-28 09:53:40,227:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "2016-03-28 09:53:40,227:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-03-28 09:53:40,228:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "2016-03-28 09:53:40,228:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-03-28 09:53:40,228:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "2016-03-28 09:53:40,228:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-03-28 09:53:40,236:DEBUG:rekall.1:Succeeded instantiating LimeAddressSpace", 
        "2016-03-28 09:53:40,237:DEBUG:rekall.1:Voting round with base: LimeAddressSpace", 
        "2016-03-28 09:53:40,237:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-03-28 09:53:40,238:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0", 
        "2016-03-28 09:53:40,239:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-03-28 09:53:40,239:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-03-28 09:53:40,239:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-03-28 09:53:40,239:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-03-28 09:53:40,239:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-03-28 09:53:40,239:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "2016-03-28 09:53:40,240:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-03-28 09:53:40,240:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "2016-03-28 09:53:40,240:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-03-28 09:53:40,240:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "2016-03-28 09:53:40,240:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-03-28 09:53:40,240:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "2016-03-28 09:53:40,241:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-03-28 09:53:40,241:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "2016-03-28 09:53:40,241:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-03-28 09:53:40,241:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "2016-03-28 09:53:40,241:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-03-28 09:53:40,241:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature", 
        "2016-03-28 09:53:40,242:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-03-28 09:53:40,242:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space", 
        "2016-03-28 09:53:40,242:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-03-28 09:53:40,242:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.", 
        "2016-03-28 09:53:40,242:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-03-28 09:53:40,242:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space", 
        "2016-03-28 09:53:40,243:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> ", 
        "2016-03-28 09:53:40,243:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space", 
        "2016-03-28 09:53:40,243:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> ", 
        "2016-03-28 09:53:40,244:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified", 
        "2016-03-28 09:53:40,244:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> ", 
        "2016-03-28 09:53:40,244:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.", 
        "2016-03-28 09:53:40,244:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> ", 
        "2016-03-28 09:53:40,244:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified", 
        "2016-03-28 09:53:40,244:INFO:rekall.1:Autodetected physical address space LimeAddressSpace", 
        "2016-03-28 09:53:40,245:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/android/Evo4G.json", 
        "2016-03-28 09:53:40,661:DEBUG:rekall.1:Running plugin (memdump) with args (()) kwargs ({'profile': '/home/scudette/projects/rekall-test/android/Evo4G.json', 'all': False, 'task': None, 'task_head': None, 'pid': None, 'proc_regex': 'sh', 'coalesce': False, 'phys_task': None, 'dump_dir': '/tmp/tmpLBwFS0/TestLinMemDumpThread-3', 'method': ['InitTask']})", 
        "2016-03-28 09:53:40,663:DEBUG:rekall.1:DTB not specified. Delegating to find_dtb.", 
        "2016-03-28 09:53:40,663:DEBUG:rekall.1:Calculating page offset...", 
        "2016-03-28 09:53:40,663:DEBUG:rekall.1:Detected ARM Linux.", 
        "2016-03-28 09:53:40,827:DEBUG:rekall.1:Listed 127 processes using InitTask"
    ], 
    "time_used": 5.271476984024048, 
    "return_code": 0, 
    "output": [
        "**************************************************", 
        "Writing     0xd367c400||sh||  1872 to sh_1872.dmp"
    ], 
    "hashes": {
        "sh_1872.dmp": "f217b91a807ce0c82e628bd878395e1b", 
        "sh_1872.dmp.idx": "dcdec5accac385985fa427609f3a91f9"
    }, 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/android/Evo4GRodeo.aff4", 
        "--format": "test", 
        "commandline": "memdump --proc_regex %(proc_name)s --dump_dir %(tempdir)s", 
        "proc_name": "sh", 
        "pid": 1872, 
        "tempdir": "/tmp/tmpLBwFS0/TestLinMemDumpThread-3", 
        "test_class": "TestLinMemDump", 
        "--cache_dir": "/home/scudette/projects/rekall-test/android/../profile_cache/", 
        "--cache": "memory", 
        "--profile": "/home/scudette/projects/rekall-test/android/Evo4G.json", 
        "executed_command": "rekall  -v --profile '/home/scudette/projects/rekall-test/android/Evo4G.json' --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/android/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/android/Evo4GRodeo.aff4' --name_resolution_strategies 'Module' 'Symbol' - memdump --proc_regex sh --dump_dir /tmp/tmpLBwFS0/TestLinMemDumpThread-3", 
        "testdir": "/home/scudette/projects/rekall-test/android"
    }
}