#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/osx10.11.3/output/TestWinMemDump /home/scudette/projects/rekall-test/osx10.11.3/TestWinMemDump
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/osx10.11.3/output/TestWinMemDump /home/scudette/projects/rekall-test/osx10.11.3/TestWinMemDump
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/osx10.11.3/output/TestWinMemDump /home/scudette/projects/rekall-test/osx10.11.3/TestWinMemDump
elif [ "$1" == "run" ]; then
   rekall  -v --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/osx10.11.3/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/osx10.11.3/10.11.3.aff4' --name_resolution_strategies 'Module' 'Symbol' - memdump --pid=232 --dump_dir /tmp/tmpDh7Wbv/TestWinMemDumpThread-4
else
   less /home/scudette/projects/rekall-test/osx10.11.3/output/TestWinMemDump
fi
exit 0
{
    "failours": {
        "testCase (rekall.plugins.windows.taskmods.TestWinMemDump)": {
            "testCase (rekall.plugins.windows.taskmods.TestWinMemDump)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 252, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 360, in testCase\n    self.assertEqual(self.baseline['hashes'], self.current['hashes'])\nAssertionError: {u'installd_232.dmp.idx': u'a97ed0b8a96039785f44130a5b631b3c', u'installd_232.dm [truncated]... != {'installd_232.dmp.idx': '8aeff0d56379d4bc1e5780da16fc4af0', 'installd_232.dmp': [truncated]...\n- {u'installd_232.dmp': u'27aef9c398bbd6c08587d1b6661d3529',\n?  -                    -\n\n+ {'installd_232.dmp': '27aef9c398bbd6c08587d1b6661d3529',\n-  u'installd_232.dmp.idx': u'a97ed0b8a96039785f44130a5b631b3c'}\n+  'installd_232.dmp.idx': '8aeff0d56379d4bc1e5780da16fc4af0'}\n"
        }
    }, 
    "errors": {
        "testCase (rekall.plugins.windows.taskmods.TestWinMemDump)": {}
    }, 
    "logging": [
        "2016-03-28 11:06:40,766:DEBUG:rekall.1:Logging level set to 10", 
        "2016-03-28 11:06:40,767:DEBUG:rekall.1:Voting round with base: None", 
        "2016-03-28 11:06:40,767:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-03-28 11:06:40,767:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided", 
        "2016-03-28 11:06:40,767:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-03-28 11:06:40,767:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space", 
        "2016-03-28 11:06:40,768:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-03-28 11:06:40,768:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided", 
        "2016-03-28 11:06:40,768:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-03-28 11:06:40,768:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided", 
        "2016-03-28 11:06:40,769:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-03-28 11:06:40,769:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space", 
        "2016-03-28 11:06:40,769:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-03-28 11:06:40,769:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space", 
        "2016-03-28 11:06:40,769:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-03-28 11:06:40,769:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided", 
        "2016-03-28 11:06:40,770:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-03-28 11:06:40,770:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided", 
        "2016-03-28 11:06:40,770:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-03-28 11:06:40,770:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space", 
        "2016-03-28 11:06:40,770:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-03-28 11:06:40,770:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.", 
        "2016-03-28 11:06:40,770:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-03-28 11:06:40,813:INFO:rekall.1:Added aff4://157f794b-6749-496c-bde9-e6586ee65fab/PhysicalMemory as physical memory", 
        "2016-03-28 11:06:40,816:DEBUG:rekall.1:Succeeded instantiating AFF4AddressSpace", 
        "2016-03-28 11:06:40,816:DEBUG:rekall.1:Voting round with base: AFF4AddressSpace", 
        "2016-03-28 11:06:40,816:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-03-28 11:06:40,821:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x45", 
        "2016-03-28 11:06:40,821:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-03-28 11:06:40,822:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-03-28 11:06:40,822:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-03-28 11:06:40,822:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-03-28 11:06:40,822:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-03-28 11:06:40,822:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "2016-03-28 11:06:40,822:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-03-28 11:06:40,823:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "2016-03-28 11:06:40,823:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-03-28 11:06:40,823:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "2016-03-28 11:06:40,823:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-03-28 11:06:40,823:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "2016-03-28 11:06:40,823:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-03-28 11:06:40,824:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "2016-03-28 11:06:40,824:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-03-28 11:06:40,824:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "2016-03-28 11:06:40,824:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-03-28 11:06:40,824:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature", 
        "2016-03-28 11:06:40,824:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-03-28 11:06:40,825:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space", 
        "2016-03-28 11:06:40,826:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-03-28 11:06:40,826:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.", 
        "2016-03-28 11:06:40,826:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-03-28 11:06:40,826:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space", 
        "2016-03-28 11:06:40,826:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> ", 
        "2016-03-28 11:06:40,826:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space", 
        "2016-03-28 11:06:40,826:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> ", 
        "2016-03-28 11:06:40,827:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified", 
        "2016-03-28 11:06:40,827:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> ", 
        "2016-03-28 11:06:40,828:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.", 
        "2016-03-28 11:06:40,828:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> ", 
        "2016-03-28 11:06:40,828:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified", 
        "2016-03-28 11:06:40,828:INFO:rekall.1:Autodetected physical address space AFF4AddressSpace", 
        "2016-03-28 11:06:40,836:DEBUG:rekall.1:Will detect profile using these Detectors: linux_index,nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux", 
        "2016-03-28 11:06:40,837:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-profiles/v1.0/inventory.gz", 
        "2016-03-28 11:06:40,856:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/inventory.gz", 
        "2016-03-28 11:06:40,857:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/Linux/index.gz", 
        "2016-03-28 11:06:40,934:INFO:rekall.1:Loaded profile Linux/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0772190093994 sec)", 
        "2016-03-28 11:06:40,934:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/eprocess_index.gz", 
        "2016-03-28 11:06:40,985:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0511929988861 sec)", 
        "2016-03-28 11:06:40,986:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/index.gz", 
        "2016-03-28 11:06:41,078:INFO:rekall.1:Loaded profile nt/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0919740200043 sec)", 
        "2016-03-28 11:06:41,078:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/OSX/index.gz", 
        "2016-03-28 11:06:41,079:INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.000818967819214 sec)", 
        "2016-03-28 11:06:41,079:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/pe.gz", 
        "2016-03-28 11:06:41,098:INFO:rekall.1:Loaded profile pe from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.018355846405 sec)", 
        "2016-03-28 11:06:41,098:DEBUG:rekall.1:Trying method pe, offset 0", 
        "2016-03-28 11:06:41,101:DEBUG:rekall.1:Trying method windows_kernel_file, offset 0", 
        "2016-03-28 11:06:41,101:DEBUG:rekall.1:Trying method rsds, offset 0", 
        "2016-03-28 11:06:41,102:DEBUG:rekall.1:Trying method linux_index, offset 0", 
        "2016-03-28 11:06:41,102:DEBUG:rekall.1:LinuxIndexDetector:DetectFromHit(0) = None", 
        "2016-03-28 11:06:41,102:DEBUG:rekall.1:Trying method nt_index, offset 0", 
        "2016-03-28 11:06:41,102:DEBUG:rekall.1:Trying method ntfs, offset 0", 
        "2016-03-28 11:06:41,103:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/ntfs.gz", 
        "2016-03-28 11:06:41,104:INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0018310546875 sec)", 
        "2016-03-28 11:07:10,957:DEBUG:rekall.1:OSX/10.10.3_14D136.64bit matched offset -0xe1ec0+0x2384c000=0x2376a140 ('Darwin Kernel Version ')", 
        "2016-03-28 11:07:10,957:DEBUG:rekall.1:OSX/10.10.3_14D136.64bit matched offset -0xe1e46+0x2384c000=0x2376a1ba ('root\\x00')", 
        "2016-03-28 11:07:10,957:DEBUG:rekall.1:OSX/10.10.3_14D136.64bit matches 2/2 comparison points", 
        "2016-03-28 11:07:10,958:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/OSX/10.10.3_14D136.64bit.gz", 
        "2016-03-28 11:07:11,648:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-profiles/v1.0/OSX/dynamic.gz", 
        "2016-03-28 11:07:11,649:INFO:rekall.1:Loaded profile OSX/dynamic from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.000890016555786 sec)", 
        "2016-03-28 11:07:11,649:INFO:rekall.1:Loaded profile OSX/10.10.3_14D136.64bit from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.691134929657 sec)", 
        "2016-03-28 11:07:11,654:DEBUG:rekall.1:Searching for KASLR hits.", 
        "2016-03-28 11:07:31,446:INFO:rekall.1:New best match: OSX/10.10.3_14D136.64bit (100% match)", 
        "2016-03-28 11:07:31,446:DEBUG:rekall.1:Detection method osx worked at offset 0x2384c000", 
        "2016-03-28 11:07:31,448:DEBUG:rekall.1:Running plugin (memdump) with args (()) kwargs ({'profile': None, 'all': False, 'pid': [232], 'proc_regex': None, 'coalesce': False, 'dump_dir': '/tmp/tmpDh7Wbv/TestWinMemDumpThread-4', 'phys_proc': None, 'proc': None})"
    ], 
    "time_used": 88.87549901008606, 
    "return_code": 0, 
    "output": [
        "**************************************************", 
        "Writing 0xff80326341a0||installd||  232 to installd_232.dmp"
    ], 
    "hashes": {
        "installd_232.dmp.idx": "8aeff0d56379d4bc1e5780da16fc4af0", 
        "installd_232.dmp": "27aef9c398bbd6c08587d1b6661d3529"
    }, 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/osx10.11.3/10.11.3.aff4", 
        "--format": "test", 
        "commandline": "memdump --pid=%(pid)s --dump_dir %(tempdir)s", 
        "script": "search('(SELECT proc.p_fd.fd_ofiles[4].vnode.full_path AS path FROM pslist WHERE proc.command == \"Finder\" LIMIT 1) == (SELECT proc.p_fd.fd_ofiles[4].human_name AS path FROM pslist WHERE proc.command == \"Finder\" LIMIT 1)')", 
        "pid": 232, 
        "test_class": "TestWinMemDump", 
        "--cache_dir": "/home/scudette/projects/rekall-test/osx10.11.3/../profile_cache/", 
        "--cache": "memory", 
        "tempdir": "/tmp/tmpDh7Wbv/TestWinMemDumpThread-4", 
        "executed_command": "rekall  -v --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/osx10.11.3/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/osx10.11.3/10.11.3.aff4' --name_resolution_strategies 'Module' 'Symbol' - memdump --pid=232 --dump_dir /tmp/tmpDh7Wbv/TestWinMemDumpThread-4", 
        "testdir": "/home/scudette/projects/rekall-test/osx10.11.3"
    }
}