#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/ntfs/output/TestSimpleYaraScan /home/scudette/projects/rekall-test/ntfs/TestSimpleYaraScan
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/ntfs/output/TestSimpleYaraScan /home/scudette/projects/rekall-test/ntfs/TestSimpleYaraScan
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/ntfs/output/TestSimpleYaraScan /home/scudette/projects/rekall-test/ntfs/TestSimpleYaraScan
elif [ "$1" == "run" ]; then
   rekall  -v --profile 'ntfs' --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/ntfs/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/ntfs/ntfs1-gen1.E01' - simple_yarascan --binary_string 320030003000370036003500310037003100320033003200370033002e00700064006600 --hits 1
else
   less /home/scudette/projects/rekall-test/ntfs/output/TestSimpleYaraScan
fi
exit 0
{
    "failours": {
        "testCase (__main__.TestSimpleYaraScan)": {
            "testCase (__main__.TestSimpleYaraScan)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 300, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 354, in testCase\n    self.assertListEqual(previous, current)\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 275, in assertListEqual\n    self.assertEqual(x, y)\nAssertionError: u'   Rule   ||    Offset    ||                              HexDump              [truncated]... != u'   Rule   ||    Offset    ||                              hexdump              [truncated]...\n-    Rule   ||    Offset    ||                              HexDump                              \n?                                                           ^  ^\n+    Rule   ||    Offset    ||                              hexdump                              \n?                                                           ^  ^\n\n"
        }
    }, 
    "errors": {
        "testCase (__main__.TestSimpleYaraScan)": {}
    }, 
    "logging": [
        "2016-10-20 15:58:59,232:DEBUG:rekall.1:Logging level set to 10", 
        "2016-10-20 15:58:59,233:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-profiles/v1.0/inventory.gz", 
        "2016-10-20 15:58:59,250:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/inventory.gz", 
        "2016-10-20 15:58:59,758:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master//v1.0/inventory.gz", 
        "2016-10-20 15:58:59,825:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/inventory.gz", 
        "2016-10-20 15:58:59,826:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/ntfs.gz", 
        "2016-10-20 15:58:59,829:INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.00329113006592 sec)", 
        "2016-10-20 15:58:59,832:DEBUG:rekall.1:Running plugin (simple_yarascan) with args (()) kwargs ({'profile': 'ntfs', 'hits': 1, 'pre_context': 0, 'string': None, 'binary_string': '320030003000370036003500310037003100320033003200370033002e00700064006600', 'yara_expression': None, 'verbosity': 1, 'yara_file': None, 'start': 0, 'limit': 18446744073709551616L, 'context': 64})", 
        "2016-10-20 15:58:59,833:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/ntfs.gz", 
        "2016-10-20 15:58:59,835:INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.00201892852783 sec)", 
        "2016-10-20 15:58:59,835:DEBUG:rekall.1:Voting round with base: None", 
        "2016-10-20 15:58:59,835:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> ", 
        "2016-10-20 15:58:59,836:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason", 
        "2016-10-20 15:58:59,836:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-10-20 15:58:59,836:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided", 
        "2016-10-20 15:58:59,836:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-10-20 15:58:59,836:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space", 
        "2016-10-20 15:58:59,837:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-10-20 15:58:59,837:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided", 
        "2016-10-20 15:58:59,837:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-10-20 15:58:59,838:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided", 
        "2016-10-20 15:58:59,838:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-10-20 15:58:59,838:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space", 
        "2016-10-20 15:58:59,838:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-10-20 15:58:59,838:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space", 
        "2016-10-20 15:58:59,838:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-10-20 15:58:59,838:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided", 
        "2016-10-20 15:58:59,839:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-10-20 15:58:59,839:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided", 
        "2016-10-20 15:58:59,839:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-10-20 15:58:59,839:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space", 
        "2016-10-20 15:58:59,839:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-10-20 15:58:59,839:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.", 
        "2016-10-20 15:58:59,839:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-10-20 15:58:59,842:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume: No physical memory categories found.", 
        "2016-10-20 15:58:59,842:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-10-20 15:58:59,842:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at /home/scudette/projects/rekall-test/ntfs/ntfs1-gen1.E01_info", 
        "2016-10-20 15:58:59,842:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-10-20 15:58:59,842:DEBUG:rekall.1:Succeeded instantiating FileAddressSpace", 
        "2016-10-20 15:58:59,843:DEBUG:rekall.1:Voting round with base: FileAddressSpace", 
        "2016-10-20 15:58:59,843:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> ", 
        "2016-10-20 15:58:59,843:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason", 
        "2016-10-20 15:58:59,843:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-10-20 15:58:59,846:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x9465645", 
        "2016-10-20 15:58:59,846:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-10-20 15:58:59,846:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-10-20 15:58:59,846:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-10-20 15:58:59,846:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-10-20 15:58:59,847:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-10-20 15:58:59,856:DEBUG:rekall.1:Succeeded instantiating EWFAddressSpace", 
        "2016-10-20 15:58:59,856:DEBUG:rekall.1:Voting round with base: EWFAddressSpace", 
        "2016-10-20 15:58:59,856:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> ", 
        "2016-10-20 15:58:59,857:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason", 
        "2016-10-20 15:58:59,857:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-10-20 15:58:59,859:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x4e9052eb", 
        "2016-10-20 15:58:59,859:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-10-20 15:58:59,859:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-10-20 15:58:59,859:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-10-20 15:58:59,859:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-10-20 15:58:59,859:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-10-20 15:58:59,861:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "2016-10-20 15:58:59,861:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-10-20 15:58:59,862:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "2016-10-20 15:58:59,862:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-10-20 15:58:59,862:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "2016-10-20 15:58:59,862:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-10-20 15:58:59,863:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "2016-10-20 15:58:59,863:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-10-20 15:58:59,863:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "2016-10-20 15:58:59,863:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-10-20 15:58:59,864:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "2016-10-20 15:58:59,864:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-10-20 15:58:59,864:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature", 
        "2016-10-20 15:58:59,864:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-10-20 15:58:59,865:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space", 
        "2016-10-20 15:58:59,865:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-10-20 15:58:59,865:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.", 
        "2016-10-20 15:58:59,865:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-10-20 15:58:59,865:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space", 
        "2016-10-20 15:58:59,866:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> ", 
        "2016-10-20 15:58:59,866:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space", 
        "2016-10-20 15:58:59,866:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> ", 
        "2016-10-20 15:58:59,867:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified", 
        "2016-10-20 15:58:59,867:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> ", 
        "2016-10-20 15:58:59,868:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.", 
        "2016-10-20 15:58:59,868:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> ", 
        "2016-10-20 15:58:59,868:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified", 
        "2016-10-20 15:58:59,868:INFO:rekall.1:Autodetected physical address space EWFAddressSpace", 
        "2016-10-20 15:58:59,869:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/ntfs.gz", 
        "2016-10-20 15:58:59,871:INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.00214004516602 sec)"
    ], 
    "time_used": 13.843597888946533, 
    "return_code": 0, 
    "output": [
        "   Rule   ||    Offset    ||                              hexdump                              ", 
        "----------||--------------||-------------------------------------------------------------------"
    ], 
    "executed_command": "rekall  -v --profile 'ntfs' --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/ntfs/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/ntfs/ntfs1-gen1.E01' - simple_yarascan --binary_string 320030003000370036003500310037003100320033003200370033002e00700064006600 --hits 1", 
    "options": {
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/ntfs/ntfs1-gen1.E01", 
        "--format": "test", 
        "commandline": "simple_yarascan --binary_string 320030003000370036003500310037003100320033003200370033002e00700064006600 --hits 1", 
        "--profile": "ntfs", 
        "test_class": "TestSimpleYaraScan", 
        "mft": 42, 
        "tempdir": "/tmp/tmpHcLkSc/TestSimpleYaraScanThread-3", 
        "--cache_dir": "/home/scudette/projects/rekall-test/ntfs/../profile_cache/", 
        "--cache": "memory", 
        "debug": false, 
        "path": "RAW/20076517123273.pdf", 
        "testdir": "/home/scudette/projects/rekall-test/ntfs"
    }
}