#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/ntfs/output/TestDT /home/scudette/projects/rekall-test/ntfs/TestDT
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/ntfs/output/TestDT /home/scudette/projects/rekall-test/ntfs/TestDT
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/ntfs/output/TestDT /home/scudette/projects/rekall-test/ntfs/TestDT
elif [ "$1" == "run" ]; then
   rekall  --profile 'ntfs' --renderer 'test' --filename '/home/scudette/projects/rekall-test/ntfs/ntfs1-gen1.E01' - dt MFT_ENTRY
else
   less /home/scudette/projects/rekall-test/ntfs/output/TestDT
fi
exit 0
{
    "errors": {}, 
    "time_used": 0.7436130046844482, 
    "return_code": 0, 
    "failures": {
        "testCase (__main__.TestDT)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 221, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 271, in testCase\n    self.assertEqual(previous, current)\nAssertionError: u'Offset      ||            Field             ||Content' != u'Offset              ||            Field             ||Content'\n- Offset      ||            Field             ||Content\n+ Offset              ||            Field             ||Content\n?             ++++++++\n\n"
    }, 
    "output": [
        "[MFT_ENTRY MFT_ENTRY] @ 0x000000 ", 
        "Offset              ||            Field             ||Content", 
        "--------------------||------------------------------||-------", 
        " ||           0x0    ||magic                         || [String:magic]: ''", 
        " ||           0x4    ||fixup_offset                  || [unsigned short:fixup_offset]: <Unable to read 2 bytes from 4>", 
        " ||           0x6    ||fixup_count                   || [unsigned short:fixup_count]: <Unable to read 2 bytes from 6>", 
        " ||           0x8    ||logfile_sequence_number       || [unsigned long long:logfile_sequence_number]: <Unable to read 8 bytes from 8>", 
        " ||          0x10    ||sequence_value                || [unsigned short:sequence_value]: <Unable to read 2 bytes from 16>", 
        " ||          0x12    ||link_count                    || [unsigned short:link_count]: <Unable to read 2 bytes from 18>", 
        " ||          0x14    ||attribute_offset              || [unsigned short:attribute_offset]: <Unable to read 2 bytes from 20>", 
        " ||          0x16    ||flags                         || [Flags:flags]: <Unable to read 2 bytes from 22> ()", 
        " ||          0x18    ||mft_entry_size                || [unsigned short:mft_entry_size]: <Unable to read 2 bytes from 24>", 
        " ||          0x1c    ||mft_entry_allocated           || [unsigned short:mft_entry_allocated]: <Unable to read 2 bytes from 28>", 
        " ||          0x20    ||base_record_reference         || [unsigned long long:base_record_reference]: <Unable to read 8 bytes from 32>", 
        " ||          0x28    ||next_attribute_id             || [unsigned short:next_attribute_id]: <Unable to read 2 bytes from 40>", 
        " ||0xffffffffffff    ||_attributes                   ||<ListArray 0 x NTFS_ATTRIBUTE @ 0xFFFFFFFFFFFF>", 
        " ||0xffffffffffff    ||fixup_magic                   || [String:fixup_magic]: <Plugin not active>", 
        " ||0xffffffffffff    ||fixup_table                   ||<Array - x String @ 0xFFFFFFFFFFFF>"
    ], 
    "options": {
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/ntfs/ntfs1-gen1.E01", 
        "commandline": "dt MFT_ENTRY", 
        "--renderer": "test", 
        "tempdir": "/tmp/tmpYzNIdY/TestDTThread-4", 
        "mfts": "42 40", 
        "test_class": "TestDT", 
        "executed_command": "rekall  --profile 'ntfs' --renderer 'test' --filename '/home/scudette/projects/rekall-test/ntfs/ntfs1-gen1.E01' - dt MFT_ENTRY", 
        "--profile": "ntfs", 
        "path": "RAW/20076517123273.pdf", 
        "testdir": "/home/scudette/projects/rekall-test/ntfs"
    }
}