#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/ntfs/output/TestFStat /home/scudette/projects/rekall-test/ntfs/TestFStat
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/ntfs/output/TestFStat /home/scudette/projects/rekall-test/ntfs/TestFStat
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/ntfs/output/TestFStat /home/scudette/projects/rekall-test/ntfs/TestFStat
elif [ "$1" == "run" ]; then
   rekall  --profile 'ntfs' --renderer 'test' --cache_dir '/home/scudette/projects/rekall-test/ntfs/../profile_cache/' --filename '/home/scudette/projects/rekall-test/ntfs/ntfs1-gen1.E01' - fstat RAW/20076517123273.pdf
else
   less /home/scudette/projects/rekall-test/ntfs/output/TestFStat
fi
exit 0
{
    "errors": {}, 
    "time_used": 1.1297221183776855, 
    "return_code": 0, 
    "failures": {
        "testCase (rekall.plugins.filesystems.ntfs.TestFStat)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 227, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 277, in testCase\n    self.assertEqual(previous, current)\nAssertionError: u'Clusters (128-1):' != u'Clusters ($DATA-1):'\n- Clusters (128-1):\n?           ^^^\n+ Clusters ($DATA-1):\n?           ^^^^^\n\n"
    }, 
    "output": [
        "MFT Entry Header Values:", 
        "Entry: 42        Sequence: 1", 
        "$LogFile Sequence Number: 3170835", 
        "Links: 2", 
        "", 
        "$STANDARD_INFORMATION Attribute Values:", 
        "Flags                         ||ARCHIVE                       ", 
        "Owner ID                      ||0                             ", 
        "SID                           ||260                           ", 
        "Created                       ||2008-12-31 23:16:29+0000      ", 
        "File Modified                 ||2008-12-31 23:15:30+0000      ", 
        "MFT Modified                  ||2008-12-31 23:15:36+0000      ", 
        "Accessed                      ||2008-12-31 23:16:29+0000      ", 
        "", 
        "Attributes:", 
        "     Inode     ||             Type             ||   Name   || Res ||   Size   ||Comment", 
        "---------------||------------------------------||----------||-----||----------||-------", 
        "        42-16-0||$STANDARD_INFORMATION         ||          ||True ||        72||       ", 
        "        42-48-3||$FILE_NAME                    ||          ||True ||        90||200765~1.PDF", 
        "        42-48-2||$FILE_NAME                    ||          ||True ||       102||20076517123273.pdf", 
        "       42-128-1||$DATA                         ||          ||False||   1001647||VCN: 0-1956", 
        "", 
        "Clusters ($DATA-1):", 
        "478465-480422(1957)      "
    ], 
    "options": {
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/ntfs/ntfs1-gen1.E01", 
        "--cache_dir": "/home/scudette/projects/rekall-test/ntfs/../profile_cache/", 
        "commandline": "fstat %(path)s", 
        "--renderer": "test", 
        "tempdir": "/tmp/tmpxdhsN5/TestFStatThread-2", 
        "test_class": "TestFStat", 
        "mft": 42, 
        "executed_command": "rekall  --profile 'ntfs' --renderer 'test' --cache_dir '/home/scudette/projects/rekall-test/ntfs/../profile_cache/' --filename '/home/scudette/projects/rekall-test/ntfs/ntfs1-gen1.E01' - fstat RAW/20076517123273.pdf", 
        "--profile": "ntfs", 
        "path": "RAW/20076517123273.pdf", 
        "testdir": "/home/scudette/projects/rekall-test/ntfs"
    }
}