#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /Users/scudette/projects/rekall-test/ntfs/output/TestIExport /Users/scudette/projects/rekall-test/ntfs/TestIExport
elif [ "$1" == "meld" ]; then
   meld /Users/scudette/projects/rekall-test/ntfs/output/TestIExport /Users/scudette/projects/rekall-test/ntfs/TestIExport
elif [ "$1" == "diff" ]; then
   diff /Users/scudette/projects/rekall-test/ntfs/output/TestIExport /Users/scudette/projects/rekall-test/ntfs/TestIExport
elif [ "$1" == "run" ]; then
   rekall  -v --profile 'ntfs' --cache_dir '/Users/scudette/projects/rekall-test/ntfs/../profile_cache/' --format 'test' --filename '/Users/scudette/projects/rekall-test/ntfs/ntfs1-gen1.E01' - iexport 40 --dump_dir /var/folders/y8/670pn1dx55x01z5fs_6r2gnh003jp1/T/tmpuAwoJJ/TestIExportThread-8
else
   less /Users/scudette/projects/rekall-test/ntfs/output/TestIExport
fi
exit 0
{
    "errors": {}, 
    "logging": [
        "DEBUG:rekall.1:Logging level set to 10", 
        "DEBUG:rekall.1:Opened local file /Users/scudette/projects/rekall-profiles/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Opened local file /Users/scudette/projects/rekall-test/profile_cache/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Opened url https://raw.githubusercontent.com/google/rekall-profiles/master/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Opened local file /Users/scudette/projects/rekall-test/profile_cache/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Opened local file /Users/scudette/projects/rekall-test/profile_cache/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Opened local file /Users/scudette/projects/rekall-test/profile_cache/v1.0/ntfs.gz", 
        "INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:/Users/scudette/projects/rekall-test/profile_cache (in 0.00205898284912 sec)", 
        "DEBUG:rekall.1:Voting round with base: None", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at /Users/scudette/projects/rekall-test/ntfs/ntfs1-gen1.E01_info", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "DEBUG:rekall.1:Succeeded instantiating FileAddressSpace", 
        "DEBUG:rekall.1:Voting round with base: FileAddressSpace", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x9465645", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "DEBUG:rekall.1:Succeeded instantiating EWFAddressSpace", 
        "DEBUG:rekall.1:Voting round with base: EWFAddressSpace", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x4e9052eb", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> ", 
        "DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified", 
        "INFO:rekall.1:Autodetected physical address space EWFAddressSpace", 
        "DEBUG:rekall.1:Opened local file /Users/scudette/projects/rekall-test/profile_cache/v1.0/ntfs.gz", 
        "INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:/Users/scudette/projects/rekall-test/profile_cache (in 0.00208616256714 sec)", 
        "DEBUG:rekall.1:Running plugin (iexport) with args (()) kwargs ({'profile': 'ntfs', 'mft': 40, 'type': 128, 'id': None, 'dump_dir': '/var/folders/y8/670pn1dx55x01z5fs_6r2gnh003jp1/T/tmpuAwoJJ/TestIExportThread-8'})"
    ], 
    "time_used": 2.040252923965454, 
    "return_code": 0, 
    "failures": {
        "testCase (rekall.plugins.filesystems.ntfs.TestIExport)": "Traceback (most recent call last):\n  File \"/Users/scudette/projects/rekall/rekall-core/rekall/testlib.py\", line 234, in run\n    testMethod()\n  File \"/Users/scudette/projects/rekall/rekall-core/rekall/testlib.py\", line 331, in testCase\n    self.assertEqual(self.baseline['hashes'], self.current['hashes'])\nAssertionError: {u'Compressed%2f20076517123273.pdf': u'2e167810afd3e5398b3fc439a99a4ef2'} != {'Compressed%2f20076517123273.pdf': '3e287d7cec7952b7f969c9a966d18b06'}\n- {u'Compressed%2f20076517123273.pdf': u'2e167810afd3e5398b3fc439a99a4ef2'}\n+ {'Compressed%2f20076517123273.pdf': '3e287d7cec7952b7f969c9a966d18b06'}\n"
    }, 
    "output": [
        "Writing MFT Entry 40 as Compressed/20076517123273.pdf"
    ], 
    "hashes": {
        "Compressed%2f20076517123273.pdf": "3e287d7cec7952b7f969c9a966d18b06"
    }, 
    "options": {
        "executable": "rekall ", 
        "--filename": "/Users/scudette/projects/rekall-test/ntfs/ntfs1-gen1.E01", 
        "--format": "test", 
        "commandline": "iexport %(mfts)s --dump_dir %(tempdir)s", 
        "tempdir": "/var/folders/y8/670pn1dx55x01z5fs_6r2gnh003jp1/T/tmpuAwoJJ/TestIExportThread-8", 
        "mfts": 40, 
        "test_class": "TestIExport", 
        "mft": 42, 
        "--cache_dir": "/Users/scudette/projects/rekall-test/ntfs/../profile_cache/", 
        "executed_command": "rekall  -v --profile 'ntfs' --cache_dir '/Users/scudette/projects/rekall-test/ntfs/../profile_cache/' --format 'test' --filename '/Users/scudette/projects/rekall-test/ntfs/ntfs1-gen1.E01' - iexport 40 --dump_dir /var/folders/y8/670pn1dx55x01z5fs_6r2gnh003jp1/T/tmpuAwoJJ/TestIExportThread-8", 
        "--profile": "ntfs", 
        "path": "RAW/20076517123273.pdf", 
        "testdir": "/Users/scudette/projects/rekall-test/ntfs"
    }
}