#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestListEvents /home/scudette/projects/rekall-test/tigger/TestListEvents
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestListEvents /home/scudette/projects/rekall-test/tigger/TestListEvents
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestListEvents /home/scudette/projects/rekall-test/tigger/TestListEvents
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - list_events
else
   less /home/scudette/projects/rekall-test/tigger/output/TestListEvents
fi
exit 0
{
    "time_used": 23.962346076965332, 
    "output": [
        "               Time                || Category ||            Actor             ||            Action            ||            Target            ", 
        "-----------------------------------||----------||------------------------------||------------------------------||------------------------------", 
        "2010-08-11 06:06:21+0000           ||-         ||-                             ||created                       ||smss.exe                      ", 
        "2010-08-11 06:06:23+0000           ||-         ||-                             ||created                       ||winlogon.exe                  ", 
        "2010-08-11 06:06:23+0000           ||-         ||-                             ||created                       ||csrss.exe                     ", 
        "2010-08-11 06:06:24+0000           ||-         ||-                             ||created                       ||svchost.exe                   ", 
        "2010-08-11 06:06:24+0000           ||-         ||-                             ||created                       ||svchost.exe                   ", 
        "2010-08-11 06:06:24+0000           ||-         ||-                             ||created                       ||vmacthlp.exe                  ", 
        "2010-08-11 06:06:24+0000           ||-         ||-                             ||created                       ||svchost.exe                   ", 
        "2010-08-11 06:06:24+0000           ||-         ||-                             ||created                       ||services.exe                  ", 
        "2010-08-11 06:06:24+0000           ||-         ||-                             ||created                       ||lsass.exe                     ", 
        "2010-08-11 06:06:25+0000           ||-         ||-                             ||created                       ||svchost.exe                   ", 
        "2010-08-11 06:06:26+0000           ||-         ||-                             ||created                       ||spoolsv.exe                   ", 
        "2010-08-11 06:06:26+0000           ||-         ||-                             ||created                       ||svchost.exe                   ", 
        "2010-08-11 06:06:35+0000           ||-         ||-                             ||created                       ||vmtoolsd.exe                  ", 
        "2010-08-11 06:06:38+0000           ||-         ||-                             ||created                       ||VMUpgradeHelper               ", 
        "2010-08-11 06:06:39+0000           ||-         ||-                             ||created                       ||alg.exe                       ", 
        "2010-08-11 06:06:39+0000           ||-         ||-                             ||created                       ||TPAutoConnSvc.e               ", 
        "2010-08-11 06:06:49+0000           ||-         ||-                             ||created                       ||wscntfy.exe                   ", 
        "2010-08-11 06:06:52+0000           ||-         ||-                             ||created                       ||TPAutoConnect.e               ", 
        "2010-08-11 06:07:44+0000           ||-         ||-                             ||created                       ||wuauclt.exe                   ", 
        "2010-08-11 06:09:29+0000           ||-         ||-                             ||created                       ||explorer.exe                  ", 
        "2010-08-11 06:09:31+0000           ||-         ||-                             ||created                       ||VMwareTray.exe                ", 
        "2010-08-11 06:09:32+0000           ||-         ||-                             ||created                       ||VMwareUser.exe                ", 
        "2010-08-11 06:09:37+0000           ||-         ||-                             ||created                       ||wuauclt.exe                   ", 
        "2010-08-15 19:26:08+0000           ||-         ||-                             ||created                       ||wmiprvse.exe                  "
    ], 
    "errors": {}, 
    "return_code": 0, 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "list_events", 
        "pid": "1724", 
        "--renderer": "test", 
        "test_class": "TestListEvents", 
        "tempdir": "/tmp/tmpKOly3v/TestListEventsThread-4", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - list_events", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}