#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestConsoles /home/scudette/projects/rekall-test/tigger/TestConsoles
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestConsoles /home/scudette/projects/rekall-test/tigger/TestConsoles
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestConsoles /home/scudette/projects/rekall-test/tigger/TestConsoles
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - consoles
else
   less /home/scudette/projects/rekall-test/tigger/output/TestConsoles
fi
exit 0
{
    "errors": {}, 
    "time_used": 1.8471801280975342, 
    "return_code": 0, 
    "failures": {
        "testCase (__main__.TestConsoles)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 227, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 277, in testCase\n    self.assertEqual(previous, current)\nAssertionError: 22 != 0\n"
    }, 
    "output": [], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "consoles", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestConsoles", 
        "tempdir": "/tmp/tmpJPWnUD/TestConsolesThread-2", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - consoles", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}