#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestPFNInfo /home/scudette/projects/rekall-test/tigger/TestPFNInfo
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestPFNInfo /home/scudette/projects/rekall-test/tigger/TestPFNInfo
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestPFNInfo /home/scudette/projects/rekall-test/tigger/TestPFNInfo
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - pfn 0x4a06
else
   less /home/scudette/projects/rekall-test/tigger/output/TestPFNInfo
fi
exit 0
{
    "time_used": 0.9201960563659668, 
    "output": [
        "    PFN 0x00004A06 at kernel address 0x0000000080E818A8", 
        "    flink       00000000  blink / share count 0000000000000001", 
        "    pteaddress (VAS) 0x00000000C07F9C30  (Phys AS) 0x000000000103FC30", 
        "    reference count 0001   color -", 
        "    containing page        0x0000103F  ActiveAndValid     PM", 
        "    ParityError Modified", 
        "    "
    ], 
    "errors": {}, 
    "return_code": 0, 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "pfn 0x4a06", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestPFNInfo", 
        "tempdir": "/tmp/tmpZtp3eR/TestPFNInfoThread-1", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - pfn 0x4a06", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}