#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /Users/adamsh/Projects/rekall-test/tigger/output/TestCheckPEHooks /Users/adamsh/Projects/rekall-test/tigger/TestCheckPEHooks
elif [ "$1" == "meld" ]; then
   meld /Users/adamsh/Projects/rekall-test/tigger/output/TestCheckPEHooks /Users/adamsh/Projects/rekall-test/tigger/TestCheckPEHooks
elif [ "$1" == "diff" ]; then
   diff /Users/adamsh/Projects/rekall-test/tigger/output/TestCheckPEHooks /Users/adamsh/Projects/rekall-test/tigger/TestCheckPEHooks
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - check_pehooks
else
   less /Users/adamsh/Projects/rekall-test/tigger/output/TestCheckPEHooks
fi
exit 0
{
    "time_used": 3.473466157913208, 
    "output": [
        "        Name        ||             Hook             ||                        Disassembly                         ", 
        "--------------------||------------------------------||------------------------------------------------------------", 
        "                           Import                           ||   Dest   ||                         Dest Name                          ", 
        "------------------------------------------------------------||----------||------------------------------------------------------------", 
        "Export||   Dest   ||Dest Name", 
        "------||----------||---------"
    ], 
    "errors": {}, 
    "return_code": 0, 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "check_pehooks", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestCheckPEHooks", 
        "tempdir": "/var/folders/yc/4zng19655k37kyxgskb3vvf0006t70/T/tmpHPq5l9/TestCheckPEHooksThread-7", 
        "executed_command": "rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - check_pehooks", 
        "testdir": "/Users/adamsh/Projects/rekall-test/tigger"
    }
}