#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /Users/adamsh/Projects/rekall-test/tigger/output/TestUsers /Users/adamsh/Projects/rekall-test/tigger/TestUsers
elif [ "$1" == "meld" ]; then
   meld /Users/adamsh/Projects/rekall-test/tigger/output/TestUsers /Users/adamsh/Projects/rekall-test/tigger/TestUsers
elif [ "$1" == "diff" ]; then
   diff /Users/adamsh/Projects/rekall-test/tigger/output/TestUsers /Users/adamsh/Projects/rekall-test/tigger/TestUsers
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - users
else
   less /Users/adamsh/Projects/rekall-test/tigger/output/TestUsers
fi
exit 0
{
    "time_used": 4.25727105140686, 
    "output": [
        "**************************************************", 
        "Key SAM/SAM/Domains/Account/Users/000001F4 ", 
        "", 
        "UserName            ||Administrator", 
        "Comment             ||Built-in account for administering the computer/domain", 
        "NTHash              ||01000100e6769487ddec3969cd1f0882b407f878", 
        "LanHash             ||01000100da9188cbe583bb9b99261969e5ffc546", 
        "FullName            || ", 
        "Type                ||Default Admin User", 
        "AccountExpiration   ||-", 
        "LoginCount          ||4", 
        "FailedLoginCount    ||0", 
        "Flags               ||Normal user account, Password does not expire", 
        "PasswordFailedTime  ||2010-08-11 06:06:26+0000", 
        "LastLoginTime       ||2010-08-11 06:06:46+0000", 
        "Rid                 ||500", 
        "PwdResetDate        ||2010-06-10 12:04:39+0000", 
        "**************************************************", 
        "Key SAM/SAM/Domains/Account/Users/000001F5 ", 
        "", 
        "UserName            ||Guest", 
        "Comment             ||Built-in account for guest access to the computer/domain", 
        "NTHash              ||01000100", 
        "LanHash             ||01000100", 
        "FullName            || ", 
        "Type                ||Default Guest Acct", 
        "AccountExpiration   ||-", 
        "LoginCount          ||0", 
        "FailedLoginCount    ||0", 
        "Flags               ||Account Disabled, Normal user account, Password does not expire, Password not required", 
        "PasswordFailedTime  ||-", 
        "LastLoginTime       ||-", 
        "Rid                 ||501", 
        "PwdResetDate        ||-", 
        "**************************************************", 
        "Key SAM/SAM/Domains/Account/Users/000003E8 ", 
        "", 
        "UserName            ||HelpAssistant", 
        "Comment             ||Account for Providing Remote Assistance", 
        "NTHash              ||01000100213e00b9a65652b6f8bcec0bde9dc45c", 
        "LanHash             ||010001003e65c850435ad0fd04d03753c1b369dd", 
        "FullName            ||Remote Desktop Help Assistant Account", 
        "Type                ||Custom Limited Acct", 
        "AccountExpiration   ||-", 
        "LoginCount          ||0", 
        "FailedLoginCount    ||0", 
        "Flags               ||Account Disabled, Normal user account, Password does not expire", 
        "PasswordFailedTime  ||-", 
        "LastLoginTime       ||-", 
        "Rid                 ||1000", 
        "PwdResetDate        ||2010-06-10 16:06:16+0000", 
        "**************************************************", 
        "Key SAM/SAM/Domains/Account/Users/000003EA ", 
        "", 
        "UserName            ||SUPPORT_388945a0", 
        "Comment             ||This is a vendor's account for the Help and Support Service", 
        "NTHash              ||01000100556e3874711c06503685fcddf6408277", 
        "LanHash             ||01000100", 
        "FullName            ||CN=Microsoft Corporation,L=Redmond,S=Washington,C=US", 
        "Type                ||Custom Limited Acct", 
        "AccountExpiration   ||-", 
        "LoginCount          ||0", 
        "FailedLoginCount    ||0", 
        "Flags               ||Account Disabled, Normal user account, Password does not expire", 
        "PasswordFailedTime  ||-", 
        "LastLoginTime       ||-", 
        "Rid                 ||1002", 
        "PwdResetDate        ||2010-06-10 16:07:40+0000"
    ], 
    "errors": {}, 
    "return_code": 0, 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "users", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestUsers", 
        "tempdir": "/var/folders/yc/4zng19655k37kyxgskb3vvf0006t70/T/tmpaPKNo8/TestUsersThread-6", 
        "executed_command": "rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - users", 
        "testdir": "/Users/adamsh/Projects/rekall-test/tigger"
    }
}