#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/test_data/tigger/output/TestListEvents /home/scudette/projects/test_data/tigger/TestListEvents
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/test_data/tigger/output/TestListEvents /home/scudette/projects/test_data/tigger/TestListEvents
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/test_data/tigger/output/TestListEvents /home/scudette/projects/test_data/tigger/TestListEvents
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/home/scudette/projects/test_data/tigger/tigger.vmem' list_events
else
   less /home/scudette/projects/test_data/tigger/output/TestListEvents
fi
exit 0
{
    "time_used": 40.19984793663025, 
    "output": [
        "               Time                || Category ||            Actor             ||            Action            ||            Target            ", 
        "-----------------------------------||----------||------------------------------||------------------------------||------------------------------", 
        "2010-08-11 06:06:21+0000           ||-         ||-                             ||created                       ||Process: smss.exe             ", 
        "2010-08-11 06:06:23+0000           ||-         ||-                             ||created                       ||Process: csrss.exe            ", 
        "2010-08-11 06:06:23+0000           ||-         ||-                             ||created                       ||Process: winlogon.exe         ", 
        "2010-08-11 06:06:24+0000           ||-         ||-                             ||created                       ||Process: svchost.exe          ", 
        "2010-08-11 06:06:24+0000           ||-         ||-                             ||created                       ||Process: svchost.exe          ", 
        "2010-08-11 06:06:24+0000           ||-         ||-                             ||created                       ||Process: services.exe         ", 
        "2010-08-11 06:06:24+0000           ||-         ||-                             ||created                       ||Process: vmacthlp.exe         ", 
        "2010-08-11 06:06:24+0000           ||-         ||-                             ||created                       ||Process: svchost.exe          ", 
        "2010-08-11 06:06:24+0000           ||-         ||-                             ||created                       ||Process: lsass.exe            ", 
        "2010-08-11 06:06:25+0000           ||-         ||-                             ||created                       ||Process: svchost.exe          ", 
        "2010-08-11 06:06:26+0000           ||-         ||-                             ||created                       ||Process: svchost.exe          ", 
        "2010-08-11 06:06:26+0000           ||-         ||-                             ||created                       ||Process: spoolsv.exe          ", 
        "2010-08-11 06:06:35+0000           ||-         ||-                             ||created                       ||Process: vmtoolsd.exe         ", 
        "2010-08-11 06:06:38+0000           ||-         ||-                             ||created                       ||Process: VMUpgradeHelper      ", 
        "2010-08-11 06:06:39+0000           ||-         ||-                             ||created                       ||Process: alg.exe              ", 
        "2010-08-11 06:06:39+0000           ||-         ||-                             ||created                       ||Process: TPAutoConnSvc.e      ", 
        "2010-08-11 06:06:49+0000           ||-         ||-                             ||created                       ||Process: wscntfy.exe          ", 
        "2010-08-11 06:06:52+0000           ||-         ||-                             ||created                       ||Process: TPAutoConnect.e      ", 
        "2010-08-11 06:07:44+0000           ||-         ||-                             ||created                       ||Process: wuauclt.exe          ", 
        "2010-08-11 06:09:29+0000           ||-         ||-                             ||created                       ||Process: explorer.exe         ", 
        "2010-08-11 06:09:31+0000           ||-         ||-                             ||created                       ||Process: VMwareTray.exe       ", 
        "2010-08-11 06:09:32+0000           ||-         ||-                             ||created                       ||Process: VMwareUser.exe       ", 
        "2010-08-11 06:09:37+0000           ||-         ||-                             ||created                       ||Process: wuauclt.exe          ", 
        "2010-08-15 19:26:08+0000           ||-         ||-                             ||created                       ||Process: wmiprvse.exe         "
    ], 
    "errors": {}, 
    "return_code": 0, 
    "options": {
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/test_data/tigger/tigger.vmem", 
        "commandline": "list_events", 
        "pid": "1724", 
        "--renderer": "test", 
        "test_class": "TestListEvents", 
        "tempdir": "/tmp/tmp6JxHN4/TestListEventsThread-3", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/test_data/tigger/tigger.vmem' list_events", 
        "testdir": "/home/scudette/projects/test_data/tigger"
    }
}