#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestPas2Vas /home/scudette/projects/rekall-test/tigger/TestPas2Vas
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestPas2Vas /home/scudette/projects/rekall-test/tigger/TestPas2Vas
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestPas2Vas /home/scudette/projects/rekall-test/tigger/TestPas2Vas
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - pas2vas 77620688 --pid 0 
else
   less /home/scudette/projects/rekall-test/tigger/output/TestPas2Vas
fi
exit 0
{
    "errors": {}, 
    "time_used": 2.3195090293884277, 
    "return_code": 0, 
    "failures": {
        "testCase (rekall.plugins.windows.pas2kas.TestPas2Vas)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 221, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 271, in testCase\n    self.assertEqual(previous, current)\nAssertionError: u'0x04a065d0||0xff3865d0||0     ||Kernel' != u'0x04a065d0||0xff3865d0||     0||Kernel'\n- 0x04a065d0||0xff3865d0||0     ||Kernel\n?                          -----\n+ 0x04a065d0||0xff3865d0||     0||Kernel\n?                         +++++\n\n"
    }, 
    "output": [
        " Physical || Virtual  || Pid  ||Name", 
        "----------||----------||------||----", 
        "0x04a065d0||0xff3865d0||     0||Kernel"
    ], 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "pas2vas %(offset)s --pid 0 ", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestPas2Vas", 
        "offset": 77620688, 
        "tempdir": "/tmp/tmpblovS9/TestPas2VasThread-4", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - pas2vas 77620688 --pid 0 ", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}