#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestEntityFind /home/scudette/projects/rekall-test/tigger/TestEntityFind
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestEntityFind /home/scudette/projects/rekall-test/tigger/TestEntityFind
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestEntityFind /home/scudette/projects/rekall-test/tigger/TestEntityFind
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - find "Process/command =~ lsass"
else
   less /home/scudette/projects/rekall-test/tigger/output/TestEntityFind
fi
exit 0
{
    "time_used": 24.29048800468445, 
    "output": [
        "pid    parent               user                 command                        is_64bit   session             ", 
        "------ -------------------- -------------------- ------------------------------ ---------- --------------------", 
        "688    winlogon.exe         -                    lsass.exe                      False      -                   "
    ], 
    "errors": {}, 
    "return_code": 0, 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "process": "lsass", 
        "commandline": "find \"Process/command =~ %(process)s\"", 
        "pid": "1724", 
        "--renderer": "test", 
        "test_class": "TestEntityFind", 
        "tempdir": "/tmp/tmpKOly3v/TestEntityFindThread-1", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - find \"Process/command =~ lsass\"", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}