#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/test_data/tigger/output/TestEntityStats /home/scudette/projects/test_data/tigger/TestEntityStats
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/test_data/tigger/output/TestEntityStats /home/scudette/projects/test_data/tigger/TestEntityStats
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/test_data/tigger/output/TestEntityStats /home/scudette/projects/test_data/tigger/TestEntityStats
else
   less /home/scudette/projects/test_data/tigger/output/TestEntityStats
fi
exit 0
{
    "time_used": 1.8642239570617676, 
    "output": [
        "          Component           ||      Entities collected      ||      Active collectors       ", 
        "------------------------------||------------------------------||------------------------------", 
        "ERROR:root:Traceback (most recent call last):", 
        "  File \"/home/scudette/rekall/rekall/session.py\", line 576, in _RunPlugin", 
        "    plugin_obj.render(ui_renderer)", 
        "  File \"/home/scudette/rekall/rekall/plugins/common/entities.py\", line 71, in render", 
        "    if collector.can_collect(component_name):", 
        "AttributeError: 'EventInferenceCollector' object has no attribute 'can_collect'", 
        "", 
        "ERROR:root:'EventInferenceCollector' object has no attribute 'can_collect'. Try --debug for more information."
    ], 
    "errors": {}, 
    "options": {
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/test_data/tigger/tigger.vmem", 
        "commandline": "entity_stats", 
        "pid": "1724", 
        "--renderer": "test", 
        "test_class": "TestEntityStats", 
        "tempdir": "/tmp/tmpewe9M4/TestEntityStatsThread-4", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/test_data/tigger/tigger.vmem' entity_stats", 
        "testdir": "/home/scudette/projects/test_data/tigger"
    }
}