#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestWinMemDump /home/scudette/projects/rekall-test/tigger/TestWinMemDump
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestWinMemDump /home/scudette/projects/rekall-test/tigger/TestWinMemDump
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestWinMemDump /home/scudette/projects/rekall-test/tigger/TestWinMemDump
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - memdump --pid=1724 --dump_dir /tmp/tmpITXgLM/TestWinMemDumpThread-1
else
   less /home/scudette/projects/rekall-test/tigger/output/TestWinMemDump
fi
exit 0
{
    "errors": {
        "testCase (rekall.plugins.windows.taskmods.TestWinMemDump)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 216, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 318, in testCase\n    self.assertEqual(self.baseline['hashes'], self.current['hashes'])\nKeyError: 'hashes'\n"
    }, 
    "time_used": 2.4279890060424805, 
    "return_code": 0, 
    "failures": {}, 
    "output": [
        "**************************************************", 
        "Writing explorer.exe 0xff3865d0 to explorer.exe_1724.dmp"
    ], 
    "hashes": {
        "explorer.exe_1724.dmp.idx": "b467e97205093f3005b37ba9bd1a540f", 
        "explorer.exe_1724.dmp": "2daa014012b075fa4a462d43db85f30e"
    }, 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "memdump --pid=%(pid)s --dump_dir %(tempdir)s", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestWinMemDump", 
        "tempdir": "/tmp/tmpITXgLM/TestWinMemDumpThread-1", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - memdump --pid=1724 --dump_dir /tmp/tmpITXgLM/TestWinMemDumpThread-1", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}