#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestDump /home/scudette/projects/rekall-test/tigger/TestDump
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestDump /home/scudette/projects/rekall-test/tigger/TestDump
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestDump /home/scudette/projects/rekall-test/tigger/TestDump
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --cache_dir '/home/scudette/projects/rekall-test/tigger/../profile_cache/' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - dump "nt!str:PoolTag" --length=100
else
   less /home/scudette/projects/rekall-test/tigger/output/TestDump
fi
exit 0
{
    "errors": {}, 
    "time_used": 0.8740580081939697, 
    "return_code": 0, 
    "failures": {
        "testCase (__main__.TestDump)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 231, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 281, in testCase\n    self.assertEqual(previous, current)\nAssertionError: 48 != 9\n"
    }, 
    "output": [
        "  Offset  ||                              Data                               ||                Comment                 ", 
        "----------||-----------------------------------------------------------------||----------------------------------------", 
        "0x804df7ec||50 00 6f 00 6f 00 6c 00 54 00 61 00 67 00 00 00 ||P.o.o.l.T.a.g...||nt!str:PoolTag", 
        "0x804df7fc||43 00 6c 00 65 00 61 00 72 00 50 00 61 00 67 00 ||C.l.e.a.r.P.a.g.||nt!str:ClearPageFileAtShutd", 
        "0x804df80c||65 00 46 00 69 00 6c 00 65 00 41 00 74 00 53 00 ||e.F.i.l.e.A.t.S.|| ", 
        "0x804df81c||68 00 75 00 74 00 64 00 6f 00 77 00 6e 00 00 00 ||h.u.t.d.o.w.n...|| ", 
        "0x804df82c||53 00 65 00 63 00 6f 00 6e 00 64 00 4c 00 65 00 ||S.e.c.o.n.d.L.e.||nt!str:SecondLevelDataCache", 
        "0x804df83c||76 00 65 00 6c 00 44 00 61 00 74 00 61 00 43 00 ||v.e.l.D.a.t.a.C.|| ", 
        "0x804df84c||61 00 63 00 68 00 65 00 00 00 00 00 4d 00 6f 00 ||a.c.h.e.....M.o.|| "
    ], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "--cache_dir": "/home/scudette/projects/rekall-test/tigger/../profile_cache/", 
        "commandline": "dump \"nt!str:PoolTag\" --length=100", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestDump", 
        "tempdir": "/tmp/tmplTZKeI/TestDumpThread-2", 
        "executed_command": "rekall  --renderer 'test' --cache_dir '/home/scudette/projects/rekall-test/tigger/../profile_cache/' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - dump \"nt!str:PoolTag\" --length=100", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}