#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestCallbacks /home/scudette/projects/rekall-test/tigger/TestCallbacks
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestCallbacks /home/scudette/projects/rekall-test/tigger/TestCallbacks
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestCallbacks /home/scudette/projects/rekall-test/tigger/TestCallbacks
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - callbacks
else
   less /home/scudette/projects/rekall-test/tigger/output/TestCallbacks
fi
exit 0
{
    "errors": {}, 
    "time_used": 2.3866348266601562, 
    "return_code": 0, 
    "failures": {
        "testCase (__main__.TestCallbacks)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 227, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 277, in testCase\n    self.assertEqual(previous, current)\nAssertionError: 29 != 11\n"
    }, 
    "output": [
        "                Type                ||  Offset  || Callback ||                      Symbol                      ||Details", 
        "------------------------------------||----------||----------||--------------------------------------------------||-------", 
        "nt!PspCreateProcessNotifyRoutine    ||0x805593e0||0x00000000||                                                  ", 
        "nt!KeBugCheckCallbackListHead       ||0x80fa35d8||0x00000048||                                                  ||-      ", 
        "nt!KeBugCheckCallbackListHead       ||0x806dff40||0x00000000||                                                  ||-      ", 
        "nt!KeBugCheckReasonCallbackListHead ||0xfc968a80||0xf92cf5e6||                                                  ||       ", 
        "nt!KeBugCheckReasonCallbackListHead ||0xfc968a60||0xf92cf58e||                                                  ||       ", 
        "nt!KeBugCheckReasonCallbackListHead ||0xfc968aa0||0xf92cf536||                                                  ||       ", 
        "nt!KeBugCheckReasonCallbackListHead ||0x80ef6180||0xf81a9ee8||                                                  ||       ", 
        "nt!KeBugCheckReasonCallbackListHead ||0x80fa73a8||0xf81a9e48||                                                  ||       ", 
        "nt!KeBugCheckReasonCallbackListHead ||0xfc0ed9e0||0xf81e14b4||                                                  ||       "
    ], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "callbacks", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestCallbacks", 
        "tempdir": "/tmp/tmpgj4t19/TestCallbacksThread-3", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - callbacks", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}