#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestGrep /home/scudette/projects/rekall-test/tigger/TestGrep
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestGrep /home/scudette/projects/rekall-test/tigger/TestGrep
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestGrep /home/scudette/projects/rekall-test/tigger/TestGrep
elif [ "$1" == "run" ]; then
   rekall  --cache_dir '/home/scudette/projects/rekall-test/tigger/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - grep explorer.exe --offset 4281886160
else
   less /home/scudette/projects/rekall-test/tigger/output/TestGrep
fi
exit 0
{
    "errors": {}, 
    "logging": "", 
    "time_used": 1.2624549865722656, 
    "return_code": 0, 
    "failures": {
        "testCase (rekall.plugins.core_test.TestGrep)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 235, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 285, in testCase\n    self.assertEqual(previous, current)\nAssertionError: 4 != 5\n"
    }, 
    "output": [
        "  Offset  ||                              Data                               ||                Comment                 ", 
        "----------||-----------------------------------------------------------------||----------------------------------------", 
        "0xff386734||30 67 38 ff 00 00 00 00 00 00 00 00 00 d0 9b fc ||0g8.............|| ", 
        "0xff386744||65 78 70 6c 6f 72 65 72 2e 65 78 65 00 00 00 00 ||explorer.exe....|| ", 
        "0xff386754||00 00 00 00 00 00 00 00 00 00 00 00 d4 7f 24 ff ||..............$.|| "
    ], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "keyword": "explorer.exe", 
        "--format": "test", 
        "commandline": "grep %(keyword)s --offset %(offset)s", 
        "pid": 1724, 
        "test_class": "TestGrep", 
        "--cache_dir": "/home/scudette/projects/rekall-test/tigger/../profile_cache/", 
        "offset": 4281886160, 
        "tempdir": "/tmp/tmpwXsnn1/TestGrepThread-1", 
        "executed_command": "rekall  --cache_dir '/home/scudette/projects/rekall-test/tigger/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - grep explorer.exe --offset 4281886160", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}