#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestCallbacks /home/scudette/projects/rekall-test/tigger/TestCallbacks
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestCallbacks /home/scudette/projects/rekall-test/tigger/TestCallbacks
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestCallbacks /home/scudette/projects/rekall-test/tigger/TestCallbacks
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - callbacks
else
   less /home/scudette/projects/rekall-test/tigger/output/TestCallbacks
fi
exit 0
{
    "errors": {}, 
    "time_used": 6.6766111850738525, 
    "return_code": 0, 
    "failures": {
        "testCase (__main__.TestCallbacks)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 227, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 277, in testCase\n    self.assertEqual(previous, current)\nAssertionError: u'KeBugCheckCallbackListHead          ||0x00000000||UNKNOWN             ||-      [truncated]... != u'KeBugCheckCallbackListHead          ||0x00000000||UNKNOWN             ||       [truncated]...\n- KeBugCheckCallbackListHead          ||0x00000000||UNKNOWN             ||-      \n?                                                                         ^\n+ KeBugCheckCallbackListHead          ||0x00000000||UNKNOWN             ||       \n?                                                                         ^\n\n"
    }, 
    "output": [
        "                Type                || Callback ||       Module       ||Details", 
        "------------------------------------||----------||--------------------||-------", 
        "GenericKernelCallback               ||0xfc58e194||vmci.sys            ||-      ", 
        "IoRegisterShutdownNotification      ||0xfc9af5be||Fs_Rec.SYS          ||\\FileSystem\\Fs_Rec", 
        "IoRegisterShutdownNotification      ||0xfc9af5be||Fs_Rec.SYS          ||\\FileSystem\\Fs_Rec", 
        "IoRegisterShutdownNotification      ||0xf3b457fa||vmhgfs.sys          ||\\FileSystem\\vmhgfs", 
        "IoRegisterShutdownNotification      ||0xfc0f765c||VIDEOPRT.SYS        ||\\Driver\\mnmdd", 
        "IoRegisterShutdownNotification      ||0xfc0f765c||VIDEOPRT.SYS        ||\\Driver\\VgaSave", 
        "IoRegisterShutdownNotification      ||0xfc6bec74||Cdfs.SYS            ||\\FileSystem\\Cdfs", 
        "IoRegisterShutdownNotification      ||0xfc9af5be||Fs_Rec.SYS          ||\\FileSystem\\Fs_Rec", 
        "IoRegisterShutdownNotification      ||0xfc9af5be||Fs_Rec.SYS          ||\\FileSystem\\Fs_Rec", 
        "IoRegisterShutdownNotification      ||0xfc9af5be||Fs_Rec.SYS          ||\\FileSystem\\Fs_Rec", 
        "IoRegisterShutdownNotification      ||0xfc0f765c||VIDEOPRT.SYS        ||\\Driver\\vmx_svga", 
        "IoRegisterShutdownNotification      ||0xfc0f765c||VIDEOPRT.SYS        ||\\Driver\\RDPCDD", 
        "IoRegisterShutdownNotification      ||0xfc33d2be||ftdisk.sys          ||\\Driver\\Ftdisk", 
        "IoRegisterShutdownNotification      ||0xfc1db33d||Mup.sys             ||\\FileSystem\\Mup", 
        "IoRegisterShutdownNotification      ||0x805f4630||ntoskrnl.exe        ||\\Driver\\WMIxWDM", 
        "IoRegisterShutdownNotification      ||0x805cc77c||ntoskrnl.exe        ||\\FileSystem\\RAW", 
        "IoRegisterShutdownNotification      ||0xfc4ab73a||MountMgr.sys        ||\\Driver\\MountMgr", 
        "IoRegisterFsRegistrationChange      ||0xfc2c0876||sr.sys              ||-      ", 
        "KeBugCheckCallbackListHead          ||0x806d57ca||hal.dll             ||ACPI 1.0 - APIC platform UP", 
        "KeBugCheckCallbackListHead          ||0x00000000||UNKNOWN             ||       ", 
        "KeRegisterBugCheckReasonCallback    ||0xfc967ac0||mssmbios.sys        ||SMBiosDa", 
        "KeRegisterBugCheckReasonCallback    ||0xfc967a78||mssmbios.sys        ||SMBiosRe", 
        "KeRegisterBugCheckReasonCallback    ||0xfc967a30||mssmbios.sys        ||SMBiosDa", 
        "KeRegisterBugCheckReasonCallback    ||0xfc0d5006||USBPORT.SYS         ||USBPORT", 
        "KeRegisterBugCheckReasonCallback    ||0xfc0d4f66||USBPORT.SYS         ||USBPORT", 
        "KeRegisterBugCheckReasonCallback    ||0xfc0eb3e2||VIDEOPRT.SYS        ||       ", 
        "GenericKernelCallback               ||0xfc58e194||vmci.sys            ||-      "
    ], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "callbacks", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestCallbacks", 
        "tempdir": "/tmp/tmpeJxAOQ/TestCallbacksThread-4", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - callbacks", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}