#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /Users/adamsh/Projects/rekall-test/tigger/output/TestUnloadedModules /Users/adamsh/Projects/rekall-test/tigger/TestUnloadedModules
elif [ "$1" == "meld" ]; then
   meld /Users/adamsh/Projects/rekall-test/tigger/output/TestUnloadedModules /Users/adamsh/Projects/rekall-test/tigger/TestUnloadedModules
elif [ "$1" == "diff" ]; then
   diff /Users/adamsh/Projects/rekall-test/tigger/output/TestUnloadedModules /Users/adamsh/Projects/rekall-test/tigger/TestUnloadedModules
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - unloaded_modules
else
   less /Users/adamsh/Projects/rekall-test/tigger/output/TestUnloadedModules
fi
exit 0
{
    "time_used": 3.455718994140625, 
    "output": [
        "        Name        ||  Start   ||   End    ||Time", 
        "--------------------||----------||----------||----", 
        "Sfloppy.SYS         ||0xfc178000||0xfc17b000||2010-08-11 06:06:17+0000", 
        "Cdaudio.SYS         ||0xfc7b3000||0xfc7b8000||2010-08-11 06:06:17+0000", 
        "vmdebug.sys         ||0xfc66b000||0xfc674000||2010-08-11 06:06:47+0000", 
        "splitter.sys        ||0xfc9cd000||0xfc9cf000||2010-08-11 06:07:39+0000", 
        "aec.sys             ||0xf3124000||0xf3147000||2010-08-11 06:07:44+0000", 
        "swmidi.sys          ||0xf377d000||0xf378b000||2010-08-11 06:07:44+0000", 
        "DMusic.sys          ||0xf323c000||0xf3249000||2010-08-11 06:07:44+0000", 
        "kmixer.sys          ||0xf30fa000||0xf3124000||2010-08-11 06:07:44+0000", 
        "drmkaud.sys         ||0xfcab8000||0xfcab9000||2010-08-11 06:07:44+0000", 
        "kmixer.sys          ||0xf2fe0000||0xf300a000||2010-08-15 19:26:22+0000"
    ], 
    "errors": {}, 
    "return_code": 0, 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "unloaded_modules", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestUnloadedModules", 
        "tempdir": "/var/folders/yc/4zng19655k37kyxgskb3vvf0006t70/T/tmpYULHcC/TestUnloadedModulesThread-6", 
        "executed_command": "rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - unloaded_modules", 
        "testdir": "/Users/adamsh/Projects/rekall-test/tigger"
    }
}