#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /Users/adamsh/Projects/rekall-test/tigger/output/TestPSTree /Users/adamsh/Projects/rekall-test/tigger/TestPSTree
elif [ "$1" == "meld" ]; then
   meld /Users/adamsh/Projects/rekall-test/tigger/output/TestPSTree /Users/adamsh/Projects/rekall-test/tigger/TestPSTree
elif [ "$1" == "diff" ]; then
   diff /Users/adamsh/Projects/rekall-test/tigger/output/TestPSTree /Users/adamsh/Projects/rekall-test/tigger/TestPSTree
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - pstree
else
   less /Users/adamsh/Projects/rekall-test/tigger/output/TestPSTree
fi
exit 0
{
    "time_used": 4.914422988891602, 
    "output": [
        "_EPROCESS                               || PPid || Thds || Hnds ||          Time          ", 
        "----------------------------------------||------||------||------||------------------------", 
        " ||0x810b1660 System (4)                 ||0     ||61    ||179   ||-                       ", 
        ".||0xff2ab020 smss.exe (544)             ||4     ||3     ||21    ||2010-08-11 06:06:21+0000", 
        "..||0xff1ecda0 csrss.exe (608)           ||544   ||10    ||405   ||2010-08-11 06:06:23+0000", 
        "..||0xff1ec978 winlogon.exe (632)        ||544   ||22    ||519   ||2010-08-11 06:06:23+0000", 
        "...||0xff247020 services.exe (676)       ||632   ||16    ||269   ||2010-08-11 06:06:24+0000", 
        "....||0xff25a7e0 alg.exe (216)           ||676   ||7     ||108   ||2010-08-11 06:06:39+0000", 
        "....||0xff218230 vmacthlp.exe (844)      ||676   ||1     ||24    ||2010-08-11 06:06:24+0000", 
        "....||0x80ff88d8 svchost.exe (856)       ||676   ||18    ||202   ||2010-08-11 06:06:24+0000", 
        ".....||0xff27d4d0 wmiprvse.exe (828)     ||856   ||9     ||214   ||2010-08-15 19:26:08+0000", 
        "....||0xff217560 svchost.exe (936)       ||676   ||9     ||270   ||2010-08-11 06:06:24+0000", 
        "....||0x80fbf910 svchost.exe (1028)      ||676   ||88    ||1395  ||2010-08-11 06:06:24+0000", 
        ".....||0x80f94588 wuauclt.exe (468)      ||1028  ||4     ||131   ||2010-08-11 06:09:37+0000", 
        ".....||0xff364310 wscntfy.exe (888)      ||1028  ||1     ||27    ||2010-08-11 06:06:49+0000", 
        ".....||0x80f60da0 wuauclt.exe (1732)     ||1028  ||7     ||178   ||2010-08-11 06:07:44+0000", 
        "....||0xff22d558 svchost.exe (1088)      ||676   ||7     ||80    ||2010-08-11 06:06:25+0000", 
        "....||0xff203b80 svchost.exe (1148)      ||676   ||15    ||210   ||2010-08-11 06:06:26+0000", 
        "....||0xff1d7da0 spoolsv.exe (1432)      ||676   ||14    ||137   ||2010-08-11 06:06:26+0000", 
        "....||0xff1b8b28 vmtoolsd.exe (1668)     ||676   ||5     ||218   ||2010-08-11 06:06:35+0000", 
        "....||0xff1fdc88 VMUpgradeHelper (1788)  ||676   ||5     ||100   ||2010-08-11 06:06:38+0000", 
        "....||0xff143b28 TPAutoConnSvc.e (1968)  ||676   ||5     ||100   ||2010-08-11 06:06:39+0000", 
        ".....||0xff38b5f8 TPAutoConnect.e (1084) ||1968  ||1     ||61    ||2010-08-11 06:06:52+0000", 
        "...||0xff255020 lsass.exe (688)          ||632   ||21    ||348   ||2010-08-11 06:06:24+0000", 
        " ||0xff3865d0 explorer.exe (1724)        ||1708  ||13    ||314   ||2010-08-11 06:09:29+0000", 
        ".||0xff3667e8 VMwareTray.exe (432)       ||1724  ||1     ||49    ||2010-08-11 06:09:31+0000", 
        ".||0xff374980 VMwareUser.exe (452)       ||1724  ||8     ||204   ||2010-08-11 06:09:32+0000"
    ], 
    "errors": {}, 
    "return_code": 0, 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "pstree", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestPSTree", 
        "tempdir": "/var/folders/yc/4zng19655k37kyxgskb3vvf0006t70/T/tmpEPJPAD/TestPSTreeThread-2", 
        "executed_command": "rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - pstree", 
        "testdir": "/Users/adamsh/Projects/rekall-test/tigger"
    }
}