#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /Users/adamsh/Projects/rekall-test/tigger/output/TestVmScan /Users/adamsh/Projects/rekall-test/tigger/TestVmScan
elif [ "$1" == "meld" ]; then
   meld /Users/adamsh/Projects/rekall-test/tigger/output/TestVmScan /Users/adamsh/Projects/rekall-test/tigger/TestVmScan
elif [ "$1" == "diff" ]; then
   diff /Users/adamsh/Projects/rekall-test/tigger/output/TestVmScan /Users/adamsh/Projects/rekall-test/tigger/TestVmScan
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - vmscan
else
   less /Users/adamsh/Projects/rekall-test/tigger/output/TestVmScan
fi
exit 0
{
    "time_used": 5.525238037109375, 
    "output": [
        "Description                             ||        Type        || Valid  ||EPT", 
        "----------------------------------------||--------------------||--------||---"
    ], 
    "errors": {}, 
    "return_code": 0, 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "vmscan", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestVmScan", 
        "tempdir": "/var/folders/yc/4zng19655k37kyxgskb3vvf0006t70/T/tmpHPq5l9/TestVmScanThread-6", 
        "executed_command": "rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - vmscan", 
        "testdir": "/Users/adamsh/Projects/rekall-test/tigger"
    }
}