#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /Users/adamsh/Projects/rekall-test/tigger/output/TestPools /Users/adamsh/Projects/rekall-test/tigger/TestPools
elif [ "$1" == "meld" ]; then
   meld /Users/adamsh/Projects/rekall-test/tigger/output/TestPools /Users/adamsh/Projects/rekall-test/tigger/TestPools
elif [ "$1" == "diff" ]; then
   diff /Users/adamsh/Projects/rekall-test/tigger/output/TestPools /Users/adamsh/Projects/rekall-test/tigger/TestPools
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - pools
else
   less /Users/adamsh/Projects/rekall-test/tigger/output/TestPools
fi
exit 0
{
    "time_used": 5.498932123184204, 
    "output": [
        "        Type        ||Index||   Size   ||  Start   ||   End    ||Comment", 
        "--------------------||-----||----------||----------||----------||-------", 
        "NonPagedPool        ||0    ||2588672   ||0x80ee1000||0x840cd000||       ", 
        "PagedPool           ||0    ||0         ||0xe1000000||0xe7400000||       ", 
        "PagedPool           ||1    ||4145152   ||0xe1000000||0xe7400000||       ", 
        "PagedPool           ||2    ||925696    ||0xe1000000||0xe7400000||       ", 
        "PagedPoolSession    ||0    ||0         ||0xbc000000||0xbc3fffff||Session ID 0"
    ], 
    "errors": {}, 
    "return_code": 0, 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "pools", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestPools", 
        "tempdir": "/var/folders/yc/4zng19655k37kyxgskb3vvf0006t70/T/tmplr9jKT/TestPoolsThread-8", 
        "executed_command": "rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - pools", 
        "testdir": "/Users/adamsh/Projects/rekall-test/tigger"
    }
}