#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /Users/adamsh/Projects/rekall-test/tigger/output/TestPas2Vas /Users/adamsh/Projects/rekall-test/tigger/TestPas2Vas
elif [ "$1" == "meld" ]; then
   meld /Users/adamsh/Projects/rekall-test/tigger/output/TestPas2Vas /Users/adamsh/Projects/rekall-test/tigger/TestPas2Vas
elif [ "$1" == "diff" ]; then
   diff /Users/adamsh/Projects/rekall-test/tigger/output/TestPas2Vas /Users/adamsh/Projects/rekall-test/tigger/TestPas2Vas
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - pas2vas 77620688 --pid 0 
else
   less /Users/adamsh/Projects/rekall-test/tigger/output/TestPas2Vas
fi
exit 0
{
    "time_used": 4.476353883743286, 
    "output": [
        " Physical || Virtual  || Pid  ||Name", 
        "----------||----------||------||----", 
        "0x04a065d0||0xff3865d0||0     ||Kernel"
    ], 
    "errors": {}, 
    "return_code": 0, 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "pas2vas %(offset)s --pid 0 ", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestPas2Vas", 
        "offset": 77620688, 
        "tempdir": "/var/folders/yc/4zng19655k37kyxgskb3vvf0006t70/T/tmpezmpxE/TestPas2VasThread-4", 
        "executed_command": "rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - pas2vas 77620688 --pid 0 ", 
        "testdir": "/Users/adamsh/Projects/rekall-test/tigger"
    }
}