#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /Users/adamsh/Projects/rekall-test/tigger/output/TestImageInfo /Users/adamsh/Projects/rekall-test/tigger/TestImageInfo
elif [ "$1" == "meld" ]; then
   meld /Users/adamsh/Projects/rekall-test/tigger/output/TestImageInfo /Users/adamsh/Projects/rekall-test/tigger/TestImageInfo
elif [ "$1" == "diff" ]; then
   diff /Users/adamsh/Projects/rekall-test/tigger/output/TestImageInfo /Users/adamsh/Projects/rekall-test/tigger/TestImageInfo
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - imageinfo
else
   less /Users/adamsh/Projects/rekall-test/tigger/output/TestImageInfo
fi
exit 0
{
    "time_used": 4.4558939933776855, 
    "output": [
        "        Fact        ||            Value             ", 
        "--------------------||------------------------------", 
        "Kernel DTB          ||0x319000                      ", 
        "NT Build            ||2600.xpsp_sp2_rtm.040803-2158 ", 
        "NT Build Ex         ||-                             ", 
        "Signed Drivers      ||-                             ", 
        "Time (UTC)          ||2010-08-15 19:26:50+0000      ", 
        "Time (Local)        ||2010-08-15 23:26:50+0000      ", 
        "Sec Since Boot      ||371.90625                     ", 
        "NtSystemRoot        ||C:\\WINDOWS                    ", 
        "", 
        "**************** Physical Layout ****************", 
        "Phys Start|| Phys End ||Number of Pages", 
        "----------||----------||---------------", 
        "0x00001000||0x0009f000||158            ", 
        "0x00100000||0x00fff000||3839           ", 
        "0x01000000||0x07ef0000||28400          ", 
        "0x07f00000||0x08000000||256            "
    ], 
    "errors": {}, 
    "return_code": 0, 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "imageinfo", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestImageInfo", 
        "tempdir": "/var/folders/yc/4zng19655k37kyxgskb3vvf0006t70/T/tmpYULHcC/TestImageInfoThread-5", 
        "executed_command": "rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - imageinfo", 
        "testdir": "/Users/adamsh/Projects/rekall-test/tigger"
    }
}