#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestConsoleScan /home/scudette/projects/rekall-test/tigger/TestConsoleScan
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestConsoleScan /home/scudette/projects/rekall-test/tigger/TestConsoleScan
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestConsoleScan /home/scudette/projects/rekall-test/tigger/TestConsoleScan
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - consolescan
else
   less /home/scudette/projects/rekall-test/tigger/output/TestConsoleScan
fi
exit 0
{
    "errors": {}, 
    "time_used": 4.456582069396973, 
    "return_code": 0, 
    "failures": {
        "testCase (__main__.TestConsoleScan)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 227, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 277, in testCase\n    self.assertEqual(previous, current)\nAssertionError: u'Console:   0x4e23b0 CommandHistorySize: 50' != u'Console: 0x4e23b0 CommandHistorySize: 50'\n- Console:   0x4e23b0 CommandHistorySize: 50\n?          --\n+ Console: 0x4e23b0 CommandHistorySize: 50\n\n"
    }, 
    "output": [
        "**************************************************", 
        "ConsoleProcess: csrss.exe Pid: 608", 
        "Console: 0x4e23b0 CommandHistorySize: 50", 
        "HistoryBufferCount: 1 HistoryBufferMax: 4", 
        "OriginalTitle: C:\\Program Files\\VMware\\VMware Tools\\TPAutoConnSvc.exe", 
        "Title: C:\\Program Files\\VMware\\VMware Tools\\TPAutoConnSvc.exe", 
        "AttachedProcess: TPAutoConnect.e Pid: 1084 Handle: 0x448", 
        "----", 
        "CommandHistory: 0xf786f8 Application: TPAutoConnect.exe Flags: Allocated", 
        "CommandCount: 0 LastAdded: -1 LastDisplayed: -1", 
        "FirstCommand: 0 CommandCountMax: 50", 
        "ProcessHandle: 0x448", 
        "----", 
        "Screen 0x4e2ab0 X:80 Y:25", 
        "Dump:", 
        "TPAutoConnect User Agent, Copyright (c) 1999-2009 ThinPrint AG, 7.17.512.1      ", 
        "**************************************************", 
        "ConsoleProcess: csrss.exe Pid: 608", 
        "Console: 0xf78958 CommandHistorySize: 50", 
        "HistoryBufferCount: 2 HistoryBufferMax: 4", 
        "OriginalTitle: \u8910\u00f7ystemRoot%\\system32\\cmd.exe", 
        "Title: "
    ], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "consolescan", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestConsoleScan", 
        "tempdir": "/tmp/tmpZjUbTN/TestConsoleScanThread-1", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - consolescan", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}