#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestPtoV /home/scudette/projects/rekall-test/tigger/TestPtoV
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestPtoV /home/scudette/projects/rekall-test/tigger/TestPtoV
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestPtoV /home/scudette/projects/rekall-test/tigger/TestPtoV
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - ptov 0x115b8d8
else
   less /home/scudette/projects/rekall-test/tigger/output/TestPtoV
fi
exit 0
{
    "time_used": 0.9402461051940918, 
    "output": [
        "Physical Address 0x115b8d8 => Virtual Address 0x80ff88d8", 
        "DTB @ 0x31d000", 
        "PDPTE @ 0x31d010", 
        "PDE @ 0x31c038", 
        "PTE @ 0x1244fc0"
    ], 
    "errors": {}, 
    "return_code": 0, 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "ptov 0x115b8d8", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestPtoV", 
        "tempdir": "/tmp/tmpXcquK0/TestPtoVThread-1", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - ptov 0x115b8d8", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}