#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestDump /home/scudette/projects/rekall-test/tigger/TestDump
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestDump /home/scudette/projects/rekall-test/tigger/TestDump
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestDump /home/scudette/projects/rekall-test/tigger/TestDump
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --cache_dir '/home/scudette/projects/rekall-test/tigger/../profile_cache/' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - dump 0xff3865d0
else
   less /home/scudette/projects/rekall-test/tigger/output/TestDump
fi
exit 0
{
    "errors": {}, 
    "time_used": 2.4910688400268555, 
    "return_code": 0, 
    "failures": {
        "testCase (__main__.TestDump)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 227, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 277, in testCase\n    self.assertEqual(previous, current)\nAssertionError: 47 != 48\n"
    }, 
    "output": [
        "  Offset  ||                              Data                               ||                Comment                 ", 
        "----------||-----------------------------------------------------------------||----------------------------------------", 
        "0xff3865d0||03 00 1b 00 00 00 00 00 d8 65 38 ff d8 65 38 ff ||.........e8..e8.|| ", 
        "0xff3865e0||e0 65 38 ff e0 65 38 ff 80 02 cc 06 3c 2c 00 00 ||.e8..e8.....<,..|| ", 
        "0xff3865f0||00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ||................|| ", 
        "0xff386600||ac 20 00 00 00 00 00 00 2d 00 00 00 0e 00 00 00 ||........-.......|| ", 
        "0xff386610||10 66 38 ff 10 66 38 ff 00 00 00 00 00 00 00 00 ||.f8..f8.........|| ", 
        "0xff386620||58 7f 24 ff c0 9c 1f ff 00 00 00 00 01 00 00 00 ||X.$.............|| ", 
        "0xff386630||09 00 08 12 00 00 00 00 00 00 00 00 00 00 00 00 ||................|| ", 
        "0xff386640||78 8c ea c1 1b 39 cb 01 00 00 00 00 00 00 00 00 ||x....9..........|| ", 
        "0xff386650||00 00 00 00 bc 06 00 00 70 68 36 ff 28 0e f6 80 ||........ph6.(...|| ", 
        "0xff386660||98 26 00 00 ac 8f 01 00 dc 07 00 00 30 2d 00 00 ||.&..........0-..|| ", 
        "0xff386670||ec b5 01 00 f0 07 00 00 dc 07 00 00 00 80 a8 03 ||................|| ", 
        "0xff386680||00 00 7e 03 9c 68 36 ff 54 0e f6 80 00 00 00 00 ||..~..h6.T.......|| ", 
        "0xff386690||30 60 70 e1 f8 4d 0a e1 31 00 07 e1 01 00 00 00 ||0`p..M..1.......|| ", 
        "0xff3866a0||70 c7 32 f3 01 00 00 00 01 00 04 00 00 00 00 00 ||p.2.............|| ", 
        "0xff3866b0||b0 66 38 ff b0 66 38 ff 3d 00 00 00 7e 61 00 00 ||.f8..f8.=...~a..|| ", 
        "0xff3866c0||01 00 00 00 70 c7 32 f3 01 00 00 00 01 00 04 00 ||....p.2.........|| ", 
        "0xff3866d0||00 00 00 00 d4 66 38 ff d4 66 38 ff 00 00 00 00 ||.....f8..f8.....|| ", 
        "0xff3866e0||00 00 00 00 00 00 00 00 00 00 00 00 a8 01 37 ff ||..............7.|| ", 
        "0xff3866f0||a8 01 37 ff 00 00 00 00 68 05 00 00 00 00 00 00 ||..7.....h.......|| ", 
        "0xff386700||b8 f1 69 e1 00 00 00 00 d0 e9 db e1 00 00 00 01 ||..i.............|| ", 
        "0xff386710||30 ec f2 80 00 00 00 00 30 00 00 00 ac 06 00 00 ||0.......0.......|| ", 
        "0xff386720||00 00 00 00 00 00 00 00 00 00 00 00 60 97 dd e1 ||............`...|| ", 
        "0xff386730||30 67 38 ff 30 67 38 ff 00 00 00 00 00 00 00 00 ||0g8.0g8.........|| ", 
        "0xff386740||00 d0 9b fc 65 78 70 6c 6f 72 65 72 2e 65 78 65 ||....explorer.exe|| ", 
        "0xff386750||00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ||................|| ", 
        "0xff386760||d4 7f 24 ff 3c 9d 1f ff 00 00 00 00 80 52 ae fc ||..$.<........R..|| ", 
        "0xff386770||0d 00 00 00 ff 0f 1f 00 00 00 00 00 00 00 00 00 ||................|| ", 
        "0xff386780||00 a0 fd 7f 00 00 00 00 45 01 00 00 00 00 00 00 ||........E.......|| ", 
        "0xff386790||0e 00 00 00 00 00 00 00 c0 10 00 00 00 00 00 00 ||................|| ", 
        "0xff3867a0||c0 11 24 00 00 00 00 00 0c 04 00 00 00 00 00 00 ||..$.............|| ", 
        "0xff3867b0||72 9e 03 00 00 00 00 00 00 00 00 00 f0 07 00 00 ||r...............|| ", 
        "0xff3867c0||00 00 00 00 28 1e 16 ff 4c c6 e5 c1 1b 39 cb 01 ||....(...L....9..|| ", 
        "0xff3867d0||00 00 01 02 ae 10 00 00 61 0c 00 00 5f 0c 00 00 ||........a..._...|| ", 
        "0xff3867e0||32 00 00 00 59 01 00 00 00 30 88 c0 04 6a 36 ff ||2...Y....0...j6.|| ", 
        "0xff3867f0||74 d7 22 ff 20 05 00 00 53 0c 00 00 6d 00 00 00 ||t.\".....S...m...|| ", 
        "0xff386800||20 05 00 00 08 00 00 00 00 00 00 00 a5 00 00 00 ||................|| ", 
        "0xff386810||cd 00 00 00 00 00 00 00 00 08 0d 00 03 01 00 00 ||................|| ", 
        "0xff386820||2f 04 0a 04 02 00 00 00 a7 b9 16 c3 00 00 00 00 ||/...............|| ", 
        "0xff386830||50 00 05 0a 46 53 66 6d 01 00 00 00 14 a4 93 fc ||P...FSfm........|| ", 
        "0xff386840||00 00 00 00 01 00 04 00 00 00 00 00 4c 68 38 ff ||............Lh8.|| ", 
        "0xff386850||4c 68 38 ff 3d 00 00 00 05 00 02 00 4e 74 66 49 ||Lh8.=.......NtfI|| ", 
        "0xff386860||e0 00 36 ff f8 e5 37 ff 02 00 1b 0a 4d 6d 43 69 ||..6...7.....MmCi|| ", 
        "0xff386870||e8 a7 6d e1 00 00 00 00 00 00 00 00 00 00 00 00 ||..m.............|| ", 
        "0xff386880||04 00 00 00 07 00 00 00 05 00 00 00 07 00 00 00 ||................|| ", 
        "0xff386890||a0 00 00 09 18 0b 38 ff 00 00 00 00 00 00 00 00 ||......8.........|| ", 
        "0xff3868a0||70 68 38 ff 11 00 00 00 00 00 00 00 02 00 00 00 ||ph8.............|| "
    ], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "--cache_dir": "/home/scudette/projects/rekall-test/tigger/../profile_cache/", 
        "commandline": "dump 0xff3865d0", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestDump", 
        "tempdir": "/tmp/tmprjYpsY/TestDumpThread-2", 
        "executed_command": "rekall  --renderer 'test' --cache_dir '/home/scudette/projects/rekall-test/tigger/../profile_cache/' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - dump 0xff3865d0", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}