#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestVtoP /home/scudette/projects/rekall-test/tigger/TestVtoP
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestVtoP /home/scudette/projects/rekall-test/tigger/TestVtoP
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestVtoP /home/scudette/projects/rekall-test/tigger/TestVtoP
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --cache_dir '/home/scudette/projects/rekall-test/tigger/../profile_cache/' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - vtop --pid 1724 - 1953792
else
   less /home/scudette/projects/rekall-test/tigger/output/TestVtoP
fi
exit 0
{
    "errors": {}, 
    "time_used": 7.260253190994263, 
    "return_code": 0, 
    "failures": {
        "testCase (rekall.plugins.windows.pfn_test.TestVtoP)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 233, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 283, in testCase\n    self.assertEqual(previous, current)\nAssertionError: 43 != 34\n"
    }, 
    "output": [
        "", 
        "******************** 0x1dd000 ********************", 
        "Virtual 0x001dd000 Page Directory 0x6cc0280", 
        "pdpte@ 0x6cc0280 = 0x4339001", 
        "pde@ 0x4339000 = 0x32ab067", 
        "pte@ 0x32abee8 = 0x0", 
        "", 
        "PTE Contains 0x0", 
        "PTE Type: Vad", 
        "", 
        "Prototype PTE is found in VAD", 
        "**************************************************", 
        "Pid: 1724 explorer.exe", 
        "   VAD    ||lev||Start Addr|| End Addr ||com ||-------||------||      Protect       ||Filename", 
        "----------||---||----------||----------||----||       ||      ||--------------------||--------", 
        "0xff23fb80||  8||0x001d0000||0x0020cfff||   0||Mapped ||      ||READONLY            ||\\WINDOWS\\system32\\locale.nls", 
        "", 
        "_MMVAD.FirstPrototypePte: 0xe1674008", 
        "PTE is at 0xe1674070", 
        "", 
        "PTE Contains 0x59418c2", 
        "PTE Type: Transition", 
        "[_MMPTE_TRANSITION Trans] @ 0xE1674070                                              ", 
        "  0x00 CacheDisable     [BitField(4-5):CacheDisable]: 0x00000000                    ", 
        "  0x00 Owner            [BitField(2-3):Owner]: 0x00000000                           ", 
        "  0x00 PageFrameNumber  [BitField(12-38):PageFrameNumber]: 0x00005941               ", 
        "  0x00 Protection       [Enumeration:Enumeration]: 0x00000006 (MM_EXECUTE_READWRITE)", 
        "  0x00 Prototype        [BitField(10-11):Prototype]: 0x00000000                     ", 
        "  0x00 Transition       [BitField(11-12):Transition]: 0x00000001                    ", 
        "  0x00 Unused           [BitField(38-64):Unused]: 0x00000000                        ", 
        "  0x00 Valid            [BitField(0-1):Valid]: 0x00000000                           ", 
        "  0x00 Write            [BitField(1-2):Write]: 0x00000001                           ", 
        "  0x00 WriteThrough     [BitField(3-4):WriteThrough]: 0x00000000                    ", 
        "Physical Address 0x5941000"
    ], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "--cache_dir": "/home/scudette/projects/rekall-test/tigger/../profile_cache/", 
        "commandline": "vtop --pid %(pid)s - %(vaddr)s", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestVtoP", 
        "vaddr": 1953792, 
        "tempdir": "/tmp/tmp5KRedy/TestVtoPThread-3", 
        "executed_command": "rekall  --renderer 'test' --cache_dir '/home/scudette/projects/rekall-test/tigger/../profile_cache/' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - vtop --pid 1724 - 1953792", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}