#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/test_data/tigger/output/TestWinMessageHooks /home/scudette/projects/test_data/tigger/TestWinMessageHooks
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/test_data/tigger/output/TestWinMessageHooks /home/scudette/projects/test_data/tigger/TestWinMessageHooks
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/test_data/tigger/output/TestWinMessageHooks /home/scudette/projects/test_data/tigger/TestWinMessageHooks
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/home/scudette/projects/test_data/tigger/tigger.vmem' --name_resolution_strategies 'Module,Symbol' - messagehooks
else
   less /home/scudette/projects/test_data/tigger/output/TestWinMessageHooks
fi
exit 0
{
    "time_used": 29.17892599105835, 
    "output": [
        "tagHOOK(V)||Sess||       Owner        ||            Thread            ||    Filter     ||  Flags   || Function ||Module", 
        "----------||----||--------------------||------------------------------||---------------||----------||----------||------", 
        "0xbc63a308||0   ||TPAutoConnect.e (1084)||1096 (TPAutoConnect.e 1084)   ||WH_MSGFILTER   ||          ||0x004384f6||\\Program Files\\VMware\\VMware Tools\\TPAutoConnect.exe!+0x384f6", 
        "0xbc63a768||0   ||TPAutoConnect.e (1084)||1096 (TPAutoConnect.e 1084)   ||WH_CBT         ||          ||0x00439684||\\Program Files\\VMware\\VMware Tools\\TPAutoConnect.exe!+0x39684", 
        "0xbc635bb0||0   ||csrss.exe (608)     ||1824 (csrss.exe 608)          ||WH_MSGFILTER   ||          ||0x75b65886||\\WINDOWS\\system32\\winsrv.dll!+0x5886", 
        "0xbc93e670||0   ||TPAutoConnSvc.e (1968)||984 (TPAutoConnSvc.e 1968)    ||WH_MSGFILTER   ||          ||0x004186fc||\\Program Files\\VMware\\VMware Tools\\TPAutoConnSvc.exe!+0x186fc", 
        "0xbc93e410||0   ||TPAutoConnSvc.e (1968)||892 (TPAutoConnSvc.e 1968)    ||WH_MSGFILTER   ||          ||0x004186fc||\\Program Files\\VMware\\VMware Tools\\TPAutoConnSvc.exe!+0x186fc", 
        "0xbc93e060||0   ||TPAutoConnSvc.e (1968)||1972 (TPAutoConnSvc.e 1968)   ||WH_MSGFILTER   ||          ||0x004186fc||\\Program Files\\VMware\\VMware Tools\\TPAutoConnSvc.exe!+0x186fc"
    ], 
    "errors": {}, 
    "return_code": 0, 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/test_data/tigger/tigger.vmem", 
        "commandline": "messagehooks", 
        "pid": "1724", 
        "--renderer": "test", 
        "test_class": "TestWinMessageHooks", 
        "tempdir": "/tmp/tmphC_JwZ/TestWinMessageHooksThread-3", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/test_data/tigger/tigger.vmem' --name_resolution_strategies 'Module,Symbol' - messagehooks", 
        "testdir": "/home/scudette/projects/test_data/tigger"
    }
}