#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestModDump /home/scudette/projects/rekall-test/tigger/TestModDump
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestModDump /home/scudette/projects/rekall-test/tigger/TestModDump
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestModDump /home/scudette/projects/rekall-test/tigger/TestModDump
elif [ "$1" == "run" ]; then
   rekall  -v --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/tigger/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - moddump --regex ntoskrnl.exe --dump_dir /tmp/tmpJFDSSp/TestModDumpThread-1
else
   less /home/scudette/projects/rekall-test/tigger/output/TestModDump
fi
exit 0
{
    "failours": {
        "testCase (rekall.plugins.windows.procdump_test.TestModDump)": {
            "testCase (rekall.plugins.windows.procdump_test.TestModDump)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 300, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 417, in testCase\n    self.assertEqual(self.baseline['hashes'], self.current['hashes'])\nAssertionError: {u'driver.804d7000.sys': u'04e1727a2daedcd450296a2879bea7d5'} != {'driver.804d7000.ntoskrnl.exe': '04e1727a2daedcd450296a2879bea7d5'}\n- {u'driver.804d7000.sys': u'04e1727a2daedcd450296a2879bea7d5'}\n?  -                  ^^   -\n\n+ {'driver.804d7000.ntoskrnl.exe': '04e1727a2daedcd450296a2879bea7d5'}\n?                   +++ ^^^^^^^^\n\n"
        }
    }, 
    "errors": {
        "testCase (rekall.plugins.windows.procdump_test.TestModDump)": {}
    }, 
    "logging": [
        "2016-06-21 17:22:48,047:DEBUG:rekall.1:Logging level set to 10", 
        "2016-06-21 17:22:48,048:DEBUG:rekall.1:Voting round with base: None", 
        "2016-06-21 17:22:48,048:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-06-21 17:22:48,048:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided", 
        "2016-06-21 17:22:48,048:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-06-21 17:22:48,049:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space", 
        "2016-06-21 17:22:48,049:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-06-21 17:22:48,049:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided", 
        "2016-06-21 17:22:48,049:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-06-21 17:22:48,050:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided", 
        "2016-06-21 17:22:48,050:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-06-21 17:22:48,050:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space", 
        "2016-06-21 17:22:48,050:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-06-21 17:22:48,050:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space", 
        "2016-06-21 17:22:48,050:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-06-21 17:22:48,051:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided", 
        "2016-06-21 17:22:48,051:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-06-21 17:22:48,051:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided", 
        "2016-06-21 17:22:48,051:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-06-21 17:22:48,051:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space", 
        "2016-06-21 17:22:48,051:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-06-21 17:22:48,051:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.", 
        "2016-06-21 17:22:48,052:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-06-21 17:22:48,053:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume: No physical memory categories found.", 
        "2016-06-21 17:22:48,053:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-06-21 17:22:48,054:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at /home/scudette/projects/rekall-test/tigger/tigger.vmem.E01_info", 
        "2016-06-21 17:22:48,054:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-06-21 17:22:48,054:DEBUG:rekall.1:Succeeded instantiating FileAddressSpace", 
        "2016-06-21 17:22:48,058:DEBUG:rekall.1:Voting round with base: FileAddressSpace", 
        "2016-06-21 17:22:48,061:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-06-21 17:22:48,064:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x9465645", 
        "2016-06-21 17:22:48,065:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-06-21 17:22:48,065:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-06-21 17:22:48,065:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-06-21 17:22:48,065:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-06-21 17:22:48,065:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-06-21 17:22:48,081:DEBUG:rekall.1:Succeeded instantiating EWFAddressSpace", 
        "2016-06-21 17:22:48,081:DEBUG:rekall.1:Voting round with base: EWFAddressSpace", 
        "2016-06-21 17:22:48,081:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-06-21 17:22:48,095:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0xf000ff53", 
        "2016-06-21 17:22:48,095:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-06-21 17:22:48,096:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-06-21 17:22:48,096:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-06-21 17:22:48,096:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-06-21 17:22:48,096:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-06-21 17:22:48,097:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "2016-06-21 17:22:48,097:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-06-21 17:22:48,097:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "2016-06-21 17:22:48,097:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-06-21 17:22:48,097:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "2016-06-21 17:22:48,098:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-06-21 17:22:48,098:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "2016-06-21 17:22:48,098:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-06-21 17:22:48,098:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "2016-06-21 17:22:48,098:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-06-21 17:22:48,099:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "2016-06-21 17:22:48,099:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-06-21 17:22:48,099:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature", 
        "2016-06-21 17:22:48,100:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-06-21 17:22:48,100:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space", 
        "2016-06-21 17:22:48,100:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-06-21 17:22:48,101:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.", 
        "2016-06-21 17:22:48,101:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-06-21 17:22:48,101:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space", 
        "2016-06-21 17:22:48,101:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> ", 
        "2016-06-21 17:22:48,101:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space", 
        "2016-06-21 17:22:48,101:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> ", 
        "2016-06-21 17:22:48,103:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified", 
        "2016-06-21 17:22:48,103:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> ", 
        "2016-06-21 17:22:48,103:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.", 
        "2016-06-21 17:22:48,103:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> ", 
        "2016-06-21 17:22:48,103:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified", 
        "2016-06-21 17:22:48,104:INFO:rekall.1:Autodetected physical address space EWFAddressSpace", 
        "2016-06-21 17:22:48,104:DEBUG:rekall.1:Will detect profile using these Detectors: linux_index,nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux", 
        "2016-06-21 17:22:48,663:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master//v1.0/inventory.gz", 
        "2016-06-21 17:22:48,785:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/inventory.gz", 
        "2016-06-21 17:22:48,786:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-profiles/v1.0/inventory.gz", 
        "2016-06-21 17:22:48,805:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/inventory.gz", 
        "2016-06-21 17:22:48,806:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/Linux/index.gz", 
        "2016-06-21 17:22:48,821:INFO:rekall.1:Loaded profile Linux/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0157401561737 sec)", 
        "2016-06-21 17:22:48,822:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/eprocess_index.gz", 
        "2016-06-21 17:22:48,881:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0590000152588 sec)", 
        "2016-06-21 17:22:48,881:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/index.gz", 
        "2016-06-21 17:22:49,038:INFO:rekall.1:Loaded profile nt/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.156383991241 sec)", 
        "2016-06-21 17:22:49,038:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/OSX/index.gz", 
        "2016-06-21 17:22:49,039:INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.000923871994019 sec)", 
        "2016-06-21 17:22:49,040:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/pe.gz", 
        "2016-06-21 17:22:49,057:INFO:rekall.1:Loaded profile pe from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0180549621582 sec)", 
        "2016-06-21 17:22:49,058:DEBUG:rekall.1:Trying method pe, offset 0", 
        "2016-06-21 17:22:49,061:DEBUG:rekall.1:Trying method windows_kernel_file, offset 0", 
        "2016-06-21 17:22:49,061:DEBUG:rekall.1:Trying method rsds, offset 0", 
        "2016-06-21 17:22:49,067:DEBUG:rekall.1:Trying method linux_index, offset 0", 
        "2016-06-21 17:22:49,067:DEBUG:rekall.1:LinuxIndexDetector:DetectFromHit(0) = None", 
        "2016-06-21 17:22:49,067:DEBUG:rekall.1:Trying method nt_index, offset 0", 
        "2016-06-21 17:22:49,067:DEBUG:rekall.1:Trying method ntfs, offset 0", 
        "2016-06-21 17:22:49,068:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/ntfs.gz", 
        "2016-06-21 17:22:49,070:INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0025360584259 sec)", 
        "2016-06-21 17:22:49,626:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/GUID/BD8F451F3E754ED8A34B50560CEB08E31.gz", 
        "2016-06-21 17:22:49,807:INFO:rekall.1:Loaded profile nt/GUID/BD8F451F3E754ED8A34B50560CEB08E31 from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.181058883667 sec)", 
        "2016-06-21 17:22:49,988:DEBUG:rekall.1:Found _EPROCESS @ 0x551B80 (DTB: 0x319000)", 
        "2016-06-21 17:22:50,118:INFO:rekall.1:Detected ntkrnlpa.pdb with GUID BD8F451F3E754ED8A34B50560CEB08E31", 
        "2016-06-21 17:22:50,118:DEBUG:rekall.1:Detection method rsds worked at offset 0x4e0508", 
        "2016-06-21 17:22:50,119:DEBUG:rekall.1:Running plugin (moddump) with args (()) kwargs ({'regex': 'ntoskrnl.exe', 'profile': None, 'proc_regex': None, 'dump_dir': '/tmp/tmpJFDSSp/TestModDumpThread-1', 'out_fd': None, 'pids': [], 'eprocess': [], 'method': ['PsActiveProcessHead', 'CSRSS', 'PspCidTable', 'Sessions', 'Handles']})", 
        "2016-06-21 17:22:50,361:INFO:rekall.1:Detected kernel base at 0x804D7000", 
        "2016-06-21 17:22:50,505:DEBUG:rekall.1:Listed 25 processes using PsActiveProcessHead", 
        "2016-06-21 17:22:51,241:DEBUG:rekall.1:Listed 22 processes using CSRSS", 
        "2016-06-21 17:22:51,940:DEBUG:rekall.1:Listed 25 processes using PspCidTable", 
        "2016-06-21 17:22:51,960:DEBUG:rekall.1:Listed 23 processes using Sessions", 
        "2016-06-21 17:22:52,011:DEBUG:rekall.1:Listed 24 processes using Handles"
    ], 
    "time_used": 7.070019006729126, 
    "return_code": 0, 
    "output": [
        "             Name             ||   Base   ||Filename", 
        "------------------------------||----------||--------", 
        "ntoskrnl.exe                  ||0x804d7000||driver.804d7000.ntoskrnl.exe"
    ], 
    "executed_command": "rekall  -v --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/tigger/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - moddump --regex ntoskrnl.exe --dump_dir /tmp/tmpJFDSSp/TestModDumpThread-1", 
    "hashes": {
        "driver.804d7000.ntoskrnl.exe": "04e1727a2daedcd450296a2879bea7d5"
    }, 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "--format": "test", 
        "commandline": "moddump --regex %(driver)s --dump_dir %(tempdir)s", 
        "driver": "ntoskrnl.exe", 
        "tempdir": "/tmp/tmpJFDSSp/TestModDumpThread-1", 
        "test_class": "TestModDump", 
        "--cache_dir": "/home/scudette/projects/rekall-test/tigger/../profile_cache/", 
        "--cache": "memory", 
        "debug": false, 
        "pids": 1724, 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}