#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestJSONParser /home/scudette/projects/rekall-test/tigger/TestJSONParser
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestJSONParser /home/scudette/projects/rekall-test/tigger/TestJSONParser
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestJSONParser /home/scudette/projects/rekall-test/tigger/TestJSONParser
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - json_render /tmp/tmpblovS9/TestJSONParserThread-4_output.json
else
   less /home/scudette/projects/rekall-test/tigger/output/TestJSONParser
fi
exit 0
{
    "errors": {}, 
    "time_used": 5.063330888748169, 
    "return_code": 0, 
    "failures": {
        "testCase (rekall.plugins.tools.json_tools.TestJSONParser)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 221, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 271, in testCase\n    self.assertEqual(previous, current)\nAssertionError: u'0x810b1660||System              ||4    ||0     ||61    ||179     ||-     ||Fal [truncated]... != u'0x810b1660||System              ||    4||     0||    61||     179||     -||Fal [truncated]...\n- 0x810b1660||System              ||4    ||0     ||61    ||179     ||-     ||False ||-                       ||-                       \n?                                    ----   -----    ----     -----   -----\n+ 0x810b1660||System              ||    4||     0||    61||     179||     -||False ||-                       ||-                       \n?                                   ++++   +++++   ++++    +++++     +++++\n\n"
    }, 
    "output": [
        "", 
        "***************** Plugin pslist *****************", 
        "_EPROCESS ||        Name        || PID || PPID || Thds ||  Hnds  || Sess ||Wow64 ||         Start          ||          Exit          ", 
        "----------||--------------------||-----||------||------||--------||------||------||------------------------||------------------------", 
        "0x810b1660||System              ||    4||     0||    61||     179||     -||False ||-                       ||-                       ", 
        "0xff25a7e0||alg.exe             ||  216||   676||     7||     108||     0||False ||2010-08-11 06:06:39+0000||-                       ", 
        "0xff3667e8||VMwareTray.exe      ||  432||  1724||     1||      49||     0||False ||2010-08-11 06:09:31+0000||-                       ", 
        "0xff374980||VMwareUser.exe      ||  452||  1724||     8||     204||     0||False ||2010-08-11 06:09:32+0000||-                       ", 
        "0x80f94588||wuauclt.exe         ||  468||  1028||     4||     131||     0||False ||2010-08-11 06:09:37+0000||-                       ", 
        "0xff2ab020||smss.exe            ||  544||     4||     3||      21||     -||False ||2010-08-11 06:06:21+0000||-                       ", 
        "0xff1ecda0||csrss.exe           ||  608||   544||    10||     405||     0||False ||2010-08-11 06:06:23+0000||-                       ", 
        "0xff1ec978||winlogon.exe        ||  632||   544||    22||     519||     0||False ||2010-08-11 06:06:23+0000||-                       ", 
        "0xff247020||services.exe        ||  676||   632||    16||     269||     0||False ||2010-08-11 06:06:24+0000||-                       ", 
        "0xff255020||lsass.exe           ||  688||   632||    21||     348||     0||False ||2010-08-11 06:06:24+0000||-                       ", 
        "0xff27d4d0||wmiprvse.exe        ||  828||   856||     9||     214||     0||False ||2010-08-15 19:26:08+0000||-                       ", 
        "0xff218230||vmacthlp.exe        ||  844||   676||     1||      24||     0||False ||2010-08-11 06:06:24+0000||-                       ", 
        "0x80ff88d8||svchost.exe         ||  856||   676||    18||     202||     0||False ||2010-08-11 06:06:24+0000||-                       ", 
        "0xff364310||wscntfy.exe         ||  888||  1028||     1||      27||     0||False ||2010-08-11 06:06:49+0000||-                       ", 
        "0xff217560||svchost.exe         ||  936||   676||     9||     270||     0||False ||2010-08-11 06:06:24+0000||-                       ", 
        "0x80fbf910||svchost.exe         || 1028||   676||    88||    1395||     0||False ||2010-08-11 06:06:24+0000||-                       ", 
        "0xff38b5f8||TPAutoConnect.e     || 1084||  1968||     1||      61||     0||False ||2010-08-11 06:06:52+0000||-                       ", 
        "0xff22d558||svchost.exe         || 1088||   676||     7||      80||     0||False ||2010-08-11 06:06:25+0000||-                       ", 
        "0xff203b80||svchost.exe         || 1148||   676||    15||     210||     0||False ||2010-08-11 06:06:26+0000||-                       ", 
        "0xff1d7da0||spoolsv.exe         || 1432||   676||    14||     137||     0||False ||2010-08-11 06:06:26+0000||-                       ", 
        "0xff1b8b28||vmtoolsd.exe        || 1668||   676||     5||     218||     0||False ||2010-08-11 06:06:35+0000||-                       ", 
        "0xff3865d0||explorer.exe        || 1724||  1708||    13||     314||     0||False ||2010-08-11 06:09:29+0000||-                       ", 
        "0x80f60da0||wuauclt.exe         || 1732||  1028||     7||     178||     0||False ||2010-08-11 06:07:44+0000||-                       ", 
        "0xff1fdc88||VMUpgradeHelper     || 1788||   676||     5||     100||     0||False ||2010-08-11 06:06:38+0000||-                       ", 
        "0xff143b28||TPAutoConnSvc.e     || 1968||   676||     5||     100||     0||False ||2010-08-11 06:06:39+0000||-                       "
    ], 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "json_render /tmp/tmpblovS9/TestJSONParserThread-4_output.json", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestJSONParser", 
        "tempdir": "/tmp/tmpblovS9/TestJSONParserThread-4", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - json_render /tmp/tmpblovS9/TestJSONParserThread-4_output.json", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}