#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/mic/projects/rekall-test/tigger/output/TestBuildProfileLocally /home/mic/projects/rekall-test/tigger/TestBuildProfileLocally
elif [ "$1" == "meld" ]; then
   meld /home/mic/projects/rekall-test/tigger/output/TestBuildProfileLocally /home/mic/projects/rekall-test/tigger/TestBuildProfileLocally
elif [ "$1" == "diff" ]; then
   diff /home/mic/projects/rekall-test/tigger/output/TestBuildProfileLocally /home/mic/projects/rekall-test/tigger/TestBuildProfileLocally
elif [ "$1" == "run" ]; then
   rekall  -v --name_resolution_strategies 'Module' 'Symbol' --cache 'memory' --cache_dir '/home/mic/projects/rekall-test/tigger/../profile_cache/' --filename '/home/mic/projects/rekall-test/tigger/tigger.vmem.E01' --format 'test' - build_local_profile --module_name=ntkrnlpa --guid=BD8F451F3E754ED8A34B50560CEB08E31 --dumpfile /tmp/tmp1wli0hs0/TestBuildProfileLocallyThread-1/output
else
   less /home/mic/projects/rekall-test/tigger/output/TestBuildProfileLocally
fi
exit 0
{
    "errors": {
        "TestBuildProfileLocally testCase": {}
    },
    "executed_command": "rekall  -v --name_resolution_strategies 'Module' 'Symbol' --cache 'memory' --cache_dir '/home/mic/projects/rekall-test/tigger/../profile_cache/' --filename '/home/mic/projects/rekall-test/tigger/tigger.vmem.E01' --format 'test' - build_local_profile --module_name=ntkrnlpa --guid=BD8F451F3E754ED8A34B50560CEB08E31 --dumpfile /tmp/tmp1wli0hs0/TestBuildProfileLocallyThread-1/output",
    "failures": {
        "TestBuildProfileLocally testCase": {
            "TestBuildProfileLocally testCase": {
                "failure_info": null,
                "msg": "Traceback (most recent call last):\n  File \"/home/mic/rekall/rekall-core/rekall/testlib.py\", line 302, in run\n    testMethod()\n  File \"/home/mic/rekall/rekall-core/rekall/testlib.py\", line 434, in testCase\n    self.assertEqual(self.baseline['hashes'], self.current['hashes'])\nAssertionError: {'output': '4a4601b611b1f10477aa11251bec74fc'} != {'output': '977e18c0e47823903d394a1233516e10'}\n- {'output': '4a4601b611b1f10477aa11251bec74fc'}\n+ {'output': '977e18c0e47823903d394a1233516e10'}\n"
            }
        }
    },
    "hashes": {
        "output": "977e18c0e47823903d394a1233516e10"
    },
    "logging": [
        "2017-10-12 22:56:58,618:DEBUG:rekall.1:Logging level set to 10",
        "2017-10-12 22:56:58,619:DEBUG:rekall.1:Running plugin (build_local_profile) with args (()) kwargs ({'module_name': 'ntkrnlpa', 'guid': 'BD8F451F3E754ED8A34B50560CEB08E31', 'dumpfile': '/tmp/tmp1wli0hs0/TestBuildProfileLocallyThread-1/output'})",
        "2017-10-12 22:56:58,827:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/inventory.gz",
        "2017-10-12 22:56:59,179:DEBUG:rekall.1:Opened local file /home/mic/projects/rekall-test/profile_cache/v1.0/inventory.gz",
        "2017-10-12 22:56:59,215:DEBUG:rekall.1:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz",
        "2017-10-12 22:56:59,480:DEBUG:rekall.1:Opened local file /home/mic/projects/rekall-test/profile_cache/v1.0/inventory.gz",
        "Extracting cabinet: /tmp/tmpujno3np_/ntkrnlpa.pd_",
        "  extracting ntkrnlpa.pdb",
        "",
        "All done, no errors.",
        "2017-10-12 22:57:00,762:DEBUG:rekall.1:Opened local file /home/mic/projects/rekall-test/profile_cache/v1.0/mspdb.gz",
        "2017-10-12 22:57:00,770:INFO:rekall.1:Loaded profile mspdb from Local Cache Directory:/home/mic/projects/rekall-test/profile_cache (in 0.007786989212036133 sec)"
    ],
    "options": {
        "--cache": "memory",
        "--cache_dir": "/home/mic/projects/rekall-test/tigger/../profile_cache/",
        "--filename": "/home/mic/projects/rekall-test/tigger/tigger.vmem.E01",
        "--format": "test",
        "--name_resolution_strategies": [
            "Module",
            "Symbol"
        ],
        "commandline": "build_local_profile --module_name=%(pdb_name)s --guid=%(guid)s --dumpfile %(tempdir)s/output",
        "debug": false,
        "executable": "rekall ",
        "guid": "BD8F451F3E754ED8A34B50560CEB08E31",
        "pdb_name": "ntkrnlpa",
        "pids": 1724,
        "tempdir": "/tmp/tmp1wli0hs0/TestBuildProfileLocallyThread-1",
        "test_class": "TestBuildProfileLocally",
        "testdir": "/home/mic/projects/rekall-test/tigger"
    },
    "output": [],
    "return_code": 0,
    "time_used": 11.248910903930664
}