#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /Users/adamsh/Projects/rekall-test/tigger/output/TestDisassemble /Users/adamsh/Projects/rekall-test/tigger/TestDisassemble
elif [ "$1" == "meld" ]; then
   meld /Users/adamsh/Projects/rekall-test/tigger/output/TestDisassemble /Users/adamsh/Projects/rekall-test/tigger/TestDisassemble
elif [ "$1" == "diff" ]; then
   diff /Users/adamsh/Projects/rekall-test/tigger/output/TestDisassemble /Users/adamsh/Projects/rekall-test/tigger/TestDisassemble
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - dis -l 50 nt!MmGetPhysicalMemoryRanges --name_resolution_strategies Export
else
   less /Users/adamsh/Projects/rekall-test/tigger/output/TestDisassemble
fi
exit 0
{
    "time_used": 3.6357860565185547, 
    "output": [
        "Address||Rel ||      Op Codes      ||         Instruction          ||Comment", 
        "-------||----||--------------------||------------------------------||-------", 
        "------ nt!MmGetPhysicalMemoryRanges ------", 
        " ||0x8063f386||0   ||8bff                ||MOV EDI, EDI                  ||       ", 
        " ||0x8063f388||2   ||55                  ||PUSH EBP                      ||       ", 
        " ||0x8063f389||3   ||8bec                ||MOV EBP, ESP                  ||       ", 
        " ||0x8063f38b||5   ||51                  ||PUSH ECX                      ||       ", 
        " ||0x8063f38c||6   ||51                  ||PUSH ECX                      ||       ", 
        " ||0x8063f38d||7   ||53                  ||PUSH EBX                      ||       ", 
        " ||0x8063f38e||8   ||56                  ||PUSH ESI                      ||       ", 
        " ||0x8063f38f||9   ||b980755580          ||MOV ECX, 0x80557580           ||nt!MmDynamicMemoryMutex", 
        " ||0x8063f394||14  ||ff150c774d80        ||CALL DWORD [0x804d770c]       ||0x806d0744 nt!imp_@ExAcquireFastMutex@4 -> hal!ExAcquireFastMutex", 
        " ||0x8063f39a||20  ||a148315580          ||MOV EAX, [0x80553148]         ||0x810ddd10 nt!MmPhysicalMemoryBlock", 
        " ||0x8063f39f||25  ||8b00                ||MOV EAX, [EAX]                ||       ", 
        " ||0x8063f3a1||27  ||40                  ||INC EAX                       ||       ", 
        " ||0x8063f3a2||28  ||684d6d5068          ||PUSH DWORD 0x68506d4d         ||       ", 
        " ||0x8063f3a7||33  ||c1e004              ||SHL EAX, 0x4                  ||       ", 
        " ||0x8063f3aa||36  ||50                  ||PUSH EAX                      ||       ", 
        " ||0x8063f3ab||37  ||33db                ||XOR EBX, EBX                  ||       ", 
        " ||0x8063f3ad||39  ||53                  ||PUSH EBX                      ||       ", 
        " ||0x8063f3ae||40  ||e8cd4cf0ff          ||CALL 0x80544080               ||nt!ExAllocatePoolWithTag", 
        " ||0x8063f3b3||45  ||8bf0                ||MOV ESI, EAX                  ||       ", 
        " ||0x8063f3b5||47  ||3bf3                ||CMP ESI, EBX                  ||       ", 
        " ||0x8063f3b7||49  ||8975f8              ||MOV [EBP-0x8], ESI            ||       ", 
        " ||0x8063f3ba||52  ||7475                ||JZ 0x8063f431                 ||nt!MmGetPhysicalMemoryRanges + 0xab", 
        " ||0x8063f3bc||54  ||57                  ||PUSH EDI                      ||       ", 
        " ||0x8063f3bd||55  ||ff3528055580        ||PUSH DWORD [0x80550528]       ||0x804d7320 nt!ExPageLockHandle -> nt!_safe_se_handler_count + 0x30d", 
        " ||0x8063f3c3||61  ||e80ecdf5ff          ||CALL 0x8059c0d6               ||nt!MmLockPagableSectionByHandle", 
        " ||0x8063f3c8||66  ||ff1514774d80        ||CALL DWORD [0x804d7714]       ||0x806d0298 nt!imp__KeRaiseIrqlToDpcLevel -> hal!KeRaiseIrqlToDpcLevel", 
        " ||0x8063f3ce||72  ||8845ff              ||MOV [EBP-0x1], AL             ||       ", 
        " ||0x8063f3d1||75  ||a148315580          ||MOV EAX, [0x80553148]         ||0x810ddd10 nt!MmPhysicalMemoryBlock", 
        " ||0x8063f3d6||80  ||33ff                ||XOR EDI, EDI                  ||       ", 
        " ||0x8063f3d8||82  ||3918                ||CMP [EAX], EBX                ||       ", 
        " ||0x8063f3da||84  ||7632                ||JBE 0x8063f40e                ||nt!MmGetPhysicalMemoryRanges + 0x88", 
        " ||0x8063f3dc||86  ||b900100000          ||MOV ECX, 0x1000               ||       ", 
        " ||0x8063f3e1||91  ||8b44f808            ||MOV EAX, [EAX+EDI*8+0x8]      ||       ", 
        " ||0x8063f3e5||95  ||8bd1                ||MOV EDX, ECX                  ||       ", 
        " ||0x8063f3e7||97  ||f7e2                ||MUL EDX                       ||       ", 
        " ||0x8063f3e9||99  ||895604              ||MOV [ESI+0x4], EDX            ||       ", 
        " ||0x8063f3ec||102 ||8906                ||MOV [ESI], EAX                ||       ", 
        " ||0x8063f3ee||104 ||a148315580          ||MOV EAX, [0x80553148]         ||0x810ddd10 nt!MmPhysicalMemoryBlock", 
        " ||0x8063f3f3||109 ||8b44f80c            ||MOV EAX, [EAX+EDI*8+0xc]      ||       ", 
        " ||0x8063f3f7||113 ||8bd1                ||MOV EDX, ECX                  ||       ", 
        " ||0x8063f3f9||115 ||f7e2                ||MUL EDX                       ||       ", 
        " ||0x8063f3fb||117 ||894608              ||MOV [ESI+0x8], EAX            ||       ", 
        " ||0x8063f3fe||120 ||89560c              ||MOV [ESI+0xc], EDX            ||       ", 
        " ||0x8063f401||123 ||a148315580          ||MOV EAX, [0x80553148]         ||0x810ddd10 nt!MmPhysicalMemoryBlock", 
        " ||0x8063f406||128 ||83c610              ||ADD ESI, 0x10                 ||       ", 
        " ||0x8063f409||131 ||47                  ||INC EDI                       ||       ", 
        " ||0x8063f40a||132 ||3b38                ||CMP EDI, [EAX]                ||       ", 
        " ||0x8063f40c||134 ||72d3                ||JB 0x8063f3e1                 ||nt!MmGetPhysicalMemoryRanges + 0x5b", 
        " ||0x8063f40e||136 ||8a4dff              ||MOV CL, [EBP-0x1]             ||       ", 
        " ||0x8063f411||139 ||891e                ||MOV [ESI], EBX                ||       ", 
        " ||0x8063f413||141 ||895e04              ||MOV [ESI+0x4], EBX            ||       "
    ], 
    "errors": {}, 
    "return_code": 0, 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "dis -l %(length)s %(func)s --name_resolution_strategies Export", 
        "pid": 1724, 
        "--renderer": "test", 
        "length": 50, 
        "test_class": "TestDisassemble", 
        "func": "nt!MmGetPhysicalMemoryRanges", 
        "tempdir": "/var/folders/yc/4zng19655k37kyxgskb3vvf0006t70/T/tmpZrt2hH/TestDisassembleThread-4", 
        "executed_command": "rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - dis -l 50 nt!MmGetPhysicalMemoryRanges --name_resolution_strategies Export", 
        "testdir": "/Users/adamsh/Projects/rekall-test/tigger"
    }
}