#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestMimikatz /home/scudette/projects/rekall-test/tigger/TestMimikatz
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestMimikatz /home/scudette/projects/rekall-test/tigger/TestMimikatz
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestMimikatz /home/scudette/projects/rekall-test/tigger/TestMimikatz
elif [ "$1" == "run" ]; then
   rekall  --cache_dir '/home/scudette/projects/rekall-test/tigger/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - mimikatz
else
   less /home/scudette/projects/rekall-test/tigger/output/TestMimikatz
fi
exit 0
{
    "errors": {}, 
    "time_used": 4.995448112487793, 
    "return_code": 0, 
    "failures": {
        "testCase (__main__.TestMimikatz)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 233, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 283, in testCase\n    self.assertEqual(previous, current)\nAssertionError: u'CRITICAL:rekall-7fb4c42a0750:Unable to decrypt LSA secret.' != u'CRITICAL:rekall-7fa030922710:Unable to decrypt LSA secret.'\n- CRITICAL:rekall-7fb4c42a0750:Unable to decrypt LSA secret.\n?                   -----   ^\n+ CRITICAL:rekall-7fa030922710:Unable to decrypt LSA secret.\n?                     +++++ ^\n\n"
    }, 
    "output": [
        "       Module       ||        User        ||       Domain       ||      Password      ", 
        "--------------------||--------------------||--------------------||--------------------", 
        "CRITICAL:rekall-7fa030922710:Unable to decrypt LSA secret."
    ], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "--format": "test", 
        "commandline": "mimikatz", 
        "pid": 1724, 
        "test_class": "TestMimikatz", 
        "--cache_dir": "/home/scudette/projects/rekall-test/tigger/../profile_cache/", 
        "tempdir": "/tmp/tmpIP_zzM/TestMimikatzThread-3", 
        "executed_command": "rekall  --cache_dir '/home/scudette/projects/rekall-test/tigger/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - mimikatz", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}