#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestWhichPlugin /home/scudette/projects/rekall-test/tigger/TestWhichPlugin
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestWhichPlugin /home/scudette/projects/rekall-test/tigger/TestWhichPlugin
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestWhichPlugin /home/scudette/projects/rekall-test/tigger/TestWhichPlugin
elif [ "$1" == "run" ]; then
   rekall  -v --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/tigger/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - which_plugin _EPROCESS
else
   less /home/scudette/projects/rekall-test/tigger/output/TestWhichPlugin
fi
exit 0
{
    "failours": {
        "testCase (rekall.plugins.common.search.TestWhichPlugin)": {
            "testCase (rekall.plugins.common.search.TestWhichPlugin)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 252, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 302, in testCase\n    self.assertListEqual(previous, current)\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 224, in assertListEqual\n    self.assertEqual(len(a), len(b))\nAssertionError: 3 != 4\n"
        }
    }, 
    "errors": {
        "testCase (rekall.plugins.common.search.TestWhichPlugin)": {}
    }, 
    "logging": [
        "2016-05-02 00:51:44,056:DEBUG:rekall.1:Logging level set to 10", 
        "2016-05-02 00:51:44,057:DEBUG:rekall.1:Voting round with base: None", 
        "2016-05-02 00:51:44,057:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-05-02 00:51:44,057:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided", 
        "2016-05-02 00:51:44,058:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-05-02 00:51:44,058:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space", 
        "2016-05-02 00:51:44,058:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-05-02 00:51:44,058:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided", 
        "2016-05-02 00:51:44,058:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-05-02 00:51:44,058:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided", 
        "2016-05-02 00:51:44,059:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-05-02 00:51:44,059:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space", 
        "2016-05-02 00:51:44,059:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-05-02 00:51:44,059:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space", 
        "2016-05-02 00:51:44,059:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-05-02 00:51:44,059:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided", 
        "2016-05-02 00:51:44,059:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-05-02 00:51:44,060:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided", 
        "2016-05-02 00:51:44,060:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-05-02 00:51:44,060:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space", 
        "2016-05-02 00:51:44,060:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-05-02 00:51:44,060:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.", 
        "2016-05-02 00:51:44,060:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-05-02 00:51:44,066:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume", 
        "2016-05-02 00:51:44,066:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-05-02 00:51:44,066:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at /home/scudette/projects/rekall-test/tigger/tigger.vmem.E01_info", 
        "2016-05-02 00:51:44,066:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-05-02 00:51:44,067:DEBUG:rekall.1:Succeeded instantiating FileAddressSpace", 
        "2016-05-02 00:51:44,067:DEBUG:rekall.1:Voting round with base: FileAddressSpace", 
        "2016-05-02 00:51:44,067:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-05-02 00:51:44,070:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x9465645", 
        "2016-05-02 00:51:44,070:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-05-02 00:51:44,071:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-05-02 00:51:44,071:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-05-02 00:51:44,071:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-05-02 00:51:44,071:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-05-02 00:51:44,080:DEBUG:rekall.1:Succeeded instantiating EWFAddressSpace", 
        "2016-05-02 00:51:44,081:DEBUG:rekall.1:Voting round with base: EWFAddressSpace", 
        "2016-05-02 00:51:44,081:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-05-02 00:51:44,083:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0xf000ff53", 
        "2016-05-02 00:51:44,083:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-05-02 00:51:44,083:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-05-02 00:51:44,084:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-05-02 00:51:44,084:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-05-02 00:51:44,084:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-05-02 00:51:44,084:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "2016-05-02 00:51:44,084:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-05-02 00:51:44,086:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "2016-05-02 00:51:44,086:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-05-02 00:51:44,087:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "2016-05-02 00:51:44,087:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-05-02 00:51:44,087:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "2016-05-02 00:51:44,087:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-05-02 00:51:44,087:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "2016-05-02 00:51:44,087:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-05-02 00:51:44,088:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "2016-05-02 00:51:44,088:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-05-02 00:51:44,088:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature", 
        "2016-05-02 00:51:44,088:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-05-02 00:51:44,089:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space", 
        "2016-05-02 00:51:44,089:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-05-02 00:51:44,089:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.", 
        "2016-05-02 00:51:44,089:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-05-02 00:51:44,090:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space", 
        "2016-05-02 00:51:44,090:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> ", 
        "2016-05-02 00:51:44,090:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space", 
        "2016-05-02 00:51:44,090:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> ", 
        "2016-05-02 00:51:44,091:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified", 
        "2016-05-02 00:51:44,091:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> ", 
        "2016-05-02 00:51:44,091:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.", 
        "2016-05-02 00:51:44,092:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> ", 
        "2016-05-02 00:51:44,092:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified", 
        "2016-05-02 00:51:44,092:INFO:rekall.1:Autodetected physical address space EWFAddressSpace", 
        "2016-05-02 00:51:44,092:DEBUG:rekall.1:Will detect profile using these Detectors: linux_index,nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux", 
        "2016-05-02 00:51:44,094:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-profiles/v1.0/inventory.gz", 
        "2016-05-02 00:51:44,114:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/inventory.gz", 
        "2016-05-02 00:51:44,114:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/Linux/index.gz", 
        "2016-05-02 00:51:44,131:INFO:rekall.1:Loaded profile Linux/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0163900852203 sec)", 
        "2016-05-02 00:51:44,131:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/eprocess_index.gz", 
        "2016-05-02 00:51:44,200:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0692410469055 sec)", 
        "2016-05-02 00:51:44,201:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/index.gz", 
        "2016-05-02 00:51:44,444:INFO:rekall.1:Loaded profile nt/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.243751049042 sec)", 
        "2016-05-02 00:51:44,445:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/OSX/index.gz", 
        "2016-05-02 00:51:44,447:INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.00152707099915 sec)", 
        "2016-05-02 00:51:44,448:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/pe.gz", 
        "2016-05-02 00:51:44,472:INFO:rekall.1:Loaded profile pe from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0249519348145 sec)", 
        "2016-05-02 00:51:44,473:DEBUG:rekall.1:Trying method pe, offset 0", 
        "2016-05-02 00:51:44,477:DEBUG:rekall.1:Trying method windows_kernel_file, offset 0", 
        "2016-05-02 00:51:44,477:DEBUG:rekall.1:Trying method rsds, offset 0", 
        "2016-05-02 00:51:44,485:DEBUG:rekall.1:Trying method linux_index, offset 0", 
        "2016-05-02 00:51:44,486:DEBUG:rekall.1:LinuxIndexDetector:DetectFromHit(0) = None", 
        "2016-05-02 00:51:44,486:DEBUG:rekall.1:Trying method nt_index, offset 0", 
        "2016-05-02 00:51:44,486:DEBUG:rekall.1:Trying method ntfs, offset 0", 
        "2016-05-02 00:51:44,487:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/ntfs.gz", 
        "2016-05-02 00:51:44,493:INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.00671100616455 sec)", 
        "2016-05-02 00:51:45,043:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/GUID/BD8F451F3E754ED8A34B50560CEB08E31.gz", 
        "2016-05-02 00:51:45,325:INFO:rekall.1:Loaded profile nt/GUID/BD8F451F3E754ED8A34B50560CEB08E31 from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.28208899498 sec)", 
        "2016-05-02 00:51:45,953:DEBUG:rekall.1:Found _EPROCESS @ 0x551B80 (DTB: 0x319000)", 
        "2016-05-02 00:51:45,966:INFO:rekall.1:Detected ntkrnlpa.pdb with GUID BD8F451F3E754ED8A34B50560CEB08E31", 
        "2016-05-02 00:51:45,966:DEBUG:rekall.1:Detection method rsds worked at offset 0x4e0508", 
        "2016-05-02 00:51:45,968:DEBUG:rekall.1:Running plugin (which_plugin) with args (()) kwargs ({'profile': None, 'type_name': '_EPROCESS', 'producers_only': False})"
    ], 
    "time_used": 3.9635770320892334, 
    "return_code": 0, 
    "output": [
        "            Plugin            ", 
        "------------------------------", 
        "privileges                    ", 
        "psscan                        "
    ], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "struct": "_EPROCESS", 
        "--format": "test", 
        "commandline": "which_plugin %(struct)s", 
        "script": "search('select details AS path from handles where _EPROCESS.pid == 1968 and obj_type == \"File\"')", 
        "pid": 1724, 
        "test_class": "TestWhichPlugin", 
        "--cache_dir": "/home/scudette/projects/rekall-test/tigger/../profile_cache/", 
        "--cache": "memory", 
        "tempdir": "/tmp/tmpu1ugDQ/TestWhichPluginThread-2", 
        "executed_command": "rekall  -v --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/tigger/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - which_plugin _EPROCESS", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}