#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestPagefiles /home/scudette/projects/rekall-test/tigger/TestPagefiles
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestPagefiles /home/scudette/projects/rekall-test/tigger/TestPagefiles
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestPagefiles /home/scudette/projects/rekall-test/tigger/TestPagefiles
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - pagefiles
else
   less /home/scudette/projects/rekall-test/tigger/output/TestPagefiles
fi
exit 0
{
    "errors": {}, 
    "time_used": 1.9591729640960693, 
    "return_code": 0, 
    "failures": {
        "testCase (__main__.TestPagefiles)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 221, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 271, in testCase\n    self.assertEqual(previous, current)\nAssertionError: u'0x80f28928    ||0     ||805306368 ||\\\\??\\\\C:\\\\pagefile.sys ' != u'0x80f28928    ||     0|| 805306368||\\\\??\\\\C:\\\\pagefile.sys '\n- 0x80f28928    ||0     ||805306368 ||\\??\\C:\\pagefile.sys \n?                  -----           -\n+ 0x80f28928    ||     0|| 805306368||\\??\\C:\\pagefile.sys \n?                 +++++   +\n\n"
    }, 
    "output": [
        "_MMPAGING_FILE||Number|| Size (b) ||      Filename      ", 
        "--------------|| ---  ||----------||--------------------", 
        "0x80f28928    ||     0|| 805306368||\\??\\C:\\pagefile.sys "
    ], 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "pagefiles", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestPagefiles", 
        "tempdir": "/tmp/tmpblovS9/TestPagefilesThread-2", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - pagefiles", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}