#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestWinMemDump /home/scudette/projects/rekall-test/tigger/TestWinMemDump
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestWinMemDump /home/scudette/projects/rekall-test/tigger/TestWinMemDump
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestWinMemDump /home/scudette/projects/rekall-test/tigger/TestWinMemDump
elif [ "$1" == "run" ]; then
   rekall  -v --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/tigger/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - memdump --pid=1724 --dump_dir /tmp/tmplui8qk/TestWinMemDumpThread-4
else
   less /home/scudette/projects/rekall-test/tigger/output/TestWinMemDump
fi
exit 0
{
    "failours": {
        "testCase (rekall.plugins.windows.taskmods.TestWinMemDump)": {
            "testCase (rekall.plugins.windows.taskmods.TestWinMemDump)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 252, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 360, in testCase\n    self.assertEqual(self.baseline['hashes'], self.current['hashes'])\nAssertionError: {u'explorer.exe_1724.dmp.idx': u'3e6278e2a4d41549e4169fd31e6fed08', u'explorer.e [truncated]... != {'explorer.exe_1724.dmp.idx': '642194fb8ce93423e8ac6b5e2730d55d', 'explorer.exe_ [truncated]...\n- {u'explorer.exe_1724.dmp': u'2daa014012b075fa4a462d43db85f30e',\n?  -                         -\n\n+ {'explorer.exe_1724.dmp': '2daa014012b075fa4a462d43db85f30e',\n-  u'explorer.exe_1724.dmp.idx': u'3e6278e2a4d41549e4169fd31e6fed08'}\n+  'explorer.exe_1724.dmp.idx': '642194fb8ce93423e8ac6b5e2730d55d'}\n"
        }
    }, 
    "errors": {
        "testCase (rekall.plugins.windows.taskmods.TestWinMemDump)": {}
    }, 
    "logging": [
        "2016-03-28 09:40:17,721:DEBUG:rekall.1:Logging level set to 10", 
        "2016-03-28 09:40:17,722:DEBUG:rekall.1:Voting round with base: None", 
        "2016-03-28 09:40:17,722:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-03-28 09:40:17,722:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided", 
        "2016-03-28 09:40:17,722:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-03-28 09:40:17,722:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space", 
        "2016-03-28 09:40:17,723:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-03-28 09:40:17,723:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided", 
        "2016-03-28 09:40:17,723:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-03-28 09:40:17,723:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided", 
        "2016-03-28 09:40:17,724:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-03-28 09:40:17,724:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space", 
        "2016-03-28 09:40:17,724:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-03-28 09:40:17,724:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space", 
        "2016-03-28 09:40:17,724:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-03-28 09:40:17,724:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided", 
        "2016-03-28 09:40:17,725:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-03-28 09:40:17,725:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided", 
        "2016-03-28 09:40:17,725:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-03-28 09:40:17,725:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space", 
        "2016-03-28 09:40:17,725:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-03-28 09:40:17,725:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.", 
        "2016-03-28 09:40:17,725:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-03-28 09:40:17,728:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume", 
        "2016-03-28 09:40:17,728:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-03-28 09:40:17,728:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at /home/scudette/projects/rekall-test/tigger/tigger.vmem.E01_info", 
        "2016-03-28 09:40:17,728:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-03-28 09:40:17,728:DEBUG:rekall.1:Succeeded instantiating FileAddressSpace", 
        "2016-03-28 09:40:17,728:DEBUG:rekall.1:Voting round with base: FileAddressSpace", 
        "2016-03-28 09:40:17,729:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-03-28 09:40:17,731:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x9465645", 
        "2016-03-28 09:40:17,731:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-03-28 09:40:17,731:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-03-28 09:40:17,731:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-03-28 09:40:17,731:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-03-28 09:40:17,732:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-03-28 09:40:17,740:DEBUG:rekall.1:Succeeded instantiating EWFAddressSpace", 
        "2016-03-28 09:40:17,740:DEBUG:rekall.1:Voting round with base: EWFAddressSpace", 
        "2016-03-28 09:40:17,740:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-03-28 09:40:17,742:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0xf000ff53", 
        "2016-03-28 09:40:17,743:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-03-28 09:40:17,743:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-03-28 09:40:17,743:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-03-28 09:40:17,743:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-03-28 09:40:17,743:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-03-28 09:40:17,744:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "2016-03-28 09:40:17,744:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-03-28 09:40:17,744:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "2016-03-28 09:40:17,744:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-03-28 09:40:17,745:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "2016-03-28 09:40:17,745:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-03-28 09:40:17,745:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "2016-03-28 09:40:17,745:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-03-28 09:40:17,746:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "2016-03-28 09:40:17,746:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-03-28 09:40:17,746:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "2016-03-28 09:40:17,746:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-03-28 09:40:17,746:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature", 
        "2016-03-28 09:40:17,746:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-03-28 09:40:17,747:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space", 
        "2016-03-28 09:40:17,747:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-03-28 09:40:17,748:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.", 
        "2016-03-28 09:40:17,748:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-03-28 09:40:17,748:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space", 
        "2016-03-28 09:40:17,748:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> ", 
        "2016-03-28 09:40:17,748:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space", 
        "2016-03-28 09:40:17,748:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> ", 
        "2016-03-28 09:40:17,749:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified", 
        "2016-03-28 09:40:17,749:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> ", 
        "2016-03-28 09:40:17,750:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.", 
        "2016-03-28 09:40:17,750:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> ", 
        "2016-03-28 09:40:17,750:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified", 
        "2016-03-28 09:40:17,750:INFO:rekall.1:Autodetected physical address space EWFAddressSpace", 
        "2016-03-28 09:40:17,751:DEBUG:rekall.1:Will detect profile using these Detectors: linux_index,nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux", 
        "2016-03-28 09:40:18,319:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master//v1.0/inventory.gz", 
        "2016-03-28 09:40:18,401:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/inventory.gz", 
        "2016-03-28 09:40:18,402:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/Linux/index.gz", 
        "2016-03-28 09:40:18,518:INFO:rekall.1:Loaded profile Linux/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.115736961365 sec)", 
        "2016-03-28 09:40:18,518:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/eprocess_index.gz", 
        "2016-03-28 09:40:18,580:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0613758563995 sec)", 
        "2016-03-28 09:40:18,580:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/index.gz", 
        "2016-03-28 09:40:18,677:INFO:rekall.1:Loaded profile nt/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0973260402679 sec)", 
        "2016-03-28 09:40:18,678:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/OSX/index.gz", 
        "2016-03-28 09:40:18,679:INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.000942945480347 sec)", 
        "2016-03-28 09:40:18,679:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/pe.gz", 
        "2016-03-28 09:40:18,725:INFO:rekall.1:Loaded profile pe from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0458559989929 sec)", 
        "2016-03-28 09:40:18,725:DEBUG:rekall.1:Trying method pe, offset 0", 
        "2016-03-28 09:40:18,745:DEBUG:rekall.1:Trying method windows_kernel_file, offset 0", 
        "2016-03-28 09:40:18,746:DEBUG:rekall.1:Trying method rsds, offset 0", 
        "2016-03-28 09:40:18,746:DEBUG:rekall.1:Trying method linux_index, offset 0", 
        "2016-03-28 09:40:18,747:DEBUG:rekall.1:LinuxIndexDetector:DetectFromHit(0) = None", 
        "2016-03-28 09:40:18,748:DEBUG:rekall.1:Trying method nt_index, offset 0", 
        "2016-03-28 09:40:18,748:DEBUG:rekall.1:Trying method ntfs, offset 0", 
        "2016-03-28 09:40:18,749:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/ntfs.gz", 
        "2016-03-28 09:40:18,754:INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.00509905815125 sec)", 
        "2016-03-28 09:40:19,477:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/GUID/BD8F451F3E754ED8A34B50560CEB08E31.gz", 
        "2016-03-28 09:40:19,819:INFO:rekall.1:Loaded profile nt/GUID/BD8F451F3E754ED8A34B50560CEB08E31 from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.342448949814 sec)", 
        "2016-03-28 09:40:20,065:DEBUG:rekall.1:Found _EPROCESS @ 0x551B80 (DTB: 0x319000)", 
        "2016-03-28 09:40:20,074:INFO:rekall.1:Detected ntkrnlpa.pdb with GUID BD8F451F3E754ED8A34B50560CEB08E31", 
        "2016-03-28 09:40:20,074:DEBUG:rekall.1:Detection method rsds worked at offset 0x4e0508", 
        "2016-03-28 09:40:20,078:DEBUG:rekall.1:Running plugin (memdump) with args (()) kwargs ({'profile': None, 'proc_regex': None, 'phys_eprocess': None, 'pid': [1724], 'all': False, 'coalesce': False, 'dump_dir': '/tmp/tmplui8qk/TestWinMemDumpThread-4', 'eprocess': None, 'method': ['PsActiveProcessHead', 'CSRSS', 'PspCidTable', 'Sessions', 'Handles']})", 
        "2016-03-28 09:40:20,293:INFO:rekall.1:Detected kernel base at 0x804D7000", 
        "2016-03-28 09:40:20,315:DEBUG:rekall.1:Listed 25 processes using PsActiveProcessHead", 
        "2016-03-28 09:40:20,777:DEBUG:rekall.1:Listed 22 processes using CSRSS", 
        "2016-03-28 09:40:21,350:DEBUG:rekall.1:Listed 25 processes using PspCidTable", 
        "2016-03-28 09:40:21,369:DEBUG:rekall.1:Listed 23 processes using Sessions", 
        "2016-03-28 09:40:21,418:DEBUG:rekall.1:Listed 24 processes using Handles"
    ], 
    "time_used": 10.103856801986694, 
    "return_code": 0, 
    "output": [
        "**************************************************", 
        "Writing 0xff3865d0||explorer.exe|| 1724 to explorer.exe_1724.dmp"
    ], 
    "hashes": {
        "explorer.exe_1724.dmp.idx": "642194fb8ce93423e8ac6b5e2730d55d", 
        "explorer.exe_1724.dmp": "2daa014012b075fa4a462d43db85f30e"
    }, 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "--format": "test", 
        "commandline": "memdump --pid=%(pid)s --dump_dir %(tempdir)s", 
        "script": "search('select details AS path from handles where _EPROCESS.pid == 1968 and obj_type == \"File\"')", 
        "pid": 1724, 
        "test_class": "TestWinMemDump", 
        "--cache_dir": "/home/scudette/projects/rekall-test/tigger/../profile_cache/", 
        "--cache": "memory", 
        "tempdir": "/tmp/tmplui8qk/TestWinMemDumpThread-4", 
        "executed_command": "rekall  -v --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/tigger/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - memdump --pid=1724 --dump_dir /tmp/tmplui8qk/TestWinMemDumpThread-4", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}