#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /Users/adamsh/Projects/rekall-test/tigger/output/TestWinPhysicalMap /Users/adamsh/Projects/rekall-test/tigger/TestWinPhysicalMap
elif [ "$1" == "meld" ]; then
   meld /Users/adamsh/Projects/rekall-test/tigger/output/TestWinPhysicalMap /Users/adamsh/Projects/rekall-test/tigger/TestWinPhysicalMap
elif [ "$1" == "diff" ]; then
   diff /Users/adamsh/Projects/rekall-test/tigger/output/TestWinPhysicalMap /Users/adamsh/Projects/rekall-test/tigger/TestWinPhysicalMap
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - phys_map
else
   less /Users/adamsh/Projects/rekall-test/tigger/output/TestWinPhysicalMap
fi
exit 0
{
    "time_used": 3.325556993484497, 
    "output": [
        "Phys Start|| Phys End ||Number of Pages", 
        "----------||----------||---------------", 
        "0x00001000||0x0009f000||158            ", 
        "0x00100000||0x00fff000||3839           ", 
        "0x01000000||0x07ef0000||28400          ", 
        "0x07f00000||0x08000000||256            "
    ], 
    "errors": {}, 
    "return_code": 0, 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "phys_map", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestWinPhysicalMap", 
        "tempdir": "/var/folders/yc/4zng19655k37kyxgskb3vvf0006t70/T/tmpZrt2hH/TestWinPhysicalMapThread-6", 
        "executed_command": "rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - phys_map", 
        "testdir": "/Users/adamsh/Projects/rekall-test/tigger"
    }
}