#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /Users/adamsh/Projects/rekall-test/tigger/output/TestHives /Users/adamsh/Projects/rekall-test/tigger/TestHives
elif [ "$1" == "meld" ]; then
   meld /Users/adamsh/Projects/rekall-test/tigger/output/TestHives /Users/adamsh/Projects/rekall-test/tigger/TestHives
elif [ "$1" == "diff" ]; then
   diff /Users/adamsh/Projects/rekall-test/tigger/output/TestHives /Users/adamsh/Projects/rekall-test/tigger/TestHives
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - hives
else
   less /Users/adamsh/Projects/rekall-test/tigger/output/TestHives
fi
exit 0
{
    "time_used": 3.381863832473755, 
    "output": [
        "  Offset  ||Name", 
        "----------||----", 
        "0xe1e158c0||\\Device\\HarddiskVolume1\\Documents and Settings\\Administrator\\Local Settings\\Application Data\\Microsoft\\Windows\\UsrClass.dat @ 0xe1e158c0", 
        "0xe1da4008||\\Device\\HarddiskVolume1\\Documents and Settings\\Administrator\\NTUSER.DAT @ 0xe1da4008", 
        "0xe1c49008||\\Device\\HarddiskVolume1\\Documents and Settings\\LocalService\\Local Settings\\Application Data\\Microsoft\\Windows\\UsrClass.dat @ 0xe1c49008", 
        "0xe1c41b60||\\Device\\HarddiskVolume1\\Documents and Settings\\LocalService\\NTUSER.DAT @ 0xe1c41b60", 
        "0xe1a39638||\\Device\\HarddiskVolume1\\Documents and Settings\\NetworkService\\Local Settings\\Application Data\\Microsoft\\Windows\\UsrClass.dat @ 0xe1a39638", 
        "0xe1a33008||\\Device\\HarddiskVolume1\\Documents and Settings\\NetworkService\\NTUSER.DAT @ 0xe1a33008", 
        "0xe153ab60||\\Device\\HarddiskVolume1\\WINDOWS\\system32\\config\\software @ 0xe153ab60", 
        "0xe1542008||\\Device\\HarddiskVolume1\\WINDOWS\\system32\\config\\default @ 0xe1542008", 
        "0xe1537b60||\u0000 @ 0xe1537b60", 
        "0xe1544008||\\Device\\HarddiskVolume1\\WINDOWS\\system32\\config\\SAM @ 0xe1544008", 
        "0xe13ae580||[no name] @ 0xe13ae580", 
        "0xe101b008||\\Device\\HarddiskVolume1\\WINDOWS\\system32\\config\\system @ 0xe101b008", 
        "0xe1008978||[no name] @ 0xe1008978"
    ], 
    "errors": {}, 
    "return_code": 0, 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "hives", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestHives", 
        "tempdir": "/var/folders/yc/4zng19655k37kyxgskb3vvf0006t70/T/tmpMn5Sf6/TestHivesThread-4", 
        "executed_command": "rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - hives", 
        "testdir": "/Users/adamsh/Projects/rekall-test/tigger"
    }
}