#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/test_data/tigger/output/TestRenderingSampler /home/scudette/projects/test_data/tigger/TestRenderingSampler
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/test_data/tigger/output/TestRenderingSampler /home/scudette/projects/test_data/tigger/TestRenderingSampler
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/test_data/tigger/output/TestRenderingSampler /home/scudette/projects/test_data/tigger/TestRenderingSampler
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/home/scudette/projects/test_data/tigger/tigger.vmem' --name_resolution_strategies 'Module,Symbol' - render_sample
else
   less /home/scudette/projects/test_data/tigger/output/TestRenderingSampler
fi
exit 0
{
    "time_used": 0.7949600219726562, 
    "output": [
        "usage: rekall [-v] [-q] [--debug] [--pager PAGER] [--paging_limit PAGING_LIMIT] [--nocolors] [--renderer {text,json,wide,test,data}] [--plugin PLUGIN] [-h]", 
        "              [--profile_path PROFILE_PATH] [-f FILENAME] [--buffer_size BUFFER_SIZE] [--output OUTPUT] [--max_collector_cost MAX_COLLECTOR_COST] [--dtb DTB] [--ept EPT [EPT ...]]", 
        "              [--timezone TIMEZONE] [--name_resolution_strategies NAME_RESOLUTION_STRATEGIES [NAME_RESOLUTION_STRATEGIES ...]] [-E ENTITY_FILTER]", 
        "              [--autodetect AUTODETECT [AUTODETECT ...]] [--autodetect_threshold AUTODETECT_THRESHOLD] [--generate_ballast GENERATE_BALLAST] [-r RUN] [-s SESSION_FILENAME] [-]", 
        "              {Nothing,NamedSection,UnnamedSection,OneRowTable,Format}", 
        "rekall: error: argument sample is required"
    ], 
    "errors": {
        "return_code": 2
    }, 
    "return_code": 2, 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/test_data/tigger/tigger.vmem", 
        "commandline": "render_sample", 
        "pid": "1724", 
        "--renderer": "test", 
        "test_class": "TestRenderingSampler", 
        "tempdir": "/tmp/tmpt6DtO6/TestRenderingSamplerThread-2", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/test_data/tigger/tigger.vmem' --name_resolution_strategies 'Module,Symbol' - render_sample", 
        "testdir": "/home/scudette/projects/test_data/tigger"
    }
}