#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestPFN /home/scudette/projects/rekall-test/tigger/TestPFN
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestPFN /home/scudette/projects/rekall-test/tigger/TestPFN
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestPFN /home/scudette/projects/rekall-test/tigger/TestPFN
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - pfn 0x4a06
else
   less /home/scudette/projects/rekall-test/tigger/output/TestPFN
fi
exit 0
{
    "errors": {}, 
    "time_used": 1.243412971496582, 
    "return_code": 0, 
    "failures": {
        "testCase (rekall.plugins.windows.pfn_test.TestPFN)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 227, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 277, in testCase\n    self.assertEqual(previous, current)\nAssertionError: u'    flink  0x0  blink / share count 0x00000001' != u'    flink  0x0  blink / share count 0x1'\n-     flink  0x0  blink / share count 0x00000001\n?                                       -------\n+     flink  0x0  blink / share count 0x1\n\n"
    }, 
    "output": [
        "    PFN     0x4a06 at kernel address 0x80e818a8", 
        "    flink  0x0  blink / share count 0x1", 
        "    pteaddress (VAS) 0xc07f9c30  (Phys AS) 0x103fc30", 
        "    reference count 0x1   color -", 
        "    containing page        0x103f  ActiveAndValid     PM", 
        "    ParityError Modified", 
        "    "
    ], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "pfn 0x4a06", 
        "pid": 1724, 
        "--renderer": "test", 
        "pfn": 0, 
        "test_class": "TestPFN", 
        "tempdir": "/tmp/tmp_r4v2T/TestPFNThread-1", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - pfn 0x4a06", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}