#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestPSScan /home/scudette/projects/rekall-test/tigger/TestPSScan
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestPSScan /home/scudette/projects/rekall-test/tigger/TestPSScan
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestPSScan /home/scudette/projects/rekall-test/tigger/TestPSScan
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - psscan
else
   less /home/scudette/projects/rekall-test/tigger/output/TestPSScan
fi
exit 0
{
    "errors": {}, 
    "time_used": 5.346803903579712, 
    "return_code": 0, 
    "failures": {
        "testCase (__main__.TestPSScan)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 221, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 271, in testCase\n    self.assertEqual(previous, current)\nAssertionError: u' ||0x010c3da0   ||wuauclt.exe         ||1732 ||0x80f60da0||1028  ||0x06cc02c0| [truncated]... != u' ||0x010c3da0   ||wuauclt.exe         || 1732||0x80f60da0||  1028||0x06cc02c0| [truncated]...\n-  ||0x010c3da0   ||wuauclt.exe         ||1732 ||0x80f60da0||1028  ||0x06cc02c0||EP  ||2010-08-11 06:07:44+0000||                        \n?                                             -                  --\n+  ||0x010c3da0   ||wuauclt.exe         || 1732||0x80f60da0||  1028||0x06cc02c0||EP  ||2010-08-11 06:07:44+0000||                        \n?                                         +                  ++\n\n"
    }, 
    "output": [
        "-||_EPROCESS (P)||        Name        || PID ||Offset(V) || PPID ||   PDB    ||Stat||      Time created      ||      Time exited       ", 
        " ||-------------||--------------------||-----||----------||------||----------||----||------------------------||------------------------", 
        " ||0x010c3da0   ||wuauclt.exe         || 1732||0x80f60da0||  1028||0x06cc02c0||EP  ||2010-08-11 06:07:44+0000||                        ", 
        " ||0x010f7588   ||wuauclt.exe         ||  468||0x80f94588||  1028||0x06cc0180||EP  ||2010-08-11 06:09:37+0000||                        ", 
        " ||0x01122910   ||svchost.exe         || 1028||0x80fbf910||   676||0x06cc0120||EP  ||2010-08-11 06:06:24+0000||                        ", 
        " ||0x0113bda8   ||\ufffd\ufffd\ufffd\ufffd\u070d\ufffd\ufffd\u070d\ufffd\ufffd\ufffd\ufffdO\ufffd      ||65536||-         ||216410||0xf37e1000||    ||                        ||                        ", 
        " ||             ||                    ||     ||          ||  0852||          ||    ||                        ||                        ", 
        " ||0x0115b8d8   ||svchost.exe         ||  856||0x80ff88d8||   676||0x06cc00e0||EP  ||2010-08-11 06:06:24+0000||                        ", 
        " ||0x01214660   ||System              ||    4||0x810b1660||     0||0x00319000||EP  ||                        ||                        ", 
        " ||0x0211ab28   ||TPAutoConnSvc.e     || 1968||0xff143b28||   676||0x06cc0260||EP  ||2010-08-11 06:06:39+0000||                        ", 
        " ||0x049c15f8   ||TPAutoConnect.e     || 1084||0xff38b5f8||  1968||0x06cc0220||EP  ||2010-08-11 06:06:52+0000||                        ", 
        " ||0x04a065d0   ||explorer.exe        || 1724||0xff3865d0||  1708||0x06cc0280||EP  ||2010-08-11 06:09:29+0000||                        ", 
        " ||0x04a4d2c8   ||cmd.exe             ||  532||0xff3802c8||  1668||0x06cc0320||    ||2010-08-15 19:26:50+0000||2010-08-15 19:26:50+0000", 
        " ||0x04a55748   ||H\ufffd7\ufffd|\ufffd7\ufffd|\ufffd7\ufffd\ufffd\ufffdO\ufffd    ||65536||-         ||428183||0xf32ed000||    ||                        ||                        ", 
        " ||             ||                    ||     ||          ||  3620||          ||    ||                        ||                        ", 
        " ||0x04b5a980   ||VMwareUser.exe      ||  452||0xff374980||  1724||0x06cc0300||EP  ||2010-08-11 06:09:32+0000||                        ", 
        " ||0x04b5f5f8   ||\ufffd\ufffd6\ufffd,\ufffd6\ufffd,\ufffd6\ufffd\ufffd\ufffdO\ufffd    ||65536||-         ||     0||0xf3429000||    ||                        ||                        ", 
        " ||0x04be97e8   ||VMwareTray.exe      ||  432||0xff3667e8||  1724||0x06cc02e0||EP  ||2010-08-11 06:09:31+0000||                        ", 
        " ||0x04c2b310   ||wscntfy.exe         ||  888||0xff364310||  1028||0x06cc0200||EP  ||2010-08-11 06:06:49+0000||                        ", 
        " ||0x05471020   ||smss.exe            ||  544||0xff2ab020||     4||0x06cc0020||EP  ||2010-08-11 06:06:21+0000||                        ", 
        " ||0x05c9f4d0   ||wmiprvse.exe        ||  828||0xff27d4d0||   856||0x06cc0340||EP  ||2010-08-15 19:26:08+0000||                        ", 
        " ||0x05f027e0   ||alg.exe             ||  216||0xff25a7e0||   676||0x06cc0240||EP  ||2010-08-11 06:06:39+0000||                        ", 
        " ||0x05f47020   ||lsass.exe           ||  688||0xff255020||   632||0x06cc00a0||EP  ||2010-08-11 06:06:24+0000||                        ", 
        " ||0x06015020   ||services.exe        ||  676||0xff247020||   632||0x06cc0080||EP  ||2010-08-11 06:06:24+0000||                        ", 
        " ||0x061ef558   ||svchost.exe         || 1088||0xff22d558||   676||0x06cc0140||EP  ||2010-08-11 06:06:25+0000||                        ", 
        " ||0x06384230   ||vmacthlp.exe        ||  844||0xff218230||   676||0x06cc00c0||EP  ||2010-08-11 06:06:24+0000||                        ", 
        " ||0x063c5560   ||svchost.exe         ||  936||0xff217560||   676||0x06cc0100||EP  ||2010-08-11 06:06:24+0000||                        ", 
        " ||0x06499b80   ||svchost.exe         || 1148||0xff203b80||   676||0x06cc0160||EP  ||2010-08-11 06:06:26+0000||                        ", 
        " ||0x0655fc88   ||VMUpgradeHelper     || 1788||0xff1fdc88||   676||0x06cc01e0||EP  ||2010-08-11 06:06:38+0000||                        ", 
        " ||0x066f0978   ||winlogon.exe        ||  632||0xff1ec978||   544||0x06cc0060||EP  ||2010-08-11 06:06:23+0000||                        ", 
        " ||0x066f0da0   ||csrss.exe           ||  608||0xff1ecda0||   544||0x06cc0040||EP  ||2010-08-11 06:06:23+0000||                        ", 
        " ||0x066f14c0   ||\ufffd\ufffd                  ||65536||-         ||     0||0xfbfc3000||    ||                        ||                        ", 
        " ||             ||\ufffd\ufffd                  ||     ||          ||      ||          ||    ||                        ||                        ", 
        " ||             ||\ufffd\ufffd                  ||     ||          ||      ||          ||    ||                        ||                        ", 
        " ||             ||\ufffd\ufffd\ufffdO\ufffd               ||     ||          ||      ||          ||    ||                        ||                        ", 
        " ||0x066f1c08   ||logonui.exe         || 1168||0xff1ebc08||   632||0x06cc0180||    ||2010-08-11 06:06:26+0000||2010-08-11 06:09:35+0000", 
        " ||0x06945da0   ||spoolsv.exe         || 1432||0xff1d7da0||   676||0x06cc01a0||EP  ||2010-08-11 06:06:26+0000||                        ", 
        " ||0x069d5b28   ||vmtoolsd.exe        || 1668||0xff1b8b28||   676||0x06cc01c0||EP  ||2010-08-11 06:06:35+0000||                        "
    ], 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "psscan", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestPSScan", 
        "tempdir": "/tmp/tmpblovS9/TestPSScanThread-4", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - psscan", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}