#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /Users/adamsh/Projects/rekall-test/tigger/output/TestEvtLogs /Users/adamsh/Projects/rekall-test/tigger/TestEvtLogs
elif [ "$1" == "meld" ]; then
   meld /Users/adamsh/Projects/rekall-test/tigger/output/TestEvtLogs /Users/adamsh/Projects/rekall-test/tigger/TestEvtLogs
elif [ "$1" == "diff" ]; then
   diff /Users/adamsh/Projects/rekall-test/tigger/output/TestEvtLogs /Users/adamsh/Projects/rekall-test/tigger/TestEvtLogs
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - evtlogs
else
   less /Users/adamsh/Projects/rekall-test/tigger/output/TestEvtLogs
fi
exit 0
{
    "time_used": 5.093559980392456, 
    "output": [
        "TimeWritten||Filename||Computer||Sid||Source||Event Id||Event Type||Message", 
        "-----------||--------||--------||---||------||--------||----------||-------", 
        "2010-06-10 16:04:45+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-82-1442861056||LoadPerf||1000    ||Info      ||'RSVP';'QoS RSVP'", 
        "2010-06-10 16:04:57+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-80-1660971008||LoadPerf||1000    ||Info      ||'PSched';'PSched'", 
        "2010-06-10 16:05:01+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-82-1828744960||LoadPerf||1000    ||Info      ||'RemoteAccess';'Routing and Remote Access'", 
        "2010-06-10 16:05:44+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-84-1912630528||LoadPerf||1000    ||Info      ||'TermService';'Terminal Services'", 
        "2010-06-10 16:05:48+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-77-1140872192||LoadPerf||1000    ||Info      ||'MSDTC';'MSDTC'", 
        "2010-06-10 16:05:49+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-0-1811939328||MSDTC ||4104    ||Info      ||       ", 
        "2010-06-10 16:05:50+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-48-805306368||MSDTC ||2444    ||Info      ||'0';'0';'0';'0';'0';'0'", 
        "2010-06-10 16:06:04+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-87-1761624320||LoadPerf||1000    ||Info      ||'WmiApRpl';'WmiApRpl'", 
        "2010-06-10 16:06:05+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-87-1761624320||LoadPerf||1001    ||Info      ||'WmiApRpl';'WmiApRpl'", 
        "2010-06-10 16:06:05+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-87-1761624320||LoadPerf||1000    ||Info      ||'WmiApRpl';'WmiApRpl'", 
        "2010-06-10 16:06:12+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-1-5-18||WinMgmt||63      ||Warning   ||'HiPerfCooker_v1';'Root\\\\WMI'", 
        "2010-06-10 16:06:13+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-1-5-18||WinMgmt||63      ||Warning   ||'CmdTriggerConsumer';'Root\\\\cimv2'", 
        "2010-06-10 16:06:13+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-1-5-18||WinMgmt||63      ||Warning   ||'CmdTriggerConsumer';'Root\\\\cimv2'", 
        "2010-06-10 16:06:15+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-67-1845523456||LoadPerf||1000    ||Info      ||'ContentIndex';'ContentIndex'", 
        "2010-06-10 16:06:15+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-67-1845523456||LoadPerf||1000    ||Info      ||'ContentFilter';'ContentFilter'", 
        "2010-06-10 16:06:15+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-73-1090539520||LoadPerf||1000    ||Info      ||'ISAPISearch';'ISAPISearch'", 
        "2010-06-10 16:07:52+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-1-5-18||WinMgmt||5603    ||Warning   ||'Rsop Planning Mode Provider';'root\\\\RSOP'", 
        "2010-06-10 16:07:52+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-1-5-18||WinMgmt||5603    ||Warning   ||'Rsop Planning Mode Provider';'root\\\\RSOP'", 
        "2010-06-10 16:07:55+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-70-1912632064||COM+  ||4156    ||Info      ||'First attemp to CoCreateInstance(CLSID_ComSystemAppEventData) failed!'", 
        "2010-06-10 16:07:55+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-82-1828744960||COM+  ||4156    ||Info      ||'Remove old EventClass(CLSID_ComSystemAppEventData) from event system!.'", 
        "2010-06-10 16:07:55+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-65-1677747456||COM+  ||4156    ||Info      ||'Added EventClass(CLSID_ComSystemAppEventData) to event system!.'", 
        "2010-06-10 16:07:55+0000||AppEvent.Evt||BILLY-DB5B96DD3||S-82-1728080128||COM+  ||4156    ||Info      ||'RegisterComSystemAppEventData() succeeded!  Will re-try CoCreateInstance(CLSID_ComSystemAppEventData)'", 
        "2010-06-10 16:08:07+0000||AppEvent.Evt||        ||S-0-0||WmdmPm||100     ||Info      ||       ", 
        "2010-06-10 12:01:43+0000||SysEvent.Evt||MACHINENAME||S-53-805318912||EventLog||6009    ||Info      ||'5.01.';'2600';'Service Pack 2';'Uniprocessor Free'", 
        "2010-06-10 12:01:43+0000||SysEvent.Evt||MACHINENAME||S-0-57344||EventLog||6005    ||Info      ||       ", 
        "2010-06-10 12:02:06+0000||SysEvent.Evt||MACHINENAME||S-224-1281772645||Serial||2       ||Info      ||'\\\\Device\\\\Serial0';'\\\\Device\\\\Serial0'", 
        "2010-06-10 12:02:06+0000||SysEvent.Evt||MACHINENAME||S-224-1281772645||Serial||2       ||Info      ||'\\\\Device\\\\Serial1';'\\\\Device\\\\Serial1'", 
        "2010-06-10 16:04:44+0000||SysEvent.Evt||BILLY-DB5B96DD3||S-77-1124091904||EventLog||6011    ||Info      ||'MACHINENAME';'BILLY-DB5B96DD3'", 
        "2010-06-10 16:05:19+0000||SysEvent.Evt||BILLY-DB5B96DD3||S-119-1912630016||Workstation||3260    ||Info      ||'workgroup';'WORKGROUP'", 
        "2010-06-10 16:06:53+0000||SysEvent.Evt||BILLY-DB5B96DD3||S-188-1281772645||HTTP  ||15007   ||Info      ||'';'http://*:2869/'", 
        "2010-06-10 16:08:25+0000||SysEvent.Evt||BILLY-DB5B96DD3||S-1-5-18||NtServicePack||4377    ||Info      ||'Windows XP';'KB911164'", 
        "2010-06-10 16:10:54+0000||SysEvent.Evt||BILLY-DB5B96DD3||S-50-805318656||Setup ||60054   ||Info      ||'2600' ", 
        "2010-06-10 16:11:25+0000||SysEvent.Evt||BILLY-DB5B96DD3||S-53-805318912||EventLog||6009    ||Info      ||'5.01.';'2600';'Service Pack 2';'Uniprocessor Free'", 
        "2010-06-10 16:11:25+0000||SysEvent.Evt||BILLY-DB5B96DD3||S-0-29696||EventLog||6005    ||Info      ||       ", 
        "2010-06-10 16:11:36+0000||SysEvent.Evt||BILLY-DB5B96DD3||S-0-1946157056||SRService||115     ||Info      ||       ", 
        "2010-06-10 16:11:39+0000||SysEvent.Evt||BILLY-DB5B96DD3||S-1-5-18||Service Control Manager||7035    ||Info      ||'DCOM Server Process Launcher';'start'", 
        "2010-06-10 16:11:39+0000||SysEvent.Evt||BILLY-DB5B96DD3||S-1-5-18||Service Control Manager||7035    ||Info      ||'Telephony';'start'", 
        "2010-06-10 16:11:39+0000||SysEvent.Evt||BILLY-DB5B96DD3||S-1-5-18||Service Control Manager||7035    ||Info      ||'Network Location Awareness (NLA)';'start'", 
        "2010-06-10 16:11:39+0000||SysEvent.Evt||BILLY-DB5B96DD3||S-78-1946187520||Service Control Manager||7036    ||Info      ||'Network Location Awareness (NLA)';'running'", 
        "2010-06-10 16:11:39+0000||SysEvent.Evt||BILLY-DB5B96DD3||S-1-5-18||Service Control Manager||7035    ||Info      ||'Application Layer Gateway Service';'start'", 
        "2010-06-10 16:11:39+0000||SysEvent.Evt||BILLY-DB5B96DD3||S-65-1879075840||Service Control Manager||7036    ||Info      ||'Application Layer Gateway Service';'running'", 
        "2010-06-10 16:11:40+0000||SysEvent.Evt||BILLY-DB5B96DD3||S-67-1828745216||Service Control Manager||7036    ||Info      ||'Computer Browser';'stopped'", 
        "2010-06-10 16:11:43+0000||SysEvent.Evt||BILLY-DB5B96DD3||S-84-1912630528||Service Control Manager||7036    ||Info      ||'Terminal Services';'running'", 
        "2010-06-10 16:11:43+0000||SysEvent.Evt||BILLY-DB5B96DD3||S-1-5-18||Service Control Manager||7035    ||Info      ||'Fast User Switching Compatibility';'start'", 
        "2010-06-10 16:11:43+0000||SysEvent.Evt||BILL    ||S-0-0||Service Control Manager||7036    ||Info      ||       "
    ], 
    "errors": {}, 
    "return_code": 0, 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "evtlogs", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestEvtLogs", 
        "tempdir": "/var/folders/yc/4zng19655k37kyxgskb3vvf0006t70/T/tmpHPq5l9/TestEvtLogsThread-7", 
        "executed_command": "rekall  --renderer 'test' --filename '/Users/adamsh/Projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - evtlogs", 
        "testdir": "/Users/adamsh/Projects/rekall-test/tigger"
    }
}