#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestAnalyzeStruct /home/scudette/projects/rekall-test/tigger/TestAnalyzeStruct
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestAnalyzeStruct /home/scudette/projects/rekall-test/tigger/TestAnalyzeStruct
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestAnalyzeStruct /home/scudette/projects/rekall-test/tigger/TestAnalyzeStruct
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - analyze_struct 0xff3865d0
else
   less /home/scudette/projects/rekall-test/tigger/output/TestAnalyzeStruct
fi
exit 0
{
    "errors": {}, 
    "time_used": 2.7311761379241943, 
    "return_code": 0, 
    "failures": {
        "testCase (__main__.TestAnalyzeStruct)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 221, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 271, in testCase\n    self.assertEqual(previous, current)\nAssertionError: u'0x00000000||Data:0x1b0003' != u'       0x0||Data:0x1b0003'\n- 0x00000000||Data:0x1b0003\n+        0x0||Data:0x1b0003\n\n"
    }, 
    "output": [
        "0xff3865d0 is inside pool allocation with tag 'Pro\\xe3' (0xff3865b0)", 
        "  Offset  ||Content", 
        "----------||-------", 
        "       0x0||Data:0x1b0003", 
        "       0x4||Data:0x0", 
        "       0x8||Data:0xff3865d8 _LIST_ENTRY @0xff3865d8 Empty Tag:Pro\\xe3 @0xff3865d8", 
        "       0xc||Data:0xff3865d8", 
        "      0x10||Data:0xff3865e0 _LIST_ENTRY @0xff3865e0 Empty Tag:Pro\\xe3 @0xff3865e0", 
        "      0x14||Data:0xff3865e0", 
        "      0x18||Data:0x6cc0280", 
        "      0x1c||Data:0x2c3c", 
        "      0x20||Data:0x0", 
        "      0x24||Data:0x0", 
        "      0x28||Data:0x0", 
        "      0x2c||Data:0x0", 
        "      0x30||Data:0x20ac", 
        "      0x34||Data:0x0", 
        "      0x38||Data:0x2d", 
        "      0x3c||Data:0xe", 
        "      0x40||Data:0xff386610 _LIST_ENTRY @0xff386610 Empty Tag:Pro\\xe3 @0xff386610", 
        "      0x44||Data:0xff386610", 
        "      0x48||Data:0x0", 
        "      0x4c||Data:0x0", 
        "      0x50||Data:0xff247f58 _LIST_ENTRY @0xff247f58", 
        "      0x54||Data:0xff1f9cc0", 
        "      0x58||Data:0x0", 
        "      0x5c||Data:0x1", 
        "      0x60||Data:0x12080009", 
        "      0x64||Data:0x0", 
        "      0x68||Data:0x0", 
        "      0x6c||Data:0x0", 
        "      0x70||Data:0xc1ea8c78", 
        "      0x74||Data:0x1cb391b", 
        "      0x78||Data:0x0", 
        "      0x7c||Data:0x0"
    ], 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "analyze_struct 0xff3865d0", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestAnalyzeStruct", 
        "tempdir": "/tmp/tmpblovS9/TestAnalyzeStructThread-4", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - analyze_struct 0xff3865d0", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}