#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestPtoV /home/scudette/projects/rekall-test/tigger/TestPtoV
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestPtoV /home/scudette/projects/rekall-test/tigger/TestPtoV
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestPtoV /home/scudette/projects/rekall-test/tigger/TestPtoV
elif [ "$1" == "run" ]; then
   rekall  -v --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/tigger/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - ptov 0x115b8d8
else
   less /home/scudette/projects/rekall-test/tigger/output/TestPtoV
fi
exit 0
{
    "failours": {
        "testCase (__main__.TestPtoV)": {
            "testCase (__main__.TestPtoV)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 252, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 302, in testCase\n    self.assertListEqual(previous, current)\n  File \"/home/scudette/rekall/rekall-core/rekall/testlib.py\", line 227, in assertListEqual\n    self.assertEqual(x, y)\nAssertionError: u'DTB @ 0x31d000' != u'DTB 0x31d000 Owning process: 0x80551b80||Idle||    0'\n- DTB @ 0x31d000\n+ DTB 0x31d000 Owning process: 0x80551b80||Idle||    0\n\n"
        }
    }, 
    "errors": {
        "testCase (__main__.TestPtoV)": {}
    }, 
    "logging": [
        "2016-05-10 13:54:22,002:DEBUG:rekall.1:Logging level set to 10", 
        "2016-05-10 13:54:22,003:DEBUG:rekall.1:Voting round with base: None", 
        "2016-05-10 13:54:22,004:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-05-10 13:54:22,004:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided", 
        "2016-05-10 13:54:22,004:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-05-10 13:54:22,004:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space", 
        "2016-05-10 13:54:22,004:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-05-10 13:54:22,005:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided", 
        "2016-05-10 13:54:22,005:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-05-10 13:54:22,005:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided", 
        "2016-05-10 13:54:22,006:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-05-10 13:54:22,006:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space", 
        "2016-05-10 13:54:22,006:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-05-10 13:54:22,006:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space", 
        "2016-05-10 13:54:22,006:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-05-10 13:54:22,006:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided", 
        "2016-05-10 13:54:22,007:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-05-10 13:54:22,007:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided", 
        "2016-05-10 13:54:22,007:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-05-10 13:54:22,007:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space", 
        "2016-05-10 13:54:22,007:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-05-10 13:54:22,007:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.", 
        "2016-05-10 13:54:22,008:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-05-10 13:54:22,013:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume", 
        "2016-05-10 13:54:22,013:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-05-10 13:54:22,013:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at /home/scudette/projects/rekall-test/tigger/tigger.vmem.E01_info", 
        "2016-05-10 13:54:22,013:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-05-10 13:54:22,013:DEBUG:rekall.1:Succeeded instantiating FileAddressSpace", 
        "2016-05-10 13:54:22,014:DEBUG:rekall.1:Voting round with base: FileAddressSpace", 
        "2016-05-10 13:54:22,014:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-05-10 13:54:22,016:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x9465645", 
        "2016-05-10 13:54:22,016:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-05-10 13:54:22,016:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-05-10 13:54:22,016:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-05-10 13:54:22,016:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-05-10 13:54:22,017:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-05-10 13:54:22,025:DEBUG:rekall.1:Succeeded instantiating EWFAddressSpace", 
        "2016-05-10 13:54:22,025:DEBUG:rekall.1:Voting round with base: EWFAddressSpace", 
        "2016-05-10 13:54:22,025:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "2016-05-10 13:54:22,028:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0xf000ff53", 
        "2016-05-10 13:54:22,028:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "2016-05-10 13:54:22,028:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "2016-05-10 13:54:22,028:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "2016-05-10 13:54:22,028:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "2016-05-10 13:54:22,028:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "2016-05-10 13:54:22,029:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "2016-05-10 13:54:22,029:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "2016-05-10 13:54:22,029:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "2016-05-10 13:54:22,029:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "2016-05-10 13:54:22,029:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "2016-05-10 13:54:22,030:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "2016-05-10 13:54:22,030:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "2016-05-10 13:54:22,030:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "2016-05-10 13:54:22,030:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "2016-05-10 13:54:22,030:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "2016-05-10 13:54:22,030:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "2016-05-10 13:54:22,030:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "2016-05-10 13:54:22,031:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature", 
        "2016-05-10 13:54:22,031:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "2016-05-10 13:54:22,032:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space", 
        "2016-05-10 13:54:22,032:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "2016-05-10 13:54:22,032:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.", 
        "2016-05-10 13:54:22,032:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "2016-05-10 13:54:22,032:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space", 
        "2016-05-10 13:54:22,033:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> ", 
        "2016-05-10 13:54:22,033:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space", 
        "2016-05-10 13:54:22,033:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> ", 
        "2016-05-10 13:54:22,034:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified", 
        "2016-05-10 13:54:22,034:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> ", 
        "2016-05-10 13:54:22,034:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.", 
        "2016-05-10 13:54:22,035:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> ", 
        "2016-05-10 13:54:22,035:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified", 
        "2016-05-10 13:54:22,035:INFO:rekall.1:Autodetected physical address space EWFAddressSpace", 
        "2016-05-10 13:54:22,035:DEBUG:rekall.1:Will detect profile using these Detectors: linux_index,nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux", 
        "2016-05-10 13:54:22,036:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-profiles/v1.0/inventory.gz", 
        "2016-05-10 13:54:22,052:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/inventory.gz", 
        "2016-05-10 13:54:22,053:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/Linux/index.gz", 
        "2016-05-10 13:54:22,061:INFO:rekall.1:Loaded profile Linux/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.00850605964661 sec)", 
        "2016-05-10 13:54:22,062:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/eprocess_index.gz", 
        "2016-05-10 13:54:22,098:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.0369770526886 sec)", 
        "2016-05-10 13:54:22,099:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/index.gz", 
        "2016-05-10 13:54:22,214:INFO:rekall.1:Loaded profile nt/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.115004062653 sec)", 
        "2016-05-10 13:54:22,214:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/OSX/index.gz", 
        "2016-05-10 13:54:22,215:INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.000909090042114 sec)", 
        "2016-05-10 13:54:22,216:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/pe.gz", 
        "2016-05-10 13:54:22,235:INFO:rekall.1:Loaded profile pe from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.019180059433 sec)", 
        "2016-05-10 13:54:22,235:DEBUG:rekall.1:Trying method pe, offset 0", 
        "2016-05-10 13:54:22,238:DEBUG:rekall.1:Trying method windows_kernel_file, offset 0", 
        "2016-05-10 13:54:22,239:DEBUG:rekall.1:Trying method rsds, offset 0", 
        "2016-05-10 13:54:22,239:DEBUG:rekall.1:Trying method linux_index, offset 0", 
        "2016-05-10 13:54:22,239:DEBUG:rekall.1:LinuxIndexDetector:DetectFromHit(0) = None", 
        "2016-05-10 13:54:22,239:DEBUG:rekall.1:Trying method nt_index, offset 0", 
        "2016-05-10 13:54:22,240:DEBUG:rekall.1:Trying method ntfs, offset 0", 
        "2016-05-10 13:54:22,240:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/ntfs.gz", 
        "2016-05-10 13:54:22,247:INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.00711297988892 sec)", 
        "2016-05-10 13:54:22,632:DEBUG:rekall.1:Opened local file /home/scudette/projects/rekall-test/profile_cache/v1.0/nt/GUID/BD8F451F3E754ED8A34B50560CEB08E31.gz", 
        "2016-05-10 13:54:22,839:INFO:rekall.1:Loaded profile nt/GUID/BD8F451F3E754ED8A34B50560CEB08E31 from Local Cache Directory:/home/scudette/projects/rekall-test/profile_cache (in 0.20676612854 sec)", 
        "2016-05-10 13:54:23,115:DEBUG:rekall.1:Found _EPROCESS @ 0x551B80 (DTB: 0x319000)", 
        "2016-05-10 13:54:23,132:INFO:rekall.1:Detected ntkrnlpa.pdb with GUID BD8F451F3E754ED8A34B50560CEB08E31", 
        "2016-05-10 13:54:23,132:DEBUG:rekall.1:Detection method rsds worked at offset 0x4e0508", 
        "2016-05-10 13:54:23,135:DEBUG:rekall.1:Running plugin (ptov) with args (()) kwargs ({'profile': None, 'proc_regex': None, 'phys_eprocess': None, 'pid': None, 'physical_address': 18200792, 'eprocess': None, 'method': ['PsActiveProcessHead', 'CSRSS', 'PspCidTable', 'Sessions', 'Handles']})", 
        "2016-05-10 13:54:23,307:INFO:rekall.1:Detected kernel base at 0x804D7000"
    ], 
    "time_used": 3.209713935852051, 
    "return_code": 0, 
    "output": [
        "DTB 0x31d000 Owning process: 0x80551b80||Idle||    0", 
        "PDE@ 0x31d010 = 0x31c063", 
        "PTE@ 0x31c038 = 0x1244163", 
        "Physical Address 0x115b8d8", 
        "Virtual Address 0x80ff88d8 (DTB   0x31d000)"
    ], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "--format": "test", 
        "commandline": "ptov 0x115b8d8", 
        "script": "search('select details AS path from handles where _EPROCESS.pid == 1968 and obj_type == \"File\"')", 
        "pid": 1724, 
        "test_class": "TestPtoV", 
        "--cache_dir": "/home/scudette/projects/rekall-test/tigger/../profile_cache/", 
        "--cache": "memory", 
        "tempdir": "/tmp/tmpR63XuI/TestPtoVThread-4", 
        "executed_command": "rekall  -v --cache 'memory' --cache_dir '/home/scudette/projects/rekall-test/tigger/../profile_cache/' --format 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - ptov 0x115b8d8", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}