#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /Users/scudette/projects/rekall-test/tigger/output/TestMemoryTranslation /Users/scudette/projects/rekall-test/tigger/TestMemoryTranslation
elif [ "$1" == "meld" ]; then
   meld /Users/scudette/projects/rekall-test/tigger/output/TestMemoryTranslation /Users/scudette/projects/rekall-test/tigger/TestMemoryTranslation
elif [ "$1" == "diff" ]; then
   diff /Users/scudette/projects/rekall-test/tigger/output/TestMemoryTranslation /Users/scudette/projects/rekall-test/tigger/TestMemoryTranslation
elif [ "$1" == "run" ]; then
   rekall  -v --cache 'memory' --cache_dir '/Users/scudette/projects/rekall-test/tigger/../profile_cache/' --format 'test' --filename '/Users/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - inspect_vaddr "nt"
else
   less /Users/scudette/projects/rekall-test/tigger/output/TestMemoryTranslation
fi
exit 0
{
    "failours": {
        "testCase (__main__.TestMemoryTranslation)": {
            "testCase (__main__.TestMemoryTranslation)": "Traceback (most recent call last):\n  File \"/Users/scudette/projects/rekall/rekall-core/rekall/testlib.py\", line 234, in run\n    testMethod()\n  File \"/Users/scudette/projects/rekall/rekall-core/rekall/testlib.py\", line 284, in testCase\n    self.assertEqual(previous, current)\nAssertionError: 6 != 3\n"
        }
    }, 
    "errors": {
        "testCase (__main__.TestMemoryTranslation)": {}
    }, 
    "logging": [
        "DEBUG:rekall.1:Logging level set to 10", 
        "DEBUG:rekall.1:Running plugin (inspect_vaddr) with args (()) kwargs ({'address': 'nt'})", 
        "DEBUG:rekall.1:Voting round with base: None", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at /Users/scudette/projects/rekall-test/tigger/tigger.vmem.E01_info", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "DEBUG:rekall.1:Succeeded instantiating FileAddressSpace", 
        "DEBUG:rekall.1:Voting round with base: FileAddressSpace", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x9465645", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "DEBUG:rekall.1:Succeeded instantiating EWFAddressSpace", 
        "DEBUG:rekall.1:Voting round with base: EWFAddressSpace", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0xf000ff53", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> ", 
        "DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> ", 
        "DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> ", 
        "DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.", 
        "DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> ", 
        "DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified", 
        "INFO:rekall.1:Autodetected physical address space EWFAddressSpace", 
        "DEBUG:rekall.1:Will detect profile using these Detectors: nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux", 
        "DEBUG:rekall.1:Opened url https://raw.githubusercontent.com/google/rekall-profiles/master/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Opened local file /Users/scudette/projects/rekall-test/profile_cache/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Opened local file /Users/scudette/projects/rekall-test/profile_cache/v1.0/inventory.gz", 
        "DEBUG:rekall.1:Opened local file /Users/scudette/projects/rekall-test/profile_cache/v1.0/nt/eprocess_index.gz", 
        "INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/Users/scudette/projects/rekall-test/profile_cache (in 0.00747609138489 sec)", 
        "DEBUG:rekall.1:Opened local file /Users/scudette/projects/rekall-test/profile_cache/v1.0/nt/index.gz", 
        "INFO:rekall.1:Loaded profile nt/index from Local Cache Directory:/Users/scudette/projects/rekall-test/profile_cache (in 0.0111110210419 sec)", 
        "DEBUG:rekall.1:Opened local file /Users/scudette/projects/rekall-test/profile_cache/v1.0/OSX/index.gz", 
        "INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:/Users/scudette/projects/rekall-test/profile_cache (in 0.000442028045654 sec)", 
        "DEBUG:rekall.1:Opened local file /Users/scudette/projects/rekall-test/profile_cache/v1.0/pe.gz", 
        "INFO:rekall.1:Loaded profile pe from Local Cache Directory:/Users/scudette/projects/rekall-test/profile_cache (in 0.0180649757385 sec)", 
        "DEBUG:rekall.1:Opened local file /Users/scudette/projects/rekall-test/profile_cache/v1.0/ntfs.gz", 
        "INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:/Users/scudette/projects/rekall-test/profile_cache (in 0.00128197669983 sec)", 
        "DEBUG:rekall.1:Opened local file /Users/scudette/projects/rekall-test/profile_cache/v1.0/nt/GUID/BD8F451F3E754ED8A34B50560CEB08E31.gz", 
        "INFO:rekall.1:Loaded profile nt/GUID/BD8F451F3E754ED8A34B50560CEB08E31 from Local Cache Directory:/Users/scudette/projects/rekall-test/profile_cache (in 0.159232139587 sec)", 
        "DEBUG:rekall.1:Found _EPROCESS @ 0x551B80 (DTB: 0x319000)", 
        "INFO:rekall.1:Detected ntkrnlpa.pdb with GUID BD8F451F3E754ED8A34B50560CEB08E31", 
        "DEBUG:rekall.1:Detection method rsds worked at offset 0x4e0508", 
        "INFO:rekall.1:Detected kernel base at 0x804D7000"
    ], 
    "time_used": 2.8667609691619873, 
    "return_code": 0, 
    "output": [
        "        Address Space         ||  Offset  ||           Base AS            ||Base AS Offset", 
        "------------------------------||----------||------------------------------||--------------", 
        "Kernel AS@0x319000            ||0x804d7000||tigger.vmem.E01 (EWF)         ||0x004d7000    "
    ], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/Users/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "--format": "test", 
        "commandline": "inspect_vaddr \"nt\"", 
        "pid": 1724, 
        "test_class": "TestMemoryTranslation", 
        "--cache_dir": "/Users/scudette/projects/rekall-test/tigger/../profile_cache/", 
        "--cache": "memory", 
        "tempdir": "/var/folders/y8/670pn1dx55x01z5fs_6r2gnh003jp1/T/tmpYUQ9GB/TestMemoryTranslationThread-2", 
        "executed_command": "rekall  -v --cache 'memory' --cache_dir '/Users/scudette/projects/rekall-test/tigger/../profile_cache/' --format 'test' --filename '/Users/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - inspect_vaddr \"nt\"", 
        "testdir": "/Users/scudette/projects/rekall-test/tigger"
    }
}