#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestWin32kAutodetect /home/scudette/projects/rekall-test/tigger/TestWin32kAutodetect
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestWin32kAutodetect /home/scudette/projects/rekall-test/tigger/TestWin32kAutodetect
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestWin32kAutodetect /home/scudette/projects/rekall-test/tigger/TestWin32kAutodetect
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - win32k_autodetect
else
   less /home/scudette/projects/rekall-test/tigger/output/TestWin32kAutodetect
fi
exit 0
{
    "errors": {}, 
    "time_used": 22.54390597343445, 
    "return_code": 0, 
    "failures": {
        "testCase (__main__.TestWin32kAutodetect)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 221, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 271, in testCase\n    self.assertEqual(previous, current)\nAssertionError: u\"rpwinstaNext        ||0x00000004||['Pointer', {'target': 'tagWINDOWSTATION'}]\" [truncated]... != u\"rpwinstaNext        ||       0x4||['Pointer', {'target': 'tagWINDOWSTATION'}]\" [truncated]...\n- rpwinstaNext        ||0x00000004||['Pointer', {'target': 'tagWINDOWSTATION'}]\n?                         -------\n+ rpwinstaNext        ||       0x4||['Pointer', {'target': 'tagWINDOWSTATION'}]\n?                       +++++++\n\n"
    }, 
    "output": [
        "", 
        "************ Struct tagWINDOWSTATION ************", 
        "       field        ||  offset  ||Definition", 
        "--------------------||----------||----------", 
        "rpwinstaNext        ||       0x4||['Pointer', {'target': 'tagWINDOWSTATION'}]", 
        "rpdeskList          ||       0x8||['Pointer', {'target': 'tagDESKTOP'}]", 
        "pTerm               ||       0xc||['Pointer', {'target': 'tagTERMINAL'}]", 
        "pGlobalAtomTable    ||      0x40||['Pointer', {'target': '_RTL_ATOM_TABLE'}]", 
        "", 
        "************** Struct tagTHREADINFO **************", 
        "       field        ||  offset  ||Definition", 
        "--------------------||----------||----------", 
        "pEThread            ||       0x0||['Pointer', {'target': '_ETHREAD'}]", 
        "ppi                 ||      0x2c||['Pointer', {'target': 'tagPROCESSINFO'}]", 
        "pq                  ||      0x30||['Pointer', {'target': 'tagQ'}]", 
        "spklActive          ||      0x34||['Pointer', {'target': 'tagKL'}]", 
        "rpdesk              ||      0x3c||['Pointer', {'target': 'tagDESKTOP'}]", 
        "PtiLink             ||      0xac||['_LIST_ENTRY']", 
        "", 
        "*************** Struct tagDESKTOP ***************", 
        "       field        ||  offset  ||Definition", 
        "--------------------||----------||----------", 
        "rpdeskNext          ||       0xc||['Pointer', {'target': 'tagDESKTOP'}]", 
        "rpwinstaParent      ||      0x10||['Pointer', {'target': 'tagWINDOWSTATION'}]", 
        "hsectionDesktop     ||      0x40||['Pointer', {'target': '_SECTION_OBJECT'}]"
    ], 
    "options": {
        "--name_resolution_strategies": "Module,Symbol", 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "win32k_autodetect", 
        "pid": 1724, 
        "--renderer": "test", 
        "test_class": "TestWin32kAutodetect", 
        "tempdir": "/tmp/tmpblovS9/TestWin32kAutodetectThread-2", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module,Symbol' - win32k_autodetect", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}