#!/bin/bash
if [ "$1" == "ok" ]; then
   cp /home/scudette/projects/rekall-test/tigger/output/TestDisassemble /home/scudette/projects/rekall-test/tigger/TestDisassemble
elif [ "$1" == "meld" ]; then
   meld /home/scudette/projects/rekall-test/tigger/output/TestDisassemble /home/scudette/projects/rekall-test/tigger/TestDisassemble
elif [ "$1" == "diff" ]; then
   diff /home/scudette/projects/rekall-test/tigger/output/TestDisassemble /home/scudette/projects/rekall-test/tigger/TestDisassemble
elif [ "$1" == "run" ]; then
   rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - dis -l 50 nt!MmGetPhysicalMemoryRanges --name_resolution_strategies Export
else
   less /home/scudette/projects/rekall-test/tigger/output/TestDisassemble
fi
exit 0
{
    "errors": {}, 
    "time_used": 4.166470050811768, 
    "return_code": 0, 
    "failures": {
        "testCase (rekall.plugins.windows.disassembler.TestDisassemble)": "Traceback (most recent call last):\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 227, in run\n    testMethod()\n  File \"/home/scudette/rekall/rekall/testlib.py\", line 277, in testCase\n    self.assertEqual(previous, current)\nAssertionError: u'Address||Rel ||      Op Codes      ||         Instruction          ||Comment' != u'Address||   Rel    ||      Op Codes      ||         Instruction          ||Com [truncated]...\n- Address||Rel ||      Op Codes      ||         Instruction          ||Comment\n+ Address||   Rel    ||      Op Codes      ||         Instruction          ||Comment\n?          +++    +++\n\n"
    }, 
    "output": [
        "Address||   Rel    ||      Op Codes      ||         Instruction          ||Comment", 
        "-------||----------||--------------------||------------------------------||-------", 
        "------ nt!MmGetPhysicalMemoryRanges ------", 
        " ||0x8063f386||       0x0||8bff                ||MOV EDI, EDI                  ||       ", 
        " ||0x8063f388||       0x2||55                  ||PUSH EBP                      ||       ", 
        " ||0x8063f389||       0x3||8bec                ||MOV EBP, ESP                  ||       ", 
        " ||0x8063f38b||       0x5||51                  ||PUSH ECX                      ||       ", 
        " ||0x8063f38c||       0x6||51                  ||PUSH ECX                      ||       ", 
        " ||0x8063f38d||       0x7||53                  ||PUSH EBX                      ||       ", 
        " ||0x8063f38e||       0x8||56                  ||PUSH ESI                      ||       ", 
        " ||0x8063f38f||       0x9||b980755580          ||MOV ECX, 0x80557580           ||nt!MmDynamicMemoryMutex", 
        " ||0x8063f394||       0xe||ff150c774d80        ||CALL DWORD [0x804d770c]       ||0x806d0744 nt!imp_@ExAcquireFastMutex@4 -> hal!ExAcquireFastMutex", 
        " ||0x8063f39a||      0x14||a148315580          ||MOV EAX, [0x80553148]         ||0x810ddd10 nt!MmPhysicalMemoryBlock", 
        " ||0x8063f39f||      0x19||8b00                ||MOV EAX, [EAX]                ||       ", 
        " ||0x8063f3a1||      0x1b||40                  ||INC EAX                       ||       ", 
        " ||0x8063f3a2||      0x1c||684d6d5068          ||PUSH DWORD 0x68506d4d         ||       ", 
        " ||0x8063f3a7||      0x21||c1e004              ||SHL EAX, 0x4                  ||       ", 
        " ||0x8063f3aa||      0x24||50                  ||PUSH EAX                      ||       ", 
        " ||0x8063f3ab||      0x25||33db                ||XOR EBX, EBX                  ||       ", 
        " ||0x8063f3ad||      0x27||53                  ||PUSH EBX                      ||       ", 
        " ||0x8063f3ae||      0x28||e8cd4cf0ff          ||CALL 0x80544080               ||nt!ExAllocatePoolWithTag", 
        " ||0x8063f3b3||      0x2d||8bf0                ||MOV ESI, EAX                  ||       ", 
        " ||0x8063f3b5||      0x2f||3bf3                ||CMP ESI, EBX                  ||       ", 
        " ||0x8063f3b7||      0x31||8975f8              ||MOV [EBP-0x8], ESI            ||       ", 
        " ||0x8063f3ba||      0x34||7475                ||JZ 0x8063f431                 ||nt!MmGetPhysicalMemoryRanges + 0xab", 
        " ||0x8063f3bc||      0x36||57                  ||PUSH EDI                      ||       ", 
        " ||0x8063f3bd||      0x37||ff3528055580        ||PUSH DWORD [0x80550528]       ||0x804d7320 nt!ExPageLockHandle -> nt!_safe_se_handler_count + 0x30d", 
        " ||0x8063f3c3||      0x3d||e80ecdf5ff          ||CALL 0x8059c0d6               ||nt!MmLockPagableSectionByHandle", 
        " ||0x8063f3c8||      0x42||ff1514774d80        ||CALL DWORD [0x804d7714]       ||0x806d0298 nt!imp__KeRaiseIrqlToDpcLevel -> hal!KeRaiseIrqlToDpcLevel", 
        " ||0x8063f3ce||      0x48||8845ff              ||MOV [EBP-0x1], AL             ||       ", 
        " ||0x8063f3d1||      0x4b||a148315580          ||MOV EAX, [0x80553148]         ||0x810ddd10 nt!MmPhysicalMemoryBlock", 
        " ||0x8063f3d6||      0x50||33ff                ||XOR EDI, EDI                  ||       ", 
        " ||0x8063f3d8||      0x52||3918                ||CMP [EAX], EBX                ||       ", 
        " ||0x8063f3da||      0x54||7632                ||JBE 0x8063f40e                ||nt!MmGetPhysicalMemoryRanges + 0x88", 
        " ||0x8063f3dc||      0x56||b900100000          ||MOV ECX, 0x1000               ||       ", 
        " ||0x8063f3e1||      0x5b||8b44f808            ||MOV EAX, [EAX+EDI*8+0x8]      ||       ", 
        " ||0x8063f3e5||      0x5f||8bd1                ||MOV EDX, ECX                  ||       ", 
        " ||0x8063f3e7||      0x61||f7e2                ||MUL EDX                       ||       ", 
        " ||0x8063f3e9||      0x63||895604              ||MOV [ESI+0x4], EDX            ||       ", 
        " ||0x8063f3ec||      0x66||8906                ||MOV [ESI], EAX                ||       ", 
        " ||0x8063f3ee||      0x68||a148315580          ||MOV EAX, [0x80553148]         ||0x810ddd10 nt!MmPhysicalMemoryBlock", 
        " ||0x8063f3f3||      0x6d||8b44f80c            ||MOV EAX, [EAX+EDI*8+0xc]      ||       ", 
        " ||0x8063f3f7||      0x71||8bd1                ||MOV EDX, ECX                  ||       ", 
        " ||0x8063f3f9||      0x73||f7e2                ||MUL EDX                       ||       ", 
        " ||0x8063f3fb||      0x75||894608              ||MOV [ESI+0x8], EAX            ||       ", 
        " ||0x8063f3fe||      0x78||89560c              ||MOV [ESI+0xc], EDX            ||       ", 
        " ||0x8063f401||      0x7b||a148315580          ||MOV EAX, [0x80553148]         ||0x810ddd10 nt!MmPhysicalMemoryBlock", 
        " ||0x8063f406||      0x80||83c610              ||ADD ESI, 0x10                 ||       ", 
        " ||0x8063f409||      0x83||47                  ||INC EDI                       ||       ", 
        " ||0x8063f40a||      0x84||3b38                ||CMP EDI, [EAX]                ||       ", 
        " ||0x8063f40c||      0x86||72d3                ||JB 0x8063f3e1                 ||nt!MmGetPhysicalMemoryRanges + 0x5b", 
        " ||0x8063f40e||      0x88||8a4dff              ||MOV CL, [EBP-0x1]             ||       ", 
        " ||0x8063f411||      0x8b||891e                ||MOV [ESI], EBX                ||       ", 
        " ||0x8063f413||      0x8d||895e04              ||MOV [ESI+0x4], EBX            ||       "
    ], 
    "options": {
        "--name_resolution_strategies": [
            "Module", 
            "Symbol"
        ], 
        "executable": "rekall ", 
        "--filename": "/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01", 
        "commandline": "dis -l %(length)s %(func)s --name_resolution_strategies Export", 
        "pid": 1724, 
        "--renderer": "test", 
        "length": 50, 
        "test_class": "TestDisassemble", 
        "func": "nt!MmGetPhysicalMemoryRanges", 
        "tempdir": "/tmp/tmpgj4t19/TestDisassembleThread-2", 
        "executed_command": "rekall  --renderer 'test' --filename '/home/scudette/projects/rekall-test/tigger/tigger.vmem.E01' --name_resolution_strategies 'Module' 'Symbol' - dis -l 50 nt!MmGetPhysicalMemoryRanges --name_resolution_strategies Export", 
        "testdir": "/home/scudette/projects/rekall-test/tigger"
    }
}